"""Specs de las lecciones del motor y framework (L5-L9).

A partir de aquí los ejercicios usan el paquete `exchange` que el alumno ha ido
construyendo. Market.sample() da 500 snapshots de BTCUSDT sin configurar rutas.
"""

LESSONS = []

# ---------------------------------------------------------------------------
# L5 — Microstructure — Leer el libro
# ---------------------------------------------------------------------------
LESSONS.append({
    "n": 5, "slug": "05-microstructure-reading-book",
    "title": "Microestructura — Leer el libro",
    "piece": "métricas de mercado sobre snapshots reales de BTC",
    "objective": "Cargar 500 snapshots reales de BTCUSDT y leer el mercado: spread, mid, imbalance, microprice y profundidad. El OrderBook deja de ser una foto y se vuelve una lente.",
    "frase": "El imbalance y el microprice te dicen hacia dónde empuja el libro antes de que se mueva el mid.",
    "concepts": [
        ("El libro como lente",
         "Cargas un snapshot y el OrderBook te da spread y mid en una línea. Pero lo interesante está más adentro: cuánta liquidez hay, y de qué lado.",
         "from exchange import Market\nm = Market.sample()\nbook = m.step()\nbook.spread, book.mid"),
        ("Imbalance: presión del libro",
         "Más tamaño en bids que en asks (imbalance > 0) suele preceder subidas de mid. Es una de las señales más usadas en microestructura.",
         "book.imbalance(levels=1)   # nivel 1\nbook.imbalance(levels=5)   # 5 niveles"),
        ("Microprice y profundidad",
         "El microprice pondera el mid por el tamaño contrario: mejor predictor a corto que el mid simple. La profundidad mide cuánto aguanta el libro un golpe.",
         "book.microprice\nbook.depth(Side.BUY, levels=5)"),
    ],
    "build": [
        {"title": "1. Carga el mercado", "practice": "Market.sample y step",
         "statement": "Crea `m = Market.sample()` y avanza un snapshot: `book = m.step()`. Guarda `n = len(m)`.",
         "starter": "from exchange import Market\n# m, book, n\n",
         "validator": "from exchange import OrderBook\nassert n == 500, 'deben ser 500 snapshots'\nassert isinstance(book, OrderBook)\nprint('ok')",
         "solution": "from exchange import Market\nm = Market.sample()\nbook = m.step()\nn = len(m)"},
        {"title": "2. Spread y mid del primer snapshot", "practice": "propiedades del libro",
         "statement": "Del `book`, guarda `spread` y `mid`.",
         "given": "from exchange import Market\nbook = Market.sample().step()\n",
         "starter": "spread = None\nmid = None\n",
         "validator": "assert spread > 0, 'el spread debe ser positivo'\nassert book.best_bid < mid < book.best_ask\nprint('ok  spread=%.2f mid=%.2f' % (spread, mid))",
         "solution": "spread = book.spread\nmid = book.mid"},
        {"title": "3. Imbalance a 1 y 5 niveles", "practice": "imbalance(levels)",
         "statement": "Guarda `imb1 = book.imbalance(1)` e `imb5 = book.imbalance(5)`. Ambos en [-1, 1].",
         "given": "from exchange import Market\nbook = Market.sample().step()\n",
         "starter": "imb1 = None\nimb5 = None\n",
         "validator": "assert -1 <= imb1 <= 1 and -1 <= imb5 <= 1\nprint('ok  imb1=%.3f imb5=%.3f' % (imb1, imb5))",
         "solution": "imb1 = book.imbalance(1)\nimb5 = book.imbalance(5)"},
        {"title": "4. Microprice", "practice": "microprice",
         "statement": "Guarda `micro = book.microprice`. Debe caer entre best_bid y best_ask.",
         "given": "from exchange import Market\nbook = Market.sample().step()\n",
         "starter": "micro = None\n",
         "validator": "assert book.best_bid <= micro <= book.best_ask\nprint('ok  micro=%.2f mid=%.2f' % (micro, book.mid))",
         "solution": "micro = book.microprice"},
        {"title": "5. Profundidad por lado", "practice": "depth(side, levels)",
         "statement": "Importa `Side` y guarda `bid_depth` y `ask_depth` sumando 5 niveles de cada lado.",
         "given": "from exchange import Market\nbook = Market.sample().step()\n",
         "starter": "from exchange import Side\nbid_depth = None\nask_depth = None\n",
         "validator": "assert bid_depth > 0 and ask_depth > 0\nprint('ok  bid=%.2f ask=%.2f' % (bid_depth, ask_depth))",
         "solution": "from exchange import Side\nbid_depth = book.depth(Side.BUY, 5)\nask_depth = book.depth(Side.SELL, 5)"},
    ],
    "aux": [
        {"title": "A1. Spread medio de la sesión", "practice": "recorrer el mercado",
         "statement": "Recorre todos los snapshots y guarda `avg_spread`, la media del spread.",
         "starter": "from exchange import Market\nm = Market.sample()\navg_spread = None\n",
         "validator": "assert avg_spread > 0\nprint('ok  avg_spread=%.2f' % avg_spread)",
         "solution": "from exchange import Market\nm = Market.sample()\nspreads = []\nwhile True:\n    b = m.step()\n    if b is None: break\n    spreads.append(b.spread)\navg_spread = sum(spreads) / len(spreads)"},
        {"title": "A2. ¿Predice el imbalance?", "practice": "señal vs siguiente mid",
         "statement": "Cuenta cuántas veces, cuando `imbalance(1) > 0`, el mid del siguiente snapshot sube. Guarda el conteo en `up_after_positive`.",
         "starter": "from exchange import Market\nm = Market.sample()\nup_after_positive = 0\n",
         "validator": "assert up_after_positive >= 0\nprint('ok  veces que sube tras imbalance+:', up_after_positive)",
         "solution": "from exchange import Market\nm = Market.sample()\nprev = m.step()\nup_after_positive = 0\nwhile True:\n    cur = m.step()\n    if cur is None: break\n    if prev.imbalance(1) is not None and prev.imbalance(1) > 0 and cur.mid > prev.mid:\n        up_after_positive += 1\n    prev = cur"},
    ],
})

# ---------------------------------------------------------------------------
# L6 — Órdenes y matching
# ---------------------------------------------------------------------------
LESSONS.append({
    "n": 6, "slug": "06-order-types-matching",
    "title": "Órdenes y matching",
    "piece": "MatchingEngine: cómo se cruzan las órdenes",
    "objective": "Enviar órdenes contra el libro y ver cómo se cruzan. Market, limit, IOC y FOK: cada tipo cambia el coste, la probabilidad de ejecución y el riesgo.",
    "frase": "La forma en que envías la orden decide tu coste: cruzar ya, o esperar barato y arriesgarte a no ejecutar.",
    "concepts": [
        ("El motor de cruce",
         "MatchingEngine.process(order, book) recorre el lado contrario, consume liquidez y devuelve los fills. El libro queda modificado.",
         "from exchange import MatchingEngine\nfills = MatchingEngine().process(order, book)"),
        ("Market vs limit",
         "Una market cruza al precio que haga falta hasta llenarse (caro pero seguro). Una limit solo cruza a tu precio o mejor; el resto descansa (barato pero incierto).",
         "Order('BTC', Side.BUY, 0.5, order_type=OrderType.MARKET)\nOrder('BTC', Side.BUY, 0.5, price=100, order_type=OrderType.LIMIT)"),
        ("IOC y FOK",
         "IOC cruza lo que pueda y cancela el resto (nada descansa). FOK es todo-o-nada: si no se llena entera, no se ejecuta nada.",
         "OrderType.IOC   # immediate-or-cancel\nOrderType.FOK   # fill-or-kill"),
    ],
    "build": [
        {"title": "1. Una market order se llena", "practice": "MatchingEngine + MARKET",
         "statement": "Cruza una market buy de 0.5 contra el primer snapshot. Guarda `fills` y `filled` (suma de tamaños).",
         "given": "from exchange import Market, MatchingEngine, Order, Side, OrderType\nbook = Market.sample().step()\neng = MatchingEngine()\n",
         "starter": "fills = None\nfilled = None\n",
         "validator": "assert abs(filled - 0.5) < 1e-9, 'una market siempre se llena si hay liquidez'\nassert all(f.side == Side.BUY for f in fills)\nprint('ok  fills=%d' % len(fills))",
         "solution": "order = Order('BTCUSDT', Side.BUY, 0.5, order_type=OrderType.MARKET)\nfills = eng.process(order, book)\nfilled = sum(f.size for f in fills)"},
        {"title": "2. Una limit cruza solo a su precio", "practice": "LIMIT + remanente",
         "statement": "Envía una limit buy enorme (size=999) al `best_bid` actual. No debería cruzar nada (precio por debajo del ask). Guarda `n_fills`.",
         "given": "from exchange import Market, MatchingEngine, Order, Side, OrderType\nbook = Market.sample().step()\neng = MatchingEngine()\nbb = book.best_bid\n",
         "starter": "n_fills = None\n",
         "validator": "assert n_fills == 0, 'comprar al best_bid no cruza el ask'\nprint('ok')",
         "solution": "order = Order('BTCUSDT', Side.BUY, 999, price=bb, order_type=OrderType.LIMIT)\nfills = eng.process(order, book)\nn_fills = len(fills)"},
        {"title": "3. Una market crossing limit sí cruza", "practice": "limit marketable",
         "statement": "Envía una limit buy de 0.3 a un precio por encima del `best_ask` (best_ask + 100). Cruza. Guarda `filled`.",
         "given": "from exchange import Market, MatchingEngine, Order, Side, OrderType\nbook = Market.sample().step()\neng = MatchingEngine()\nba = book.best_ask\n",
         "starter": "filled = None\n",
         "validator": "assert abs(filled - 0.3) < 1e-9\nprint('ok')",
         "solution": "order = Order('BTCUSDT', Side.BUY, 0.3, price=ba+100, order_type=OrderType.LIMIT)\nfills = eng.process(order, book)\nfilled = sum(f.size for f in fills)"},
        {"title": "4. FOK: todo o nada", "practice": "OrderType.FOK",
         "statement": "Envía una FOK buy de tamaño 9999 (más de lo que hay) a precio muy alto. Debe devolver 0 fills. Guarda `n_fills`.",
         "given": "from exchange import Market, MatchingEngine, Order, Side, OrderType\nbook = Market.sample().step()\neng = MatchingEngine()\nba = book.best_ask\n",
         "starter": "n_fills = None\n",
         "validator": "assert n_fills == 0, 'FOK no se llena entera -> 0 fills'\nprint('ok')",
         "solution": "order = Order('BTCUSDT', Side.BUY, 9999, price=ba+1000, order_type=OrderType.FOK)\nfills = eng.process(order, book)\nn_fills = len(fills)"},
        {"title": "5. Precio efectivo de una market", "practice": "vwap de los fills",
         "statement": "Cruza una market buy de 1.0 y calcula `eff_price` = nocional total / tamaño total. Debe ser >= best_ask (pagas el barrido).",
         "given": "from exchange import Market, MatchingEngine, Order, Side, OrderType\nbook = Market.sample().step()\nba = book.best_ask\neng = MatchingEngine()\n",
         "starter": "eff_price = None\n",
         "validator": "assert eff_price >= ba - 1e-6, 'una market barre niveles: precio efectivo >= best_ask'\nprint('ok  eff=%.2f best_ask=%.2f' % (eff_price, ba))",
         "solution": "order = Order('BTCUSDT', Side.BUY, 1.0, order_type=OrderType.MARKET)\nfills = eng.process(order, book)\neff_price = sum(f.price*f.size for f in fills) / sum(f.size for f in fills)"},
    ],
    "aux": [
        {"title": "A1. Slippage por tamaño", "practice": "coste vs tamaño",
         "statement": "Para tamaños 0.1, 1.0 y 5.0, calcula el precio efectivo de una market buy. Guarda la lista `eff_prices`. Debe ser creciente (más tamaño, peor precio).",
         "starter": "from exchange import Market, MatchingEngine, Order, Side, OrderType\neff_prices = []\n",
         "validator": "assert eff_prices[0] <= eff_prices[1] <= eff_prices[2], 'más tamaño = peor precio'\nprint('ok', [round(p,1) for p in eff_prices])",
         "solution": "from exchange import Market, MatchingEngine, Order, Side, OrderType\neng = MatchingEngine()\neff_prices = []\nfor size in (0.1, 1.0, 5.0):\n    book = Market.sample().step()\n    fills = eng.process(Order('BTCUSDT', Side.BUY, size, order_type=OrderType.MARKET), book)\n    eff_prices.append(sum(f.price*f.size for f in fills)/sum(f.size for f in fills))"},
    ],
})

# ---------------------------------------------------------------------------
# L7 — Loop de simulación
# ---------------------------------------------------------------------------
LESSONS.append({
    "n": 7, "slug": "07-market-simulation-loop",
    "title": "El loop de simulación",
    "piece": "Market: reproducir snapshots y ejecutar en el tiempo",
    "objective": "Poner el tiempo en marcha: recorrer los snapshots, enviar órdenes en cada paso y llevar la cuenta de caja, inventario y equity con PositionTracker.",
    "frase": "Mercado = estado (libro) + dinámica (matching) + tiempo (el loop). Todo junto, ya simulas.",
    "concepts": [
        ("step() avanza el tiempo",
         "Market.step() reconstruye el libro desde el siguiente snapshot y lo devuelve. Cuando se acaban, devuelve None. Ese es tu reloj.",
         "while True:\n    book = m.step()\n    if book is None: break\n    ..."),
        ("submit() ejecuta contra el libro actual",
         "En cada paso puedes enviar una orden: m.submit(order) la cruza contra el libro de ese instante y te devuelve los fills.",
         "fills = m.submit(order)"),
        ("PositionTracker lleva la cuenta",
         "Aplicas cada fill al tracker y en cualquier momento consultas equity(mid). Esa es tu curva de PnL.",
         "for f in fills:\n    tracker.apply_fill(f)\ntracker.equity(book.mid)"),
    ],
    "build": [
        {"title": "1. Cuenta los pasos", "practice": "el loop step()",
         "statement": "Recorre todo el mercado con un while y cuenta los snapshots en `steps`.",
         "starter": "from exchange import Market\nm = Market.sample()\nsteps = 0\n",
         "validator": "assert steps == 500\nprint('ok')",
         "solution": "from exchange import Market\nm = Market.sample()\nsteps = 0\nwhile True:\n    book = m.step()\n    if book is None: break\n    steps += 1"},
        {"title": "2. Ejecuta una orden en un paso", "practice": "submit",
         "statement": "Avanza un paso y envía una market buy de 0.2 con `m.submit(...)`. Guarda `filled`.",
         "given": "from exchange import Market, Order, Side, OrderType\nm = Market.sample()\nm.step()\n",
         "starter": "filled = None\n",
         "validator": "assert abs(filled - 0.2) < 1e-9\nprint('ok')",
         "solution": "fills = m.submit(Order('BTCUSDT', Side.BUY, 0.2, order_type=OrderType.MARKET))\nfilled = sum(f.size for f in fills)"},
        {"title": "3. Acumula posición en el tiempo", "practice": "loop + tracker",
         "statement": "Cada 50 pasos compra 0.1 (market). Aplica los fills a un `PositionTracker`. Guarda `final_pos`.",
         "given": "from exchange import Market, Order, Side, OrderType, PositionTracker\nm = Market.sample()\ntracker = PositionTracker()\n",
         "starter": "i = 0\nfinal_pos = None\n",
         "validator": "assert final_pos > 0, 'has comprado varias veces: posición larga'\nprint('ok  pos=%.2f' % final_pos)",
         "solution": "i = 0\nwhile True:\n    book = m.step()\n    if book is None: break\n    if i % 50 == 0:\n        for f in m.submit(Order('BTCUSDT', Side.BUY, 0.1, order_type=OrderType.MARKET)):\n            tracker.apply_fill(f)\n    i += 1\nfinal_pos = tracker.position"},
        {"title": "4. Equity final", "practice": "marcar a mercado",
         "statement": "Continuando, marca el equity al último mid visto. Guarda `equity`.",
         "given": "from exchange import Market, Order, Side, OrderType, PositionTracker\nm = Market.sample()\ntracker = PositionTracker()\nlast_mid = 0\ni = 0\nwhile True:\n    book = m.step()\n    if book is None: break\n    last_mid = book.mid\n    if i % 50 == 0:\n        for f in m.submit(Order('BTCUSDT', Side.BUY, 0.1, order_type=OrderType.MARKET)):\n            tracker.apply_fill(f)\n    i += 1\n",
         "starter": "equity = None\n",
         "validator": "assert isinstance(equity, float)\nprint('ok  equity=%.2f' % equity)",
         "solution": "equity = tracker.equity(last_mid)"},
    ],
    "aux": [
        {"title": "A1. Schedule de participación", "practice": "repartir un objetivo",
         "statement": "Reparte una compra total de 1.0 en 10 trozos iguales, uno cada 50 pasos. Guarda `executed` (debe sumar ~1.0).",
         "starter": "from exchange import Market, Order, Side, OrderType, PositionTracker\nexecuted = 0.0\n",
         "validator": "assert abs(executed - 1.0) < 1e-6\nprint('ok')",
         "solution": "from exchange import Market, Order, Side, OrderType, PositionTracker\nm = Market.sample(); i = 0; executed = 0.0\nwhile True:\n    book = m.step()\n    if book is None: break\n    if i % 50 == 0 and executed < 1.0 - 1e-9:\n        for f in m.submit(Order('BTCUSDT', Side.BUY, 0.1, order_type=OrderType.MARKET)):\n            executed += f.size\n    i += 1"},
    ],
})

# ---------------------------------------------------------------------------
# L8 — Strategy + Backtest (el pico arquitectónico)
# ---------------------------------------------------------------------------
LESSONS.append({
    "n": 8, "slug": "08-strategy-framework",
    "title": "El framework: Strategy + Backtest",
    "piece": "interfaz Strategy (ABC) y el runner Backtest",
    "objective": "El corazón del curso: una estrategia solo reacciona al libro y devuelve acciones. El Backtest la cablea con el mercado y el portfolio. Cualquier estrategia se enchufa igual.",
    "frase": "Escribe una subclase de Strategy y enchúfala al mismo Backtest. Eso es polimorfismo, y es lo que hace todo modular.",
    "concepts": [
        ("La interfaz Strategy",
         "Una estrategia implementa on_book_update(book) y devuelve una lista de acciones (NewOrder/Cancel). No sabe nada del motor. Esa ignorancia es lo que la hace enchufable.",
         "class Strategy(ABC):\n    @abstractmethod\n    def on_book_update(self, book) -> list[Action]:\n        ..."),
        ("Acciones, no efectos",
         "La estrategia no ejecuta órdenes: las pide. Devuelve NewOrder(order). El Backtest decide qué hacer con ellas. Separar decisión de ejecución es la clave del diseño.",
         "return [NewOrder(Order('BTC', Side.BUY, 0.1,\n        order_type=OrderType.MARKET))]"),
        ("El Backtest lo cablea todo",
         "Recorre el mercado, pasa cada libro a la estrategia, ejecuta sus acciones contra el matching, actualiza el portfolio y mide. El mismo run() para cualquier estrategia.",
         "result = Backtest(market, mi_estrategia).run()\nresult.final_equity, result.n_fills"),
    ],
    "build": [
        {"title": "1. Tu primera estrategia", "practice": "heredar de Strategy",
         "statement": "Define `BuyOnce(Strategy)`: en el primer libro envía una market buy de 0.5; después nada.",
         "given": "from exchange import Strategy, NewOrder, Order, Side, OrderType\n",
         "starter": "class BuyOnce(Strategy):\n    def __init__(self):\n        self.done = False\n    def on_book_update(self, book):\n        pass\n",
         "validator": "from exchange import Market, Backtest\nr = Backtest(Market.sample(), BuyOnce()).run()\nassert r.n_fills >= 1 and r.final_position > 0\nprint('ok  fills=%d pos=%.2f' % (r.n_fills, r.final_position))",
         "solution": "class BuyOnce(Strategy):\n    def __init__(self):\n        self.done = False\n    def on_book_update(self, book):\n        if self.done:\n            return []\n        self.done = True\n        return [NewOrder(Order('BTCUSDT', Side.BUY, 0.5, order_type=OrderType.MARKET))]"},
        {"title": "2. Corre el Backtest", "practice": "Backtest.run",
         "statement": "Corre `BuyOnce` con `Backtest(Market.sample(), BuyOnce()).run()`. Guarda `result` y `equity`.",
         "given": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\nclass BuyOnce(Strategy):\n    def __init__(self): self.done=False\n    def on_book_update(self, book):\n        if self.done: return []\n        self.done=True\n        return [NewOrder(Order('BTCUSDT', Side.BUY, 0.5, order_type=OrderType.MARKET))]\n",
         "starter": "result = None\nequity = None\n",
         "validator": "assert result.n_steps == 500\nassert isinstance(equity, float)\nprint('ok ', result)",
         "solution": "result = Backtest(Market.sample(), BuyOnce()).run()\nequity = result.final_equity"},
        {"title": "3. Reacciona a tus fills", "practice": "el hook on_fill",
         "statement": "Define `CountingBuyer(Strategy)` que cuente sus fills en `self.n` vía `on_fill`. Compra 0.1 cada paso.",
         "given": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\n",
         "starter": "class CountingBuyer(Strategy):\n    def __init__(self):\n        self.n = 0\n    def on_book_update(self, book):\n        return [NewOrder(Order('BTCUSDT', Side.BUY, 0.1, order_type=OrderType.MARKET))]\n    def on_fill(self, fill):\n        pass\n",
         "validator": "s = CountingBuyer()\nBacktest(Market.sample(), s).run()\nassert s.n >= 1, 'on_fill debe haberse llamado'\nprint('ok  on_fill llamado %d veces' % s.n)",
         "solution": "class CountingBuyer(Strategy):\n    def __init__(self):\n        self.n = 0\n    def on_book_update(self, book):\n        return [NewOrder(Order('BTCUSDT', Side.BUY, 0.1, order_type=OrderType.MARKET))]\n    def on_fill(self, fill):\n        self.n += 1"},
        {"title": "4. Polimorfismo: cambia la estrategia, no el runner", "practice": "intercambiar subclases",
         "statement": "Define `SellOnce` (igual que BuyOnce pero vende). Córrela en el MISMO Backtest. Guarda `pos` (debe ser < 0).",
         "given": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\n",
         "starter": "class SellOnce(Strategy):\n    def __init__(self): self.done=False\n    def on_book_update(self, book):\n        pass\n\npos = None\n",
         "validator": "assert pos < 0, 'SellOnce deja posición corta — mismo runner, otra estrategia'\nprint('ok  pos=%.2f' % pos)",
         "solution": "class SellOnce(Strategy):\n    def __init__(self): self.done=False\n    def on_book_update(self, book):\n        if self.done: return []\n        self.done=True\n        return [NewOrder(Order('BTCUSDT', Side.SELL, 0.5, order_type=OrderType.MARKET))]\npos = Backtest(Market.sample(), SellOnce()).run().final_position"},
    ],
    "aux": [
        {"title": "A1. Estrategia con señal", "practice": "decidir según el libro",
         "statement": "Define `ImbalanceBuyer`: compra 0.1 (market) solo cuando `book.imbalance(1) > 0.3`. Guarda `fills` del backtest.",
         "starter": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\nclass ImbalanceBuyer(Strategy):\n    def on_book_update(self, book):\n        pass\nfills = None\n",
         "validator": "assert fills is not None and fills >= 0\nprint('ok  fills=%d' % fills)",
         "solution": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\nclass ImbalanceBuyer(Strategy):\n    def on_book_update(self, book):\n        if book.imbalance(1) is not None and book.imbalance(1) > 0.3:\n            return [NewOrder(Order('BTCUSDT', Side.BUY, 0.1, order_type=OrderType.MARKET))]\n        return []\nfills = Backtest(Market.sample(), ImbalanceBuyer()).run().n_fills"},
    ],
})

# ---------------------------------------------------------------------------
# L9 — Primera estrategia + métricas
# ---------------------------------------------------------------------------
LESSONS.append({
    "n": 9, "slug": "09-first-strategy-metrics",
    "title": "Primera estrategia + métricas",
    "piece": "medir una estrategia contra un benchmark",
    "objective": "Cerrar el motor: una estrategia con señal real, y métricas honestas — PnL, posición y slippage contra el mid de llegada. Checkpoint integrador de todo L1-L9.",
    "frase": "Sin benchmark no hay estrategia: medir contra el mid de llegada separa la suerte del valor.",
    "concepts": [
        ("Una estrategia con criterio",
         "Compra cuando el libro empuja arriba (imbalance positivo), vende cuando empuja abajo. Simple, pero ya es una decisión basada en microestructura.",
         "if book.imbalance(3) > thr:  buy\nelif book.imbalance(3) < -thr: sell"),
        ("El benchmark: mid de llegada",
         "El precio justo de referencia es el mid cuando empezaste. Tu ejecución es buena si compraste por debajo (o vendiste por encima) de él.",
         "arrival_mid = primer book.mid\nslippage = eff_price - arrival_mid"),
        ("Leer el resultado con honestidad",
         "final_equity, posición final, número de fills. Un equity positivo con inventario enorme no es una buena estrategia: es riesgo escondido.",
         "result.final_equity, result.final_position,\nresult.n_fills"),
    ],
    "build": [
        {"title": "1. Estrategia de imbalance", "practice": "señal larga/corta",
         "statement": "Define `ImbalanceStrategy(thr)`: compra 0.05 si `imbalance(3) > thr`, vende 0.05 si `< -thr`. Market orders.",
         "given": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\n",
         "starter": "class ImbalanceStrategy(Strategy):\n    def __init__(self, thr=0.3):\n        self.thr = thr\n    def on_book_update(self, book):\n        pass\n",
         "validator": "r = Backtest(Market.sample(), ImbalanceStrategy(0.3)).run()\nassert r.n_steps == 500\nprint('ok ', r)",
         "solution": "class ImbalanceStrategy(Strategy):\n    def __init__(self, thr=0.3):\n        self.thr = thr\n    def on_book_update(self, book):\n        imb = book.imbalance(3)\n        if imb is None: return []\n        if imb > self.thr:\n            return [NewOrder(Order('BTCUSDT', Side.BUY, 0.05, order_type=OrderType.MARKET))]\n        if imb < -self.thr:\n            return [NewOrder(Order('BTCUSDT', Side.SELL, 0.05, order_type=OrderType.MARKET))]\n        return []"},
        {"title": "2. Mídela", "practice": "leer BacktestResult",
         "statement": "Corre la estrategia y guarda `equity`, `pos` y `fills` del resultado.",
         "given": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\nclass ImbalanceStrategy(Strategy):\n    def __init__(self, thr=0.3): self.thr=thr\n    def on_book_update(self, book):\n        imb = book.imbalance(3)\n        if imb is None: return []\n        if imb > self.thr: return [NewOrder(Order('BTCUSDT', Side.BUY, 0.05, order_type=OrderType.MARKET))]\n        if imb < -self.thr: return [NewOrder(Order('BTCUSDT', Side.SELL, 0.05, order_type=OrderType.MARKET))]\n        return []\n",
         "starter": "equity = None\npos = None\nfills = None\n",
         "validator": "assert isinstance(equity, float) and isinstance(fills, int)\nprint('ok  equity=%.2f pos=%.3f fills=%d' % (equity, pos, fills))",
         "solution": "r = Backtest(Market.sample(), ImbalanceStrategy(0.3)).run()\nequity = r.final_equity\npos = r.final_position\nfills = r.n_fills"},
        {"title": "3. Benchmark de llegada", "practice": "mid inicial",
         "statement": "Guarda `arrival_mid`, el mid del primer snapshot del mercado.",
         "starter": "from exchange import Market\narrival_mid = None\n",
         "validator": "assert 90000 < arrival_mid < 110000\nprint('ok  arrival_mid=%.2f' % arrival_mid)",
         "solution": "from exchange import Market\narrival_mid = Market.sample().step().mid"},
        {"title": "4. Riesgo escondido", "practice": "interpretar inventario",
         "statement": "Para `thr=0.1` y `thr=0.5`, guarda en `pos_small_thr` y `pos_big_thr` la posición final. Un umbral bajo opera más y arriesga más inventario.",
         "given": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\nclass ImbalanceStrategy(Strategy):\n    def __init__(self, thr=0.3): self.thr=thr\n    def on_book_update(self, book):\n        imb = book.imbalance(3)\n        if imb is None: return []\n        if imb > self.thr: return [NewOrder(Order('BTCUSDT', Side.BUY, 0.05, order_type=OrderType.MARKET))]\n        if imb < -self.thr: return [NewOrder(Order('BTCUSDT', Side.SELL, 0.05, order_type=OrderType.MARKET))]\n        return []\n",
         "starter": "pos_small_thr = None\npos_big_thr = None\n",
         "validator": "assert pos_small_thr is not None and pos_big_thr is not None\nprint('ok  thr0.1 pos=%.3f | thr0.5 pos=%.3f' % (pos_small_thr, pos_big_thr))",
         "solution": "pos_small_thr = Backtest(Market.sample(), ImbalanceStrategy(0.1)).run().final_position\npos_big_thr = Backtest(Market.sample(), ImbalanceStrategy(0.5)).run().final_position"},
    ],
    "aux": [
        {"title": "A1. Curva de equity", "practice": "serie temporal de PnL",
         "statement": "Corre la estrategia y guarda `curve = result.equity_curve`. Verifica que tiene 500 puntos. (En clase la dibujarías con matplotlib.)",
         "given": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\nclass S(Strategy):\n    def on_book_update(self, book):\n        return [NewOrder(Order('BTCUSDT', Side.BUY, 0.01, order_type=OrderType.MARKET))]\n",
         "starter": "curve = None\n",
         "validator": "assert len(curve) == 500\nprint('ok  puntos=%d' % len(curve))",
         "solution": "curve = Backtest(Market.sample(), S()).run().equity_curve"},
    ],
})
