"""Specs de las lecciones del motor y framework (L7-L11).

L7-L9 abren el motor en orden acumulativo: snapshot -> OrderBook ->
MatchingEngine -> Market. El paquete de referencia se usa solo como oráculo.
"""

LESSONS = []

SYNTHETIC_ROW_GIVEN = """import csv
import os
import exchange

_data_path = os.path.join(os.path.dirname(exchange.__file__), '_data', 'btc_lob_snapshots.csv')
with open(_data_path, newline='') as _f:
    row = {k: float(v) for k, v in next(csv.DictReader(_f)).items()}
"""

SYNTHETIC_BOOK_GIVEN = SYNTHETIC_ROW_GIVEN + """from exchange.book import OrderBook
book = OrderBook.from_snapshot('BTCUSDT', row, depth=10)
"""

# ---------------------------------------------------------------------------
# L7 — Del snapshot sintético al OrderBook
# ---------------------------------------------------------------------------
LESSONS.append({
    "n": 7, "slug": "07-microstructure-reading-book",
    "title": "Del snapshot sintético al OrderBook",
    "piece": "OrderBook: transformar datos externos en estado ordenado y consultable",
    "objective": "Convertir una fila del replay sintético en Level y OrderBook, y ampliar su API con depth, imbalance y microprice sin duplicar lógica.",
    "frase": "El CSV termina en la frontera del sistema: desde ahí, todo el motor habla con OrderBook.",
    "concepts": [
        ("De fila a objetos",
         "Cada pareja price/size se convierte en un Level. Los bids y asks se separan y OrderBook impone el orden una sola vez.",
         "row → Level(...) → bids / asks → OrderBook"),
        ("Una factory desde otra representación",
         "from_snapshot recorre la fila y fabrica la instancia. El resto del sistema deja de conocer nombres como bid_price_1.",
         "book = OrderBook.from_snapshot(symbol, row, depth=10)"),
        ("API por composición",
         "depth agrega tamaños; imbalance reutiliza depth; microprice reutiliza el mejor nivel. Cada método tiene una responsabilidad pequeña.",
         "book.depth(...)\nbook.imbalance(...)\nbook.microprice"),
    ],
    "build": [
        {"title": "B1 · Construye Level", "practice": "dataclass e independencia de objetos",
         "statement": "Instancia `bid` y `ask` como dos `Level` independientes. Cambiar el tamaño de uno no puede afectar al otro.",
         "given": "from exchange.book import Level\n",
         "starter": "bid = None\nask = None\n",
         "validator": "assert isinstance(bid, Level) and isinstance(ask, Level)\nassert bid is not ask\nold = ask.size; bid.size += 1\nassert ask.size == old, 'cada nivel mantiene su propio estado'\nassert bid.price > 0 and ask.price > bid.price\nprint('ok ->', bid, ask)",
         "solution": "bid = Level(100.0, 2.0)\nask = Level(101.0, 3.0)", "tier": "nucleo", "min": 3},
        {"title": "B2 · Ordena bids y asks", "practice": "sorted(key=...)",
         "statement": "Implementa `sort_sides`: bids de mayor a menor precio; asks de menor a mayor. No alteres las listas recibidas.",
         "given": "from exchange.book import Level\nbids = [Level(99, 1), Level(101, 2), Level(100, 3)]\nasks = [Level(103, 1), Level(101, 2), Level(102, 3)]\n",
         "starter": "def sort_sides(bids, asks):\n    pass\n",
         "validator": "b0, a0 = list(bids), list(asks)\nsb, sa = sort_sides(bids, asks)\nassert [x.price for x in sb] == [101, 100, 99]\nassert [x.price for x in sa] == [101, 102, 103]\nassert bids == b0 and asks == a0, 'devuelve listas ordenadas nuevas'\nprint('ok')",
         "solution": "def sort_sides(bids, asks):\n    return (sorted(bids, key=lambda lv: -lv.price),\n            sorted(asks, key=lambda lv: lv.price))", "tier": "nucleo", "min": 5},
        {"title": "B3 · Raw snapshot → niveles", "practice": "nombres dinámicos y bucle",
         "statement": "Convierte el snapshot de tres niveles en dos listas de `Level`. Ignora tamaños nulos o no positivos.",
         "given": "from exchange.book import Level\nrow = {\n 'bid_price_1': 100, 'bid_size_1': 2, 'ask_price_1': 101, 'ask_size_1': 1,\n 'bid_price_2': 99,  'bid_size_2': 0, 'ask_price_2': 102, 'ask_size_2': 3,\n 'bid_price_3': 98,  'bid_size_3': 4, 'ask_price_3': 103, 'ask_size_3': 2,\n}\n",
         "starter": "def levels_from_snapshot(row, depth):\n    pass\n",
         "validator": "bids, asks = levels_from_snapshot(row, 3)\nassert [(x.price, x.size) for x in bids] == [(100.0, 2.0), (98.0, 4.0)]\nassert [(x.price, x.size) for x in asks] == [(101.0, 1.0), (102.0, 3.0), (103.0, 2.0)]\nprint('ok')",
         "pista": "En cada `i`, construye los nombres `bid_price_{i}`, `bid_size_{i}`, etc. Añade Level solo cuando precio y tamaño existan y `size > 0`.",
         "solution": "def levels_from_snapshot(row, depth):\n    bids, asks = [], []\n    for i in range(1, depth + 1):\n        bp, bs = row.get(f'bid_price_{i}'), row.get(f'bid_size_{i}')\n        ap, az = row.get(f'ask_price_{i}'), row.get(f'ask_size_{i}')\n        if bp is not None and bs is not None and float(bs) > 0:\n            bids.append(Level(float(bp), float(bs)))\n        if ap is not None and az is not None and float(az) > 0:\n            asks.append(Level(float(ap), float(az)))\n    return bids, asks", "tier": "nucleo", "min": 7},
        {"title": "B4 · Implementa from_snapshot", "practice": "@classmethod como factory",
         "statement": "Completa `StudentOrderBook.from_snapshot`. Debe fabricar la instancia con `cls(...)`; `__init__` se ocupa de ordenar.",
         "given": "from exchange.book import Level\nrow = {'bid_price_1':99,'bid_size_1':1,'ask_price_1':102,'ask_size_1':2,\n       'bid_price_2':100,'bid_size_2':3,'ask_price_2':101,'ask_size_2':4}\n",
         "starter": "class StudentOrderBook:\n    def __init__(self, symbol, bids, asks):\n        self.symbol = symbol\n        self.bids = sorted(bids, key=lambda lv: -lv.price)\n        self.asks = sorted(asks, key=lambda lv: lv.price)\n\n    @classmethod\n    def from_snapshot(cls, symbol, row, depth=10):\n        pass\n",
         "validator": "book = StudentOrderBook.from_snapshot('BTCUSDT', row, 2)\nassert isinstance(book, StudentOrderBook) and book.symbol == 'BTCUSDT'\nassert [x.price for x in book.bids] == [100.0, 99.0]\nassert [x.price for x in book.asks] == [101.0, 102.0]\nprint('ok')",
         "solution": "class StudentOrderBook:\n    def __init__(self, symbol, bids, asks):\n        self.symbol = symbol\n        self.bids = sorted(bids, key=lambda lv: -lv.price)\n        self.asks = sorted(asks, key=lambda lv: lv.price)\n\n    @classmethod\n    def from_snapshot(cls, symbol, row, depth=10):\n        bids, asks = [], []\n        for i in range(1, depth + 1):\n            bp, bs = row.get(f'bid_price_{i}'), row.get(f'bid_size_{i}')\n            ap, az = row.get(f'ask_price_{i}'), row.get(f'ask_size_{i}')\n            if bp is not None and bs is not None and float(bs) > 0:\n                bids.append(Level(float(bp), float(bs)))\n            if ap is not None and az is not None and float(az) > 0:\n                asks.append(Level(float(ap), float(az)))\n        return cls(symbol, bids, asks)", "tier": "nucleo", "min": 8},
        {"title": "B5 · Implementa depth", "practice": "método de consulta",
         "statement": "Completa `depth(side, levels)`: suma el tamaño de los primeros niveles del lado solicitado.",
         "given": "from exchange.book import Level\nfrom exchange.orders import Side\n",
         "starter": "class StudentOrderBook:\n    def __init__(self):\n        self.bids = [Level(100,2), Level(99,3), Level(98,5)]\n        self.asks = [Level(101,7), Level(102,11)]\n    def depth(self, side, levels=10):\n        pass\nbook = StudentOrderBook()\n",
         "validator": "assert book.depth(Side.BUY, 2) == 5\nassert book.depth('sell', 1) == 7\nassert book.depth(Side.SELL, 99) == 18\nprint('ok')",
         "solution": "class StudentOrderBook:\n    def __init__(self):\n        self.bids = [Level(100,2), Level(99,3), Level(98,5)]\n        self.asks = [Level(101,7), Level(102,11)]\n    def depth(self, side, levels=10):\n        side = Side(side)\n        selected = self.bids if side is Side.BUY else self.asks\n        return sum(lv.size for lv in selected[:levels])\nbook = StudentOrderBook()", "tier": "bien", "min": 5},
        {"title": "B6 · Implementa imbalance componiendo métodos", "practice": "reutilizar depth",
         "statement": "Completa `imbalance`. No vuelvas a recorrer bids/asks: apóyate en `depth()` y trata el libro vacío.",
         "given": "from exchange.book import Level\nfrom exchange.orders import Side\n",
         "starter": "class StudentOrderBook:\n    def __init__(self, bids, asks): self.bids, self.asks = bids, asks\n    def depth(self, side, levels=10):\n        side = Side(side); xs = self.bids if side is Side.BUY else self.asks\n        return sum(lv.size for lv in xs[:levels])\n    def imbalance(self, levels=1):\n        pass\n",
         "validator": "book = StudentOrderBook([Level(100,3)], [Level(101,1)])\nassert abs(book.imbalance(1) - 0.5) < 1e-12\nassert StudentOrderBook([], []).imbalance(2) is None\nprint('ok')",
         "solution": "class StudentOrderBook:\n    def __init__(self, bids, asks): self.bids, self.asks = bids, asks\n    def depth(self, side, levels=10):\n        side = Side(side); xs = self.bids if side is Side.BUY else self.asks\n        return sum(lv.size for lv in xs[:levels])\n    def imbalance(self, levels=1):\n        bid = self.depth(Side.BUY, levels)\n        ask = self.depth(Side.SELL, levels)\n        total = bid + ask\n        return None if total == 0 else (bid - ask) / total", "tier": "bien", "min": 6},
        {"title": "B7 · Implementa microprice", "practice": "propiedad derivada del nivel 1",
         "statement": "Implementa `microprice`. Si falta cualquiera de los lados devuelve `None`; si existen, pondera cada precio por el tamaño contrario.",
         "given": "from exchange.book import Level\n",
         "starter": "class StudentOrderBook:\n    def __init__(self, bids, asks): self.bids, self.asks = bids, asks\n    @property\n    def best_bid(self): return self.bids[0].price if self.bids else None\n    @property\n    def best_ask(self): return self.asks[0].price if self.asks else None\n    @property\n    def microprice(self):\n        pass\n",
         "validator": "book = StudentOrderBook([Level(100,3)], [Level(102,1)])\nassert abs(book.microprice - 101.5) < 1e-12\nassert StudentOrderBook([], [Level(102,1)]).microprice is None\nprint('ok')",
         "solution": "class StudentOrderBook:\n    def __init__(self, bids, asks): self.bids, self.asks = bids, asks\n    @property\n    def best_bid(self): return self.bids[0].price if self.bids else None\n    @property\n    def best_ask(self): return self.asks[0].price if self.asks else None\n    @property\n    def microprice(self):\n        if not self.bids or not self.asks: return None\n        bs, az = self.bids[0].size, self.asks[0].size\n        return (self.best_bid * az + self.best_ask * bs) / (bs + az)", "tier": "bien", "min": 5},
        {"title": "B8 · Snapshot sintético contra la referencia", "practice": "integración y oráculo",
         "statement": "Completa la clase y úsala sobre el primer snapshot sintético. `student` debe coincidir con `OrderBook` en orden, depth, imbalance y microprice.",
         "given": SYNTHETIC_ROW_GIVEN + "from exchange.book import Level, OrderBook\nfrom exchange.orders import Side\n",
         "starter": "class StudentOrderBook:\n    # integra aquí from_snapshot, depth, imbalance y microprice\n    pass\nstudent = None\n",
         "validator": "reference = OrderBook.from_snapshot('BTCUSDT', row, 5)\nassert [x.price for x in student.bids] == [x.price for x in reference.bids]\nassert [x.price for x in student.asks] == [x.price for x in reference.asks]\nfor side in (Side.BUY, Side.SELL): assert abs(student.depth(side, 5)-reference.depth(side, 5)) < 1e-9\nassert abs(student.imbalance(5)-reference.imbalance(5)) < 1e-9\nassert abs(student.microprice-reference.microprice) < 1e-9\nprint('ok — tu objeto coincide con el oráculo')",
         "solution": "class StudentOrderBook:\n    def __init__(self, symbol, bids, asks):\n        self.symbol=symbol; self.bids=sorted(bids,key=lambda x:-x.price); self.asks=sorted(asks,key=lambda x:x.price)\n    @classmethod\n    def from_snapshot(cls, symbol, row, depth=10):\n        bids=[]; asks=[]\n        for i in range(1, depth+1):\n            bp,bs=row.get(f'bid_price_{i}'),row.get(f'bid_size_{i}')\n            ap,az=row.get(f'ask_price_{i}'),row.get(f'ask_size_{i}')\n            if bp is not None and bs is not None and float(bs)>0: bids.append(Level(float(bp),float(bs)))\n            if ap is not None and az is not None and float(az)>0: asks.append(Level(float(ap),float(az)))\n        return cls(symbol,bids,asks)\n    def depth(self, side, levels=10):\n        side=Side(side); xs=self.bids if side is Side.BUY else self.asks\n        return sum(x.size for x in xs[:levels])\n    def imbalance(self, levels=1):\n        b=self.depth(Side.BUY,levels); a=self.depth(Side.SELL,levels); t=b+a\n        return None if t==0 else (b-a)/t\n    @property\n    def microprice(self):\n        if not self.bids or not self.asks: return None\n        b,a=self.bids[0],self.asks[0]\n        return (b.price*a.size+a.price*b.size)/(b.size+a.size)\nstudent = StudentOrderBook.from_snapshot('BTCUSDT', row, 5)", "tier": "bien", "min": 10},
    ],
    "aux": [
        {"section": "Gimnasio · Calentamiento — repaso exprés de L6",
         "blurb": "Herencia y polimorfismo en dos reps antes de tocar un replay sintético."},
        {"title": "C1. Override exprés", "practice": "repaso: herencia",
         "statement": "Con la base dada, escribe `Alcista(Strategy)` cuyo `decide` devuelva siempre `'buy'`.",
         "given": "class Strategy:\n    def decide(self, imbalance):\n        return 'hold'\n",
         "starter": "a = None\n",
         "validator": "assert a.decide(-1) == 'buy'\nprint('ok')",
         "solution": "class Alcista(Strategy):\n    def decide(self, imbalance):\n        return 'buy'\n\na = Alcista()"},
        {"title": "C2. El bucle exprés", "practice": "repaso: polimorfismo",
         "statement": "Recorre `familia` llamando `decide(0.5)` y guarda las respuestas en `res`.",
         "given": "class Strategy:\n    def decide(self, imbalance):\n        return 'hold'\nclass Alcista(Strategy):\n    def decide(self, imbalance):\n        return 'buy'\nfamilia = [Strategy(), Alcista()]\n",
         "starter": "res = None\n",
         "validator": "assert res == ['hold', 'buy']\nprint('ok')",
         "solution": "res = [s.decide(0.5) for s in familia]"},

        {"section": "Gimnasio · Bloque 1 — Leer el replay sintético",
         "blurb": "Las lentes de la clase, aplicadas a los 500 snapshots sintéticos y reproducibles."},
        {"title": "A1. La primera foto", "practice": "snapshot sintético + métricas",
         "statement": "Transforma la primera fila sintética (ya cargada en `book`) y guarda `spread0` y `mid0`.",
         "given": SYNTHETIC_BOOK_GIVEN,
         "starter": "spread0 = None\nmid0 = None\n",
         "validator": "assert abs(spread0 - book.spread) < 1e-9\nassert abs(mid0 - book.mid) < 1e-9\nprint('ok ->', spread0, mid0)",
         "solution": "spread0 = book.spread\nmid0 = book.mid"},
        {"title": "A2. Dos imbalances, dos historias", "practice": "imbalance(levels)",
         "statement": "Sobre el primer snapshot, guarda `im1 = book.imbalance(1)` e `im5 = book.imbalance(5)`.",
         "given": SYNTHETIC_BOOK_GIVEN,
         "starter": "im1 = None\nim5 = None\n",
         "validator": "assert -1 <= im1 <= 1 and -1 <= im5 <= 1\nassert abs(im1 - book.imbalance(1)) < 1e-9\nprint(f'ok  im1={im1:.3f} im5={im5:.3f}')",
         "solution": "im1 = book.imbalance(1)\nim5 = book.imbalance(5)"},
        {"title": "A3. La inclinación del microprice", "practice": "microprice vs mid",
         "statement": "Guarda `tilt = book.microprice - book.mid`. Su signo dice hacia dónde se inclina el libro.",
         "given": SYNTHETIC_BOOK_GIVEN,
         "starter": "tilt = None\n",
         "validator": "assert abs(tilt) < book.spread, 'el microprice vive dentro del spread'\nassert abs(tilt - (book.microprice - book.mid)) < 1e-9\nprint(f'ok  tilt={tilt:.3f}')",
         "solution": "tilt = book.microprice - book.mid"},
        {"title": "A4. depth, comprobada a mano", "practice": "depth vs suma manual",
         "statement": "Calcula `d3 = book.depth(Side.BUY, 3)` y comprueba que coincide con sumar a mano los 3 primeros bids en `manual`.",
         "given": SYNTHETIC_BOOK_GIVEN + "from exchange.orders import Side\n",
         "starter": "d3 = None\nmanual = None\n",
         "validator": "assert abs(d3 - manual) < 1e-9, 'depth es exactamente esa suma'\nprint(f'ok  d3={d3:.3f}')",
         "solution": "d3 = book.depth(Side.BUY, 3)\nmanual = sum(lv.size for lv in book.bids[:3])"},
        {"title": "A5. El techo del día", "practice": "recorrer los 500",
         "statement": "Recorre TODO el mercado con `step()` y guarda `high` (el mid más alto del día).",
         "given": SYNTHETIC_ROW_GIVEN + "from exchange.book import OrderBook\nwith open(_data_path, newline='') as _f:\n    rows = [{k: float(v) for k, v in r.items()} for r in csv.DictReader(_f)]\n",
         "starter": "high = None\n",
         "validator": "mids = [OrderBook.from_snapshot('BTCUSDT', r).mid for r in rows]\nassert abs(high - max(mids)) < 1e-9\nprint(f'ok  high={high}')",
         "solution": "high = None\nfor r in rows:\n    b = OrderBook.from_snapshot('BTCUSDT', r)\n    if high is None or b.mid > high:\n        high = b.mid"},

        {"section": "Para terminar — profundización",
         "blurb": "El spread medio de la sesión y la pregunta de si el imbalance predice."},
        {"title": "A6. Spread medio de la sesión", "practice": "recorrer el mercado",
         "statement": "Recorre todos los snapshots y guarda `avg_spread`, la media del spread.",
         "given": SYNTHETIC_ROW_GIVEN + "from exchange.book import OrderBook\nwith open(_data_path, newline='') as _f:\n    rows = [{k: float(v) for k, v in r.items()} for r in csv.DictReader(_f)]\n",
         "starter": "avg_spread = None\n",
         "validator": "assert avg_spread > 0\nprint('ok  avg_spread=%.2f' % avg_spread)",
         "solution": "spreads = [OrderBook.from_snapshot('BTCUSDT', r).spread for r in rows]\navg_spread = sum(spreads) / len(spreads)"},
        {"title": "A7. ¿Predice el imbalance?", "practice": "señal vs siguiente mid",
         "statement": "Cuenta cuántas veces, cuando `imbalance(1) > 0`, el mid del siguiente snapshot sube. Guarda el conteo en `up_after_positive`.",
         "given": SYNTHETIC_ROW_GIVEN + "from exchange.book import OrderBook\nwith open(_data_path, newline='') as _f:\n    rows = [{k: float(v) for k, v in r.items()} for r in csv.DictReader(_f)]\nbooks = [OrderBook.from_snapshot('BTCUSDT', r) for r in rows]\n",
         "starter": "up_after_positive = 0\n",
         "validator": "assert up_after_positive != 0, 'sigue en 0: recorre el dia comparando cada mid con el anterior'\nassert up_after_positive == 117, f'obtuviste {up_after_positive}; cuenta solo cuando imbalance(1) > 0 Y el mid del snapshot siguiente sube'\nprint('ok  veces que sube tras imbalance+:', up_after_positive)",
         "solution": "up_after_positive = 0\nfor prev, cur in zip(books, books[1:]):\n    if prev.imbalance(1) is not None and prev.imbalance(1) > 0 and cur.mid > prev.mid:\n        up_after_positive += 1"},
    ],
})

# ---------------------------------------------------------------------------
# L8 — Construir MatchingEngine
# ---------------------------------------------------------------------------
LESSONS.append({
    "n": 8, "slug": "08-order-types-matching",
    "title": "Construir MatchingEngine",
    "piece": "MatchingEngine: planificar cruces, validar y mutar el libro",
    "objective": "Programar el algoritmo que convierte Order + OrderBook en fills y estado nuevo, reutilizando un único proceso para MARKET, LIMIT, IOC y FOK.",
    "frase": "Cuando una operación puede abortarse, primero planifica y valida; después muta el estado.",
    "concepts": [
        ("Seleccionar y planificar",
         "BUY consume asks y SELL consume bids. remaining y take permiten recorrer niveles sin mutar todavía.",
         "take = min(remaining, level.size)\nplanned.append((level.price, take))"),
        ("Validar y hacer commit",
         "FOK obliga a separar PLAN de COMMIT: si no cabe entera, el libro debe quedar idéntico.",
         "if FOK and filled < size: return []\n# solo después: book.reduce(...)"),
        ("Un algoritmo, cuatro políticas",
         "MARKET, LIMIT, IOC y FOK comparten selección, planificación y commit. Solo cambian el cruce permitido y el tratamiento del remanente.",
         "LIMIT → add_limit(rest)\nMARKET / IOC → cancelar rest\nFOK → todo o nada"),
    ],
    "build": [
        {"title": "B1 · ¿Qué lado consumo?", "practice": "selección BUY/SELL",
         "statement": "Implementa `opposite_levels`: BUY devuelve asks; SELL devuelve bids. Devuelve la lista real del book, no una copia.",
         "given": "from exchange.book import OrderBook, Level\nfrom exchange.orders import Order, OrderType, Side\nbook = OrderBook('BTC', [Level(100,2),Level(99,3)], [Level(101,1),Level(102,4)])\n",
         "starter": "def opposite_levels(order, book):\n    pass\n",
         "validator": "buy=Order('BTC',Side.BUY,1,order_type=OrderType.MARKET)\nsell=Order('BTC',Side.SELL,1,order_type=OrderType.MARKET)\nassert opposite_levels(buy,book) is book.asks\nassert opposite_levels(sell,book) is book.bids\nprint('ok')",
         "solution": "def opposite_levels(order, book):\n    return book.asks if order.side is Side.BUY else book.bids", "tier": "nucleo", "min": 4},
        {"title": "B2 · remaining + take", "practice": "planificar sin mutar",
         "statement": "Implementa `plan_market`. Devuelve `(planned, remaining)` y no cambies el libro. Cada plan es `(price, take)`.",
         "given": "import math\nfrom exchange.book import OrderBook, Level\nfrom exchange.orders import Order, OrderType\nbook=OrderBook('BTC',[Level(100,2)],[Level(101,.8),Level(102,1),Level(103,2)])\norder=Order('BTC','buy',2.4,order_type=OrderType.MARKET)\n",
         "starter": "def plan_market(order, book):\n    pass\n",
         "validator": "before=[(x.price,x.size) for x in book.asks]\nplanned,remaining=plan_market(order,book)\nassert [(p,round(s,9)) for p,s in planned]==[(101,.8),(102,1),(103,.6)]\nassert remaining==0.0\nassert [(x.price,x.size) for x in book.asks]==before, 'PLAN no muta'\ntiny=math.ulp(0.0)\ntiny_book=OrderBook('BTC',[],[Level(101,tiny)])\ntiny_order=Order('BTC','buy',tiny,order_type=OrderType.MARKET)\ntiny_plan,tiny_remaining=plan_market(tiny_order,tiny_book)\nassert tiny_plan==[(101.0,tiny)] and tiny_remaining==0.0, 'un size subnormal positivo no es cero'\nprint('ok')",
         "solution": "def plan_market(order, book):\n    remaining=order.size; planned=[]\n    opposite=book.asks if order.side.value=='buy' else book.bids\n    for level in opposite:\n        if remaining==0.0: break\n        take=min(remaining,level.size); planned.append((level.price,take))\n        filled=math.fsum(size for _,size in planned)\n        remaining=0.0 if filled>=order.size else order.size-filled\n    return planned,remaining", "tier": "nucleo", "min": 6},
        {"title": "B3 · Primera MARKET completa", "practice": "loop → reduce → Fill",
         "statement": "Implementa `StudentMatchingEngine.process` para MARKET. Debe barrer varios niveles, crear fills y mutar correctamente el book. Para `book.reduce`, calcula el lado consumido con la misma regla explícita de B1: BUY consume `Side.SELL`; SELL consume `Side.BUY`.",
         "given": "import math\nfrom exchange.book import OrderBook, Level\nfrom exchange.orders import Order, OrderType, Side\nfrom exchange.trades import Fill\n",
         "starter": "class StudentMatchingEngine:\n    def process(self, order, book, timestamp=None):\n        pass\n",
         "validator": "book=OrderBook('BTC',[Level(100,2)],[Level(101,.8),Level(102,1),Level(103,2)])\norder=Order('BTC','buy',2.4,order_type=OrderType.MARKET)\nfills=StudentMatchingEngine().process(order,book,7)\nassert [(f.price,round(f.size,9)) for f in fills]==[(101,.8),(102,1),(103,.6)]\nassert [(x.price,round(x.size,9)) for x in book.asks]==[(103,1.4)]\nassert all(f.timestamp==7 and f.side is Side.BUY for f in fills)\nprint('ok')",
         "solution": "class StudentMatchingEngine:\n    def process(self, order, book, timestamp=None):\n        opposite=book.asks if order.side is Side.BUY else book.bids\n        consumed_side=Side.SELL if order.side is Side.BUY else Side.BUY\n        remaining=order.size; planned=[]\n        for level in opposite:\n            if remaining==0.0: break\n            take=min(remaining,level.size); planned.append((level.price,take))\n            filled=math.fsum(size for _,size in planned)\n            remaining=0.0 if filled>=order.size else order.size-filled\n        fills=[]\n        for price,take in planned:\n            book.reduce(consumed_side,price,take)\n            fills.append(Fill(order.id,order.symbol,order.side,price,take,timestamp))\n        return fills", "tier": "nucleo", "min": 9},
        {"title": "B4 · Diseña _crosses()", "practice": "LIMIT simétrica BUY/SELL",
         "statement": "Implementa `_crosses(order, level_price)`. BUY cruza si el nivel está a su límite o mejor; SELL, simétricamente.",
         "given": "from exchange.orders import Order, OrderType\n",
         "starter": "def crosses(order, level_price):\n    pass\n",
         "validator": "buy=Order('BTC','buy',1,price=101,order_type=OrderType.LIMIT)\nsell=Order('BTC','sell',1,price=99,order_type=OrderType.LIMIT)\nassert crosses(buy,100) and crosses(buy,101) and not crosses(buy,102)\nassert crosses(sell,100) and crosses(sell,99) and not crosses(sell,98)\nprint('ok')",
         "solution": "def crosses(order, level_price):\n    if order.side.value=='buy': return order.price>=level_price\n    return order.price<=level_price", "tier": "nucleo", "min": 5},
        {"title": "B5 · LIMIT marketable", "practice": "detener el plan en el límite",
         "statement": "Añade `_crosses()` al plan. La LIMIT puede barrer precios válidos, pero debe parar en el primer nivel que empeora su límite. Desde esta consolidación puedes usar `order.side.opposite`: devuelve `Side.SELL` para BUY y `Side.BUY` para SELL.",
         "given": "import math\nfrom exchange.book import OrderBook,Level\nfrom exchange.orders import Order,OrderType,Side\nfrom exchange.trades import Fill\n",
         "starter": "class StudentMatchingEngine:\n    @staticmethod\n    def _crosses(order, price):\n        pass\n    def process(self, order, book, timestamp=None):\n        pass\n",
         "validator": "b=OrderBook('BTC',[Level(99,2)],[Level(101,1),Level(102,1),Level(103,1)])\no=Order('BTC','buy',3,price=102,order_type=OrderType.LIMIT)\nf=StudentMatchingEngine().process(o,b)\nassert [(x.price,x.size) for x in f]==[(101,1),(102,1)]\nassert [(x.price,x.size) for x in b.asks]==[(103,1)]\nprint('ok')",
         "solution": "class StudentMatchingEngine:\n    @staticmethod\n    def _crosses(order, price):\n        return order.price>=price if order.side is Side.BUY else order.price<=price\n    def process(self, order, book, timestamp=None):\n        opposite=book.asks if order.side is Side.BUY else book.bids\n        remaining=order.size; planned=[]\n        for level in opposite:\n            if remaining==0.0 or not self._crosses(order,level.price): break\n            take=min(remaining,level.size); planned.append((level.price,take))\n            filled=math.fsum(size for _,size in planned)\n            remaining=0.0 if filled>=order.size else order.size-filled\n        fills=[]\n        for price,take in planned:\n            book.reduce(order.side.opposite,price,take)\n            fills.append(Fill(order.id,order.symbol,order.side,price,take,timestamp))\n        return fills", "tier": "bien", "min": 8},
        {"title": "B6 · El remanente LIMIT descansa", "practice": "book.add_limit",
         "statement": "Extiende LIMIT: tras el commit, cualquier `remaining` debe descansar al precio límite en el lado de la orden.",
         "given": "import math\nfrom exchange.book import OrderBook,Level\nfrom exchange.orders import Order,OrderType,Side\nfrom exchange.trades import Fill\n",
         "starter": "class StudentMatchingEngine:\n    # integra plan, commit y tratamiento del remanente LIMIT\n    pass\n",
         "validator": "b=OrderBook('BTC',[Level(99,2)],[Level(101,1),Level(102,1)])\no=Order('BTC','buy',3,price=101,order_type=OrderType.LIMIT)\nf=StudentMatchingEngine().process(o,b)\nassert sum(x.size for x in f)==1\nassert any(x.price==101 and abs(x.size-2)<1e-12 for x in b.bids), 'el remanente descansa'\nprint('ok')",
         "solution": "class StudentMatchingEngine:\n    @staticmethod\n    def _crosses(o,p): return o.price>=p if o.side is Side.BUY else o.price<=p\n    def process(self,o,b,timestamp=None):\n        xs=b.asks if o.side is Side.BUY else b.bids; r=o.size; plan=[]\n        for lv in xs:\n            if r==0.0 or not self._crosses(o,lv.price): break\n            take=min(r,lv.size); plan.append((lv.price,take))\n            filled=math.fsum(size for _,size in plan)\n            r=0.0 if filled>=o.size else o.size-filled\n        fills=[]\n        for p,s in plan:\n            b.reduce(o.side.opposite,p,s); fills.append(Fill(o.id,o.symbol,o.side,p,s,timestamp))\n        if r>0.0:\n            filled=math.fsum(fill.size for fill in fills)\n            if filled>0.0 and r==o.size: raise OverflowError('remainder is not representable')\n            b.add_limit(o.side,o.price,r)\n        return fills", "tier": "bien", "min": 7},
        {"title": "B7 · Diseña IOC sin duplicar el engine", "practice": "misma ejecución, otra política de remanente",
         "statement": "Soporta LIMIT e IOC con un solo proceso. Ambas cruzan igual; solo LIMIT puede ejecutar `add_limit` para el remanente.",
         "given": "import math\nfrom exchange.book import OrderBook,Level\nfrom exchange.orders import Order,OrderType,Side\nfrom exchange.trades import Fill\n",
         "starter": "class StudentMatchingEngine:\n    pass\n",
         "validator": "def run(kind):\n b=OrderBook('BTC',[Level(99,2)],[Level(101,1)]); o=Order('BTC','buy',3,price=101,order_type=kind); f=StudentMatchingEngine().process(o,b); return f,b\nfl,bl=run(OrderType.LIMIT); fi,bi=run(OrderType.IOC)\nassert [(x.price,x.size) for x in fl]==[(x.price,x.size) for x in fi]==[(101,1)]\nassert any(x.price==101 and x.size==2 for x in bl.bids)\nassert all(x.price!=101 for x in bi.bids), 'IOC cancela el remanente'\nprint('ok')",
         "solution": "class StudentMatchingEngine:\n    @staticmethod\n    def _crosses(o,p): return o.price>=p if o.side is Side.BUY else o.price<=p\n    def process(self,o,b,timestamp=None):\n        xs=b.asks if o.side is Side.BUY else b.bids; r=o.size; plan=[]\n        for lv in xs:\n            if r==0.0 or not self._crosses(o,lv.price): break\n            take=min(r,lv.size); plan.append((lv.price,take))\n            filled=math.fsum(size for _,size in plan)\n            r=0.0 if filled>=o.size else o.size-filled\n        fills=[]\n        for p,s in plan:\n            b.reduce(o.side.opposite,p,s); fills.append(Fill(o.id,o.symbol,o.side,p,s,timestamp))\n        if r>0.0 and o.order_type is OrderType.LIMIT:\n            filled=math.fsum(fill.size for fill in fills)\n            if filled>0.0 and r==o.size: raise OverflowError('remainder is not representable')\n            b.add_limit(o.side,o.price,r)\n        return fills", "tier": "bien", "min": 7},
        {"title": "B8 · Depura FOK: plan → validate → commit", "practice": "atomicidad del estado",
         "statement": "La implementación inicial muta mientras recorre. Repárala: una FOK imposible devuelve `[]` y deja el book nivel por nivel idéntico.",
         "given": "import math\nfrom exchange.book import OrderBook,Level\nfrom exchange.orders import Order,OrderType,Side\nfrom exchange.trades import Fill\n",
         "starter": "class StudentMatchingEngine:\n    def process(self,o,b,timestamp=None):\n        # BUG: reduce antes de saber si habrá liquidez suficiente\n        xs=b.asks if o.side is Side.BUY else b.bids; r=o.size; fills=[]; consumed=[]\n        for lv in list(xs):\n            if r==0.0: break\n            take=min(r,lv.size); b.reduce(o.side.opposite,lv.price,take)\n            fills.append(Fill(o.id,o.symbol,o.side,lv.price,take,timestamp)); consumed.append(take)\n            filled=math.fsum(consumed); r=0.0 if filled>=o.size else o.size-filled\n        return [] if r>0.0 else fills\n",
         "validator": "b=OrderBook('BTC',[Level(99,2)],[Level(101,2),Level(102,1)])\nbefore=([(x.price,x.size) for x in b.bids],[(x.price,x.size) for x in b.asks])\no=Order('BTC','buy',10,price=102,order_type=OrderType.FOK)\nassert StudentMatchingEngine().process(o,b)==[]\nafter=([(x.price,x.size) for x in b.bids],[(x.price,x.size) for x in b.asks])\nassert after==before, 'FOK fallida debe ser atómica'\nprint('ok — no hubo mutación parcial')",
         "pista": "Primero guarda `(price, take)` en una lista y calcula cuánto podrías llenar. Si no alcanza, retorna antes del primer `reduce`.",
         "solution": "class StudentMatchingEngine:\n    def process(self,o,b,timestamp=None):\n        xs=b.asks if o.side is Side.BUY else b.bids; r=o.size; plan=[]\n        for lv in xs:\n            if r==0.0: break\n            if o.price is not None and not (o.price>=lv.price if o.side is Side.BUY else o.price<=lv.price): break\n            take=min(r,lv.size); plan.append((lv.price,take))\n            filled=math.fsum(size for _,size in plan)\n            r=0.0 if filled>=o.size else o.size-filled\n        if r>0.0: return []\n        fills=[]\n        for p,s in plan:\n            b.reduce(o.side.opposite,p,s); fills.append(Fill(o.id,o.symbol,o.side,p,s,timestamp))\n        return fills", "tier": "bien", "min": 9},
        {"title": "B9 · Refactor: un único process()", "practice": "MARKET/LIMIT/IOC/FOK reutilizando fases",
         "statement": "Integra los cuatro tipos en `StudentMatchingEngine`. No escribas cuatro loops: selección, plan y commit deben ser comunes.",
         "given": "import math\nfrom exchange.book import OrderBook,Level\nfrom exchange.orders import Order,OrderType,Side\nfrom exchange.trades import Fill\n",
         "starter": "class StudentMatchingEngine:\n    pass\n",
         "validator": "def snap(b): return ([(x.price,round(x.size,9)) for x in b.bids],[(x.price,round(x.size,9)) for x in b.asks])\ndef fresh(): return OrderBook('BTC',[Level(100,1),Level(99,2)],[Level(101,1),Level(102,2)])\ne=StudentMatchingEngine()\nb=fresh(); assert sum(x.size for x in e.process(Order('BTC','buy',2,order_type=OrderType.MARKET),b))==2\nb=fresh(); e.process(Order('BTC','buy',2,price=101,order_type=OrderType.LIMIT),b); assert (101,1) in snap(b)[0]\nb=fresh(); e.process(Order('BTC','buy',2,price=101,order_type=OrderType.IOC),b); assert (101,1) not in snap(b)[0]\nb=fresh(); before=snap(b); assert e.process(Order('BTC','buy',9,price=102,order_type=OrderType.FOK),b)==[] and snap(b)==before\nb=fresh(); f=e.process(Order('BTC','sell',1.5,order_type=OrderType.MARKET),b); assert [x.price for x in f]==[100,99]\ntiny=math.ulp(0.0); b=OrderBook('BTC',[],[Level(101,tiny)])\nf=e.process(Order('BTC','buy',tiny,order_type=OrderType.MARKET),b)\nassert len(f)==1 and f[0].size==tiny and b.asks==[], 'un size subnormal positivo se ejecuta'\nb=OrderBook('BTC',[],[Level(101,1)])\ntry: e.process(Order('BTC','buy',1e16,price=101,order_type=OrderType.LIMIT),b)\nexcept OverflowError: pass\nelse: raise AssertionError('un remanente no representable no puede descansar sobredimensionado')\nassert b.bids==[], 'la guardia no publica un remanente sobredimensionado'\nprint('ok — cuatro políticas, un algoritmo')",
         "solution": "class StudentMatchingEngine:\n    @staticmethod\n    def _crosses(o,p): return o.price>=p if o.side is Side.BUY else o.price<=p\n    def process(self,o,b,timestamp=None):\n        xs=b.asks if o.side is Side.BUY else b.bids; r=o.size; plan=[]\n        for lv in xs:\n            if r==0.0: break\n            if o.order_type is not OrderType.MARKET and not self._crosses(o,lv.price): break\n            take=min(r,lv.size); plan.append((lv.price,take))\n            filled=math.fsum(size for _,size in plan)\n            r=0.0 if filled>=o.size else o.size-filled\n        if o.order_type is OrderType.FOK and r>0.0: return []\n        fills=[]\n        for p,s in plan:\n            b.reduce(o.side.opposite,p,s); fills.append(Fill(o.id,o.symbol,o.side,p,s,timestamp))\n        if r>0.0 and o.order_type is OrderType.LIMIT:\n            filled=math.fsum(fill.size for fill in fills)\n            if filled>0.0 and r==o.size: raise OverflowError('remainder is not representable')\n            b.add_limit(o.side,o.price,r)\n        return fills", "tier": "bien", "min": 10},
        {"title": "B10 · Prueba contra la referencia", "practice": "differential testing",
         "statement": "Ejecuta escenarios simétricos contra tu engine y el de referencia. Compara fills por comportamiento y el estado final completo.",
         "given": "import math\nfrom exchange.book import OrderBook,Level\nfrom exchange.orders import Order,OrderType,Side\nfrom exchange.trades import Fill\nfrom exchange.matching import MatchingEngine\n",
         "starter": "# reutiliza aquí tu StudentMatchingEngine de B9\nmatched = None\n",
         "validator": "def fresh(): return OrderBook('BTC',[Level(100,1),Level(99,2)],[Level(101,1),Level(102,2)])\ndef state(b): return ([(x.price,round(x.size,9)) for x in b.bids],[(x.price,round(x.size,9)) for x in b.asks])\ndef sig(fs): return [(f.side.value,f.price,round(f.size,9)) for f in fs]\nassert matched is True\nfor side,kind,size,px in [('buy',OrderType.MARKET,2,None),('sell',OrderType.MARKET,1.5,None),('buy',OrderType.LIMIT,2,101),('buy',OrderType.IOC,2,101),('buy',OrderType.FOK,9,102)]:\n a,c=fresh(),fresh(); oa=Order('BTC',side,size,price=px,order_type=kind); oc=Order('BTC',side,size,price=px,order_type=kind)\n fa=StudentMatchingEngine().process(oa,a); fc=MatchingEngine().process(oc,c)\n assert sig(fa)==sig(fc) and state(a)==state(c)\ntiny=math.ulp(0.0); a=OrderBook('BTC',[],[Level(101,tiny)]); c=OrderBook('BTC',[],[Level(101,tiny)])\nfa=StudentMatchingEngine().process(Order('BTC','buy',tiny,order_type=OrderType.MARKET),a)\nfc=MatchingEngine().process(Order('BTC','buy',tiny,order_type=OrderType.MARKET),c)\nassert len(fa)==len(fc)==1 and fa[0].size==fc[0].size==tiny and a.asks==c.asks==[]\nprint('ok — coincide con la referencia')",
         "solution": "class StudentMatchingEngine:\n    @staticmethod\n    def _crosses(o,p): return o.price>=p if o.side is Side.BUY else o.price<=p\n    def process(self,o,b,timestamp=None):\n        xs=b.asks if o.side is Side.BUY else b.bids; r=o.size; plan=[]\n        for lv in xs:\n            if r==0.0: break\n            if o.order_type is not OrderType.MARKET and not self._crosses(o,lv.price): break\n            take=min(r,lv.size); plan.append((lv.price,take))\n            filled=math.fsum(size for _,size in plan)\n            r=0.0 if filled>=o.size else o.size-filled\n        if o.order_type is OrderType.FOK and r>0.0: return []\n        fills=[]\n        for p,s in plan:\n            b.reduce(o.side.opposite,p,s); fills.append(Fill(o.id,o.symbol,o.side,p,s,timestamp))\n        if r>0.0 and o.order_type is OrderType.LIMIT:\n            filled=math.fsum(fill.size for fill in fills)\n            if filled>0.0 and r==o.size: raise OverflowError('remainder is not representable')\n            b.add_limit(o.side,o.price,r)\n        return fills\nmatched=True", "tier": "bien", "min": 8},
    ],
    "aux": [
        {"section": "Gimnasio · Calentamiento — repaso exprés de L7",
         "blurb": "Dos lecturas rápidas del OrderBook canónico del replay sintético antes de dispararle."},
        {"title": "C1. Foto exprés", "practice": "repaso: mid y spread",
         "statement": "Del primer snapshot, guarda `mid0` y `spread0`.",
         "given": SYNTHETIC_BOOK_GIVEN,
         "starter": "mid0 = None\nspread0 = None\n",
         "validator": "assert abs(mid0 - book.mid) < 1e-9 and abs(spread0 - book.spread) < 1e-9\nprint('ok')",
         "solution": "mid0 = book.mid\nspread0 = book.spread"},
        {"title": "C2. Liquidez exprés", "practice": "repaso: depth",
         "statement": "¿Cuánto se puede comprar contra los 3 primeros asks? Guarda `d3`.",
         "given": SYNTHETIC_BOOK_GIVEN + "from exchange.orders import Side\n",
         "starter": "d3 = None\n",
         "validator": "assert abs(d3 - book.depth(Side.SELL, 3)) < 1e-9\nprint(f'ok  d3={d3:.3f}')",
         "solution": "d3 = book.depth(Side.SELL, 3)"},

        {"section": "Gimnasio · Bloque 1 — Fills, barridos y el peaje",
         "blurb": "La aritmética del matching, contra el motor canónico."},
        {"title": "A1. La orden pequeña no barre", "practice": "market vs nivel 1",
         "statement": "Envía una market buy de la MITAD del mejor ask. Comprueba que sale UN fill al precio `best_ask`. Guarda `fills`.",
         "given": SYNTHETIC_BOOK_GIVEN + "from exchange.matching import MatchingEngine\nfrom exchange.orders import Order, OrderType\nsize = book.asks[0].size / 2\nbest_ask_antes = book.asks[0].price  # process() consume el libro: captura antes\n",
         "starter": "fills = None\n",
         "validator": "assert len(fills) == 1, 'cabe entera en el nivel 1: un solo fill'\nassert abs(fills[0].price - best_ask_antes) < 1e-9, 'se llena AL precio del mejor ask'\nassert abs(fills[0].size - size) < 1e-9\nprint('ok ->', fills[0])",
         "solution": "engine = MatchingEngine()\nfills = engine.process(Order('BTCUSDT', 'buy', size, order_type=OrderType.MARKET), book)"},
        {"title": "A2. Precio efectivo", "practice": "media ponderada de fills",
         "statement": "Con los fills dados (tuplas precio-tamaño), calcula `eff`, el precio medio ponderado.",
         "given": "fills = [(100010.0, 0.8), (100025.0, 0.5), (100040.0, 0.7)]\n",
         "starter": "eff = None\n",
         "validator": "assert abs(eff - 100024.25) < 1e-2, 'suma p*s / suma s'\nprint(f'ok  eff={eff:.2f}')",
         "solution": "eff = sum(p * s for p, s in fills) / sum(s for p, s in fills)"},
        {"title": "A3. El slippage con signo", "practice": "eff vs mid",
         "statement": "Compraste con `eff = 100024.25` y el mid era `100000.0`. Guarda `slip` (positivo = pagaste de más) y `slip_bps`.",
         "given": "eff = 100024.25\nmid = 100000.0\n",
         "starter": "slip = None\nslip_bps = None\n",
         "validator": "assert abs(slip - 24.25) < 1e-9\nassert abs(slip_bps - 2.425) < 1e-3\nprint('ok')",
         "solution": "slip = eff - mid\nslip_bps = slip / mid * 10000"},
        {"title": "A4. El barrido, medido", "practice": "motor canónico contra replay sintético",
         "statement": "Dispara una market buy que se coma los 2 primeros niveles ask enteros. Comprueba que salen 2 fills y guarda `eff`.",
         "given": SYNTHETIC_BOOK_GIVEN + "from exchange.matching import MatchingEngine\nfrom exchange.orders import Order, OrderType\nsize = book.asks[0].size + book.asks[1].size\nmid_antes = book.mid  # process() consume el libro: captura antes\n",
         "starter": "eff = None\n",
         "validator": "assert eff is not None, 'calcula el precio efectivo de los fills'\nassert eff > mid_antes, 'compras barriendo: el efectivo queda POR ENCIMA del mid'\nprint(f'ok  eff={eff:.2f}  (mid era {mid_antes:.2f})')",
         "solution": "engine = MatchingEngine()\nfills = engine.process(Order('BTCUSDT', 'buy', size, order_type=OrderType.MARKET), book)\neff = sum(f.price * f.size for f in fills) / sum(f.size for f in fills)"},
        {"title": "A5. FOK: todo o nada", "practice": "el contrato FOK",
         "statement": "Envía una FOK de compra MÁS GRANDE que toda la liquidez ask visible, a precio del último nivel. Comprueba que devuelve 0 fills y que el libro queda intacto.",
         "given": SYNTHETIC_BOOK_GIVEN + "from exchange.matching import MatchingEngine\nfrom exchange.orders import Order, OrderType\ntotal_ask = sum(lv.size for lv in book.asks)\nask_antes = book.best_ask\n",
         "starter": "fills = None\n",
         "validator": "assert fills == []\nassert abs(book.best_ask - ask_antes) < 1e-9, 'FOK imposible no toca el libro'\nprint('ok — todo o nada')",
         "solution": "engine = MatchingEngine()\nfills = engine.process(Order('BTCUSDT', 'buy', total_ask * 2, price=book.asks[-1].price, order_type=OrderType.FOK), book)"},

        {"section": "Para terminar — profundización",
         "blurb": "El slippage como función del tamaño, sistematizado."},
        {"title": "A6. Slippage por tamaño", "practice": "coste vs tamaño",
         "statement": "Para tamaños 0.1, 1.0 y 5.0, calcula el precio efectivo de una market buy. Guarda la lista `eff_prices`. Debe ser creciente (más tamaño, peor precio).",
         "given": SYNTHETIC_ROW_GIVEN + "from exchange import OrderBook, MatchingEngine, Order, Side, OrderType\n",
         "starter": "eff_prices = []\n",
         "validator": "assert len(eff_prices) == 3, '⏸ llena eff_prices con los 3 precios efectivos antes de validar'\nassert eff_prices[0] <= eff_prices[1] <= eff_prices[2], 'más tamaño = peor precio'\nprint('ok', [round(p,1) for p in eff_prices])",
         "solution": "eng = MatchingEngine()\neff_prices = []\nfor size in (0.1, 1.0, 5.0):\n    book = OrderBook.from_snapshot('BTCUSDT', row, depth=10)\n    fills = eng.process(Order('BTCUSDT', Side.BUY, size, order_type=OrderType.MARKET), book)\n    eff_prices.append(sum(f.price*f.size for f in fills)/sum(f.size for f in fills))"},
    ],
})

# ---------------------------------------------------------------------------
# L9 — Construir Market
# ---------------------------------------------------------------------------
LESSONS.append({
    "n": 9, "slug": "09-market-simulation-loop",
    "title": "Construir Market y su API",
    "piece": "Market: componer snapshots, OrderBook, MatchingEngine y tiempo",
    "objective": "Construir el objeto que mantiene el índice temporal, reconstruye el OrderBook actual y delega cada orden al MatchingEngine.",
    "frase": "Market añade tiempo y composición: step cambia el estado; submit delega la dinámica; reset vuelve al origen.",
    "concepts": [
        ("El estado de Market",
         "Market contiene snapshots, profundidad, índice, book actual y un MatchingEngine. Antes del primer tick: _i=-1 y book=None.",
         "Market(_snapshots, _depth, _engine, _i, book)"),
        ("step() cambia el tiempo y el estado",
         "Avanza el cursor y reconstruye book con OrderBook.from_snapshot. Al agotarse los datos deja book=None.",
         "self._i += 1\nself.book = OrderBook.from_snapshot(...)"),
        ("submit() delega; reset() restaura",
         "Market no reprograma matching: verifica que hay book y delega. reset restaura exactamente el estado previo al primer tick.",
         "return self._engine.process(order, self.book, self.timestamp)"),
    ],
    "build": [
        {"title": "B1 · Estado inicial", "practice": "__init__ y composición",
         "statement": "Implementa `__init__`: conserva symbol/snapshots/depth, crea el engine y deja `_i=-1`, `book=None`.",
         "given": "from exchange.matching import MatchingEngine\n",
         "starter": "class StudentMarket:\n    def __init__(self, symbol, snapshots, depth=10):\n        pass\nmarket = StudentMarket('BTC', [{'x':1}], 5)\n",
         "validator": "assert market.symbol=='BTC' and market._snapshots==[{'x':1}] and market._depth==5\nassert market._i==-1 and market.book is None\nassert isinstance(market._engine,MatchingEngine)\nprint('ok')",
         "solution": "class StudentMarket:\n    def __init__(self,symbol,snapshots,depth=10):\n        self.symbol=symbol; self._snapshots=snapshots; self._depth=depth\n        self._engine=MatchingEngine(); self._i=-1; self.book=None\nmarket=StudentMarket('BTC',[{'x':1}],5)", "tier": "nucleo", "min": 5},
        {"title": "B2 · Implementa step()", "practice": "cursor + factory de L7",
         "statement": "Avanza un snapshot y reconstruye `book` con `OrderBook.from_snapshot`. Dos llamadas deben producir dos libros distintos.",
         "given": "from exchange.book import OrderBook\nfrom exchange.matching import MatchingEngine\nrows=[{'bid_price_1':100,'bid_size_1':1,'ask_price_1':101,'ask_size_1':1}, {'bid_price_1':102,'bid_size_1':2,'ask_price_1':103,'ask_size_1':2}]\n",
         "starter": "class StudentMarket:\n    def __init__(self,symbol,snapshots,depth=10):\n        self.symbol=symbol; self._snapshots=snapshots; self._depth=depth\n        self._engine=MatchingEngine(); self._i=-1; self.book=None\n    def step(self):\n        pass\n",
         "validator": "m=StudentMarket('BTC',rows,1); b0=m.step(); b1=m.step()\nassert b0.best_bid==100 and b1.best_bid==102\nassert b0 is not b1 and m.book is b1 and m._i==1\nprint('ok')",
         "solution": "class StudentMarket:\n    def __init__(self,symbol,snapshots,depth=10):\n        self.symbol=symbol; self._snapshots=snapshots; self._depth=depth\n        self._engine=MatchingEngine(); self._i=-1; self.book=None\n    def step(self):\n        self._i+=1\n        if self._i>=len(self._snapshots): self.book=None; return None\n        self.book=OrderBook.from_snapshot(self.symbol,self._snapshots[self._i],self._depth)\n        return self.book", "tier": "nucleo", "min": 7},
        {"title": "B3 · Final de datos", "practice": "estado terminal explícito",
         "statement": "Completa `step()` para que, al agotarse los snapshots, devuelva `None` y también deje `book=None`. Las llamadas posteriores siguen siendo seguras.",
         "given": "from exchange.book import OrderBook\nfrom exchange.matching import MatchingEngine\nrow={'bid_price_1':100,'bid_size_1':1,'ask_price_1':101,'ask_size_1':1}\n",
         "starter": "class StudentMarket:\n    def __init__(self):\n        self.symbol='BTC'; self._snapshots=[row]; self._depth=1; self._engine=MatchingEngine(); self._i=-1; self.book=None\n    def step(self):\n        pass\n",
         "validator": "m=StudentMarket(); assert m.step() is not None\nassert m.step() is None and m.book is None\nassert m.step() is None and m.book is None\nprint('ok')",
         "solution": "class StudentMarket:\n    def __init__(self):\n        self.symbol='BTC'; self._snapshots=[row]; self._depth=1; self._engine=MatchingEngine(); self._i=-1; self.book=None\n    def step(self):\n        self._i+=1\n        if self._i>=len(self._snapshots): self.book=None; return None\n        self.book=OrderBook.from_snapshot(self.symbol,self._snapshots[self._i],self._depth)\n        return self.book", "tier": "nucleo", "min": 5},
        {"title": "B4 · submit() sin book: fail fast", "practice": "raise RuntimeError",
         "statement": "Implementa el guard de `submit`: si no hay libro activo, lanza `RuntimeError` con un mensaje útil.",
         "given": "from exchange.matching import MatchingEngine\n",
         "starter": "class StudentMarket:\n    def __init__(self): self.book=None; self._engine=MatchingEngine()\n    def submit(self,order):\n        pass\nmarket=StudentMarket()\n",
         "validator": "try:\n market.submit(object())\n assert False,'debía lanzar RuntimeError'\nexcept RuntimeError as e:\n assert 'step' in str(e).lower() or 'libro' in str(e).lower()\nprint('ok')",
         "solution": "class StudentMarket:\n    def __init__(self): self.book=None; self._engine=MatchingEngine()\n    def submit(self,order):\n        if self.book is None: raise RuntimeError('no hay libro activo: llama a step() primero')\n        return self._engine.process(order,self.book,None)\nmarket=StudentMarket()", "tier": "nucleo", "min": 4},
        {"title": "B5 · Delega al MatchingEngine", "practice": "composición, no duplicación",
         "statement": "Completa `submit`: debe llamar exactamente al engine contenido con `(order, book, timestamp)` y devolver su resultado.",
         "given": "class SpyEngine:\n    def __init__(self): self.calls=[]\n    def process(self,*args): self.calls.append(args); return ['fill']\n",
         "starter": "class StudentMarket:\n    def __init__(self):\n        self.book=object(); self._engine=SpyEngine(); self._i=0; self._snapshots=[{'timestamp':123}]\n    @property\n    def timestamp(self): return self._snapshots[self._i]['timestamp']\n    def submit(self,order):\n        pass\nmarket=StudentMarket(); order=object(); result=market.submit(order)\n",
         "validator": "assert result==['fill']\nassert market._engine.calls==[(order,market.book,123)]\nprint('ok — Market delega')",
         "solution": "class StudentMarket:\n    def __init__(self):\n        self.book=object(); self._engine=SpyEngine(); self._i=0; self._snapshots=[{'timestamp':123}]\n    @property\n    def timestamp(self): return self._snapshots[self._i]['timestamp']\n    def submit(self,order):\n        if self.book is None: raise RuntimeError('no hay libro activo: llama a step() primero')\n        return self._engine.process(order,self.book,self.timestamp)\nmarket=StudentMarket(); order=object(); result=market.submit(order)", "tier": "nucleo", "min": 5},
        {"title": "B6 · reset()", "practice": "restaurar invariantes",
         "statement": "Implementa `reset`. Después de avanzar y resetear, el primer `step()` debe reproducir exactamente el primer snapshot.",
         "given": "from exchange.book import OrderBook\nfrom exchange.matching import MatchingEngine\nrows=[{'bid_price_1':100,'bid_size_1':1,'ask_price_1':101,'ask_size_1':1},{'bid_price_1':102,'bid_size_1':1,'ask_price_1':103,'ask_size_1':1}]\n",
         "starter": "class StudentMarket:\n    def __init__(self): self.symbol='BTC'; self._snapshots=rows; self._depth=1; self._engine=MatchingEngine(); self._i=-1; self.book=None\n    def step(self):\n        self._i+=1\n        if self._i>=len(self._snapshots): self.book=None; return None\n        self.book=OrderBook.from_snapshot(self.symbol,self._snapshots[self._i],self._depth); return self.book\n    def reset(self):\n        pass\n",
         "validator": "m=StudentMarket(); first=m.step().best_bid; m.step(); m.reset()\nassert m._i==-1 and m.book is None\nassert m.step().best_bid==first==100\nprint('ok')",
         "solution": "class StudentMarket:\n    def __init__(self): self.symbol='BTC'; self._snapshots=rows; self._depth=1; self._engine=MatchingEngine(); self._i=-1; self.book=None\n    def step(self):\n        self._i+=1\n        if self._i>=len(self._snapshots): self.book=None; return None\n        self.book=OrderBook.from_snapshot(self.symbol,self._snapshots[self._i],self._depth); return self.book\n    def reset(self):\n        self._i=-1; self.book=None", "tier": "bien", "min": 4},
        {"title": "B7 · Carga REQUIRED: from_csv, sample y snapshots", "practice": "I/O reproducible y copia defensiva",
         "statement": "Carga explícitamente el CSV sintético con `Market.from_csv`, crea la versión empaquetada con `Market.sample` y lee `snapshots`. Comprueba que ambas rutas producen el mismo replay y que la lista expuesta es una copia defensiva.",
         "given": "import os\nimport exchange\nfrom exchange.market import Market\ncsv_path=os.path.join(os.path.dirname(exchange.__file__),'_data','btc_lob_snapshots.csv')\n",
         "starter": "loaded=None\nsampled=None\nrows=None\n",
         "validator": "assert len(loaded)==len(sampled)==len(rows)==500\nassert rows[0]==sampled.snapshots[0]\nrows[0]['bid_price_1']=-1.0\nassert loaded.snapshots[0]['bid_price_1']!=-1.0, 'snapshots debe devolver una copia defensiva'\nbook=loaded.step()\nassert len(book.bids)==len(book.asks)==3\nprint('ok — from_csv/sample/snapshots son REQUIRED')",
         "solution": "loaded=Market.from_csv(csv_path,depth=3)\nsampled=Market.sample(depth=3)\nrows=loaded.snapshots", "tier": "bien", "min": 6},
        {"title": "B8 · Challenge de integración", "practice": "step → submit → fills → tracker → equity",
         "statement": "Integra las tres lessons: avanza, envía una MARKET, aplica fills al tracker, avanza otra vez y calcula equity. Guarda también `owners`, indicando qué objeto modifica cada acción.",
         "given": "from exchange.book import OrderBook\nfrom exchange.matching import MatchingEngine\nfrom exchange.market import Market\nfrom exchange.orders import Order,OrderType\nfrom exchange.portfolio import PositionTracker\nrows=Market.sample().snapshots[:2]\nclass StudentMarket:\n    def __init__(self): self.symbol='BTCUSDT'; self._snapshots=rows; self._depth=5; self._engine=MatchingEngine(); self._i=-1; self.book=None\n    @property\n    def timestamp(self): return int(self._snapshots[self._i].get('timestamp',self._i)) if 0<=self._i<len(self._snapshots) else None\n    def step(self):\n        self._i+=1\n        if self._i>=len(self._snapshots): self.book=None; return None\n        self.book=OrderBook.from_snapshot(self.symbol,self._snapshots[self._i],self._depth); return self.book\n    def submit(self,o):\n        if self.book is None: raise RuntimeError('llama a step primero')\n        return self._engine.process(o,self.book,self.timestamp)\n",
         "starter": "market=StudentMarket(); tracker=PositionTracker()\nequity=None\nowners=[]\n",
         "validator": "assert isinstance(equity,float) and tracker.position>0\nassert owners==['Market','MatchingEngine/OrderBook','PositionTracker','Market','PositionTracker']\nprint('ok  equity=%.2f'%equity)",
         "solution": "market=StudentMarket(); tracker=PositionTracker(); owners=[]\nbook=market.step(); owners.append('Market')\nfills=market.submit(Order('BTCUSDT','buy',.2,order_type=OrderType.MARKET)); owners.append('MatchingEngine/OrderBook')\nfor fill in fills: tracker.apply_fill(fill)\nowners.append('PositionTracker')\nbook=market.step(); owners.append('Market')\nequity=tracker.equity(book.mid); owners.append('PositionTracker')", "tier": "bien", "min": 8},
    ],
    "aux": [
        {"section": "Gimnasio · Calentamiento — repaso exprés de L8",
         "blurb": "Un disparo y su factura, antes de poner el tiempo en marcha."},
        {"title": "C1. Disparo exprés", "practice": "repaso: market order",
         "statement": "Contra el primer libro, envía una market buy de 0.05 con el engine y guarda `n_fills`.",
         "given": "from exchange.market import Market\nfrom exchange.matching import MatchingEngine\nfrom exchange.orders import Order, OrderType\nbook = Market.sample().step()\n",
         "starter": "n_fills = None\n",
         "validator": "assert n_fills >= 1\nprint('ok ->', n_fills)",
         "solution": "engine = MatchingEngine()\nfills = engine.process(Order('BTCUSDT', 'buy', 0.05, order_type=OrderType.MARKET), book)\nn_fills = len(fills)"},
        {"title": "C2. Factura exprés", "practice": "repaso: precio efectivo",
         "statement": "Con `fills = [(100.0, 1.0), (101.0, 1.0)]`, calcula `eff`.",
         "given": "fills = [(100.0, 1.0), (101.0, 1.0)]\n",
         "starter": "eff = None\n",
         "validator": "assert eff == 100.5\nprint('ok')",
         "solution": "eff = sum(p * s for p, s in fills) / sum(s for p, s in fills)"},

        {"section": "Gimnasio · Bloque 1 — El loop y la cuenta",
         "blurb": "step, submit, equity: el latido del backtest, drill a drill."},
        {"title": "A1. Contar el día", "practice": "el while de step()",
         "statement": "Recorre `Market.sample()` con un while y cuenta los pasos en `n`.",
         "given": "from exchange.market import Market\nm = Market.sample()\n",
         "starter": "n = 0\n",
         "validator": "assert n == 500, 'el dia tiene 500 snapshots'\nprint('ok')",
         "solution": "n = 0\nwhile m.step() is not None:\n    n = n + 1"},
        {"title": "A2. Apertura y cierre", "practice": "primer y último mid",
         "statement": "Recorre el día y guarda `first_mid` y `last_mid`.",
         "given": "from exchange.market import Market\nm = Market.sample()\n",
         "starter": "first_mid = None\nlast_mid = None\n",
         "validator": "assert first_mid is not None and last_mid is not None\nm2 = Market.sample(); b = m2.step()\nassert abs(first_mid - b.mid) < 1e-9\nprint(f'ok  {first_mid} -> {last_mid}')",
         "solution": "first_mid = None\nlast_mid = None\nwhile m.step() is not None:\n    if first_mid is None:\n        first_mid = m.book.mid\n    last_mid = m.book.mid"},
        {"title": "A3. La orden en su momento", "practice": "submit dentro del loop",
         "statement": "Avanza 10 pasos y en el 10º envía una market buy de 0.05 con `m.submit(...)`. Guarda `fills`.",
         "given": "from exchange.market import Market\nfrom exchange.orders import Order, OrderType\nm = Market.sample()\n",
         "starter": "fills = None\n",
         "validator": "assert fills and sum(f.size for f in fills) > 0\nprint('ok ->', fills[0])",
         "solution": "for _ in range(10):\n    m.step()\nfills = m.submit(Order('BTCUSDT', 'buy', 0.05, order_type=OrderType.MARKET))"},
        {"title": "A4. La cuenta tras el fill", "practice": "PositionTracker en el loop",
         "statement": "Aplica los fills dados a un `PositionTracker` y guarda `eq = tracker.equity(100000.0)`.",
         "given": "from exchange.portfolio import PositionTracker\nfrom exchange.trades import Fill\nfills = [Fill(1, 'BTCUSDT', 'buy', 99990.0, 0.1)]\n",
         "starter": "eq = None\n",
         "validator": "assert abs(eq - 1.0) < 1e-6, 'pagaste 9999, vale 10000: +1'\nprint('ok')",
         "solution": "tracker = PositionTracker()\nfor f in fills:\n    tracker.apply_fill(f)\neq = tracker.equity(100000.0)"},
        {"title": "A5. Sin posición no hay historia", "practice": "la curva plana",
         "statement": "Simula 5 pasos SIN operar, apuntando `tracker.equity(m.book.mid)` en `curva`. Comprueba que es plana en 0.",
         "given": "from exchange.market import Market\nfrom exchange.portfolio import PositionTracker\nm = Market.sample()\ntracker = PositionTracker()\n",
         "starter": "curva = []\n",
         "validator": "assert len(curva) == 5\nassert all(abs(x) < 1e-9 for x in curva), 'sin fills, el equity no se mueve'\nprint('ok — la parte plana de la curva')",
         "solution": "curva = []\nfor _ in range(5):\n    m.step()\n    curva.append(tracker.equity(m.book.mid))"},

        {"section": "Para terminar — profundización",
         "blurb": "Trocear la ejecución a lo largo del loop: la semilla del VWAP."},
        {"title": "A6. Schedule de participación", "practice": "repartir un objetivo",
         "statement": "Reparte una compra total de 1.0 en 10 trozos iguales, uno cada 50 pasos. Guarda `executed` (debe sumar ~1.0).",
         "starter": "from exchange import Market, Order, Side, OrderType, PositionTracker\nexecuted = 0.0\n",
         "validator": "assert abs(executed - 1.0) < 1e-6\nprint('ok')",
         "solution": "from exchange import Market, Order, Side, OrderType, PositionTracker\nm = Market.sample(); i = 0; executed = 0.0\nwhile True:\n    book = m.step()\n    if book is None: break\n    if i % 50 == 0 and executed < 1.0 - 1e-9:\n        for f in m.submit(Order('BTCUSDT', Side.BUY, 0.1, order_type=OrderType.MARKET)):\n            executed += f.size\n    i += 1"},

        {"section": "Transferencia — la misma idea, otro dominio",
         "blurb": "El bucle de simulación (leer estado → decidir → acumular → avanzar) no es del mercado: "
                  "es como se simula CUALQUIER sistema en el tiempo. Aquí, el consumo eléctrico de una casa."},
        {"title": "T1. El contador de la luz (mismo loop, otro sistema)",
         "practice": "bucle paso a paso fuera del trading",
         "statement": "Una casa consume, cada hora, `lecturas[i]` kWh. Recórrelas con un bucle acumulando "
                       "el total en `consumido` y, en paralelo, apuntando el acumulado en `curva` "
                       "(como la equity curve, pero de kWh). Es el mismo patrón `step → acumula → avanza`.",
         "given": "lecturas = [0.4, 0.6, 1.2, 0.9, 0.3, 0.5]\n",
         "starter": "consumido = 0.0\ncurva = []\n",
         "validator": "assert abs(consumido - 3.9) < 1e-9, 'la suma de todas las lecturas'\nassert curva == [0.4, 1.0, 2.2, 3.1, 3.4, 3.9], 'la curva es el acumulado paso a paso'\nprint('ok — un loop de simulación es un loop de simulación, venda kWh o BTC')",
         "pista": "Un solo `for x in lecturas:` que haga `consumido += x` y luego "
                  "`curva.append(consumido)`. Es la misma forma que la equity curve del ejercicio A5.",
         "solution": "consumido = 0.0\ncurva = []\nfor x in lecturas:\n    consumido += x\n    curva.append(consumido)"},
    ],
})

# ---------------------------------------------------------------------------
# L10 — Strategy + Backtest (el pico arquitectónico)
# ---------------------------------------------------------------------------
LESSONS.append({
    "n": 10, "slug": "10-strategy-framework",
    "title": "El framework: Strategy + Backtest",
    "piece": "interfaz Strategy (ABC) y el runner Backtest",
    "objective": "El corazón del curso: una estrategia solo reacciona al libro y devuelve acciones. El Backtest la cablea con el mercado y el portfolio. Cualquier estrategia se enchufa igual.",
    "frase": "Escribe una subclase de Strategy y enchúfala al mismo Backtest. Eso es polimorfismo, y es lo que hace todo modular.",
    "concepts": [
        ("Recall L6 → contrato de producción",
         "En L6 todas las estrategias respondían a decide(imbalance) y devolvían una decisión. Conservamos el polimorfismo, pero el framework necesita más capacidad: recibe el libro completo y devuelve 0..N acciones; el motor ejecuta esas acciones.",
         "# L6: decide(imbalance) -> decision\n# L10: on_book_update(book) -> list[Action]"),
        ("La interfaz Strategy",
         "Una estrategia implementa on_book_update(book) y devuelve una lista de acciones (NewOrder/Cancel). No sabe nada del motor. Esa ignorancia es lo que la hace enchufable.",
         "class Strategy(ABC):\n    @abstractmethod\n    def on_book_update(self, book) -> list[Action]:\n        ..."),
        ("Acciones, no efectos",
         "La estrategia no ejecuta órdenes: las pide. Devuelve NewOrder(order). El Backtest decide qué hacer con ellas. Separar decisión de ejecución es la clave del diseño.",
         "return [NewOrder(Order('BTC', Side.BUY, 0.1,\n        order_type=OrderType.MARKET))]"),
        ("El Backtest lo cablea todo",
         "Recorre el mercado, pasa cada libro a la estrategia, ejecuta sus acciones contra el matching, actualiza el portfolio y mide. El mismo run() para cualquier estrategia.",
         "result = Backtest(market, mi_estrategia).run()\nresult.final_equity, result.n_fills"),
    ],
    "build": [
        {"title": "1. Tu primera estrategia", "practice": "heredar de Strategy",
         "statement": "Define `BuyOnce(Strategy)`: en el primer libro envía una market buy de 0.5; después nada.",
         "given": "from exchange import Strategy, NewOrder, Order, Side, OrderType\n",
         "starter": "class BuyOnce(Strategy):\n    def __init__(self):\n        self.done = False\n    def on_book_update(self, book):\n        pass\n",
         "validator": "from exchange import Market, Backtest\nr = Backtest(Market.sample(), BuyOnce()).run()\nassert r.n_fills >= 1 and r.final_position > 0\nprint('ok  fills=%d pos=%.2f' % (r.n_fills, r.final_position))",
         "solution": "class BuyOnce(Strategy):\n    def __init__(self):\n        self.done = False\n    def on_book_update(self, book):\n        if self.done:\n            return []\n        self.done = True\n        return [NewOrder(Order('BTCUSDT', Side.BUY, 0.5, order_type=OrderType.MARKET))]"},
        {"title": "2. Corre el Backtest", "practice": "Backtest.run",
         "statement": "Corre `BuyOnce` con `Backtest(Market.sample(), BuyOnce()).run()`. Guarda `result` y `equity`.",
         "given": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\nclass BuyOnce(Strategy):\n    def __init__(self): self.done=False\n    def on_book_update(self, book):\n        if self.done: return []\n        self.done=True\n        return [NewOrder(Order('BTCUSDT', Side.BUY, 0.5, order_type=OrderType.MARKET))]\n",
         "starter": "result = None\nequity = None\n",
         "validator": "assert result.n_steps == 500\nassert isinstance(equity, float)\nprint('ok ', result)",
         "solution": "result = Backtest(Market.sample(), BuyOnce()).run()\nequity = result.final_equity"},
        {"title": "3. Reacciona a tus fills", "practice": "el hook on_fill",
         "statement": "Define `CountingBuyer(Strategy)` que cuente sus fills en `self.n` vía `on_fill`. Compra 0.1 cada paso.",
         "given": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\n",
         "starter": "class CountingBuyer(Strategy):\n    def __init__(self):\n        self.n = 0\n    def on_book_update(self, book):\n        return [NewOrder(Order('BTCUSDT', Side.BUY, 0.1, order_type=OrderType.MARKET))]\n    def on_fill(self, fill):\n        pass\n",
         "validator": "s = CountingBuyer()\nBacktest(Market.sample(), s).run()\nassert s.n >= 1, 'on_fill debe haberse llamado'\nprint('ok  on_fill llamado %d veces' % s.n)",
         "pista": "Solo falta `on_fill`: recibe un `fill` y hace `self.n += 1`. El `on_book_update` ya está en el starter.",
         "solution": "class CountingBuyer(Strategy):\n    def __init__(self):\n        self.n = 0\n    def on_book_update(self, book):\n        return [NewOrder(Order('BTCUSDT', Side.BUY, 0.1, order_type=OrderType.MARKET))]\n    def on_fill(self, fill):\n        self.n += 1"},
        {"title": "4. Polimorfismo: cambia la estrategia, no el runner", "practice": "intercambiar subclases",
         "statement": "Define `SellOnce` (igual que BuyOnce pero vende). Córrela en el MISMO Backtest. Guarda `pos` (debe ser < 0).",
         "given": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\n",
         "starter": "class SellOnce(Strategy):\n    def __init__(self): self.done=False\n    def on_book_update(self, book):\n        pass\n\npos = None\n",
         "validator": "assert pos < 0, 'SellOnce deja posición corta — mismo runner, otra estrategia'\nprint('ok  pos=%.2f' % pos)",
         "pista": "Copia el patrón BuyOnce: si `self.done`, devuelve `[]`; si no, márcalo y devuelve `[NewOrder(Order(..., Side.SELL, 0.5, order_type=OrderType.MARKET))]`. Luego `Backtest(Market.sample(), SellOnce()).run().final_position`.",
         "solution": "class SellOnce(Strategy):\n    def __init__(self): self.done=False\n    def on_book_update(self, book):\n        if self.done: return []\n        self.done=True\n        return [NewOrder(Order('BTCUSDT', Side.SELL, 0.5, order_type=OrderType.MARKET))]\npos = Backtest(Market.sample(), SellOnce()).run().final_position"},
    ],
    "aux": [
        {"section": "Gimnasio · Calentamiento — repaso exprés de L9",
         "blurb": "El loop y la fórmula de la cuenta, en dos reps."},
        {"title": "C1. El día exprés", "practice": "repaso: contar pasos",
         "statement": "¿Cuántos pasos tiene `Market.sample()`? Cuéntalos en `n` con `len(m.snapshots)`.",
         "given": "from exchange.market import Market\nm = Market.sample()\n",
         "starter": "n = None\n",
         "validator": "assert n == 500\nprint('ok')",
         "solution": "n = len(m.snapshots)"},
        {"title": "C2. equity exprés", "practice": "repaso: la fórmula",
         "statement": "Con `cash = -9999.0` y `position = 0.1`, calcula `eq` al mark 100000.",
         "given": "cash = -9999.0\nposition = 0.1\n",
         "starter": "eq = None\n",
         "validator": "assert abs(eq - 1.0) < 1e-9\nprint('ok')",
         "solution": "eq = cash + position * 100000"},

        {"section": "Gimnasio · Bloque 1 — El contrato Strategy",
         "blurb": "Recupera L6: misma familia polimórfica. La migración es explícita: `decide(imbalance) -> decision` pasa a `on_book_update(book) -> list[Action]` porque ahora decisión y ejecución están separadas."},
        {"title": "A1. La estrategia que no hace nada", "practice": "el contrato mínimo",
         "statement": "Escribe `Hold(Strategy)` cuyo `on_book_update` devuelva `[]`. Pásala por el Backtest y guarda `result`.",
         "given": "from exchange.backtest import Backtest\nfrom exchange.market import Market\nfrom exchange.strategy import Strategy\n",
         "starter": "result = None\n",
         "validator": "assert result.n_steps == 500 and result.n_fills == 0\nassert abs(result.final_equity) < 1e-9\nprint('ok ->', result)",
         "solution": "class Hold(Strategy):\n    def on_book_update(self, book):\n        return []\n\nresult = Backtest(Market.sample(), Hold()).run()"},
        {"title": "A2. Una acción de verdad", "practice": "NewOrder",
         "statement": "Construye la acción `a = NewOrder(Order('BTCUSDT', 'buy', 0.05, order_type=OrderType.MARKET))` y comprueba sus campos.",
         "given": "from exchange.orders import Order, OrderType\nfrom exchange.strategy import NewOrder\n",
         "starter": "a = None\n",
         "validator": "assert isinstance(a, NewOrder)\nassert a.order.side == 'buy' and a.order.size == 0.05\nprint('ok ->', a.order)",
         "solution": "a = NewOrder(Order('BTCUSDT', 'buy', 0.05, order_type=OrderType.MARKET))"},
        {"title": "A3. BuyOnce, tuya", "practice": "la subclase clásica",
         "statement": "Escribe `BuyOnce(Strategy)`: en el primer libro devuelve UNA market buy de 0.1 y después siempre `[]`. Ejecútala y guarda `result`.",
         "given": "from exchange.backtest import Backtest\nfrom exchange.market import Market\nfrom exchange.orders import Order, OrderType\nfrom exchange.strategy import NewOrder, Strategy\n",
         "starter": "result = None\n",
         "validator": "assert result.n_fills >= 1\nassert result.final_position > 0\nprint('ok ->', result)",
         "solution": "class BuyOnce(Strategy):\n    def __init__(self):\n        self._done = False\n    def on_book_update(self, book):\n        if self._done:\n            return []\n        self._done = True\n        return [NewOrder(Order('BTCUSDT', 'buy', 0.1, order_type=OrderType.MARKET))]\n\nresult = Backtest(Market.sample(), BuyOnce()).run()"},
        {"title": "A4. El gancho on_fill", "practice": "feedback del motor",
         "statement": "Añade a tu BuyOnce un contador `self.n_fills` que crezca en `on_fill`. Tras el run, debe coincidir con `result.n_fills`.",
         "given": "from exchange.backtest import Backtest\nfrom exchange.market import Market\nfrom exchange.orders import Order, OrderType\nfrom exchange.strategy import NewOrder, Strategy\n",
         "starter": "strat = None\nresult = None\n",
         "validator": "assert strat.n_fills == result.n_fills\nassert strat.n_fills >= 1\nprint('ok ->', strat.n_fills, 'fills contados por la estrategia')",
         "solution": "class BuyOnce(Strategy):\n    def __init__(self):\n        self._done = False\n        self.n_fills = 0\n    def on_book_update(self, book):\n        if self._done:\n            return []\n        self._done = True\n        return [NewOrder(Order('BTCUSDT', 'buy', 0.1, order_type=OrderType.MARKET))]\n    def on_fill(self, fill):\n        self.n_fills += 1\n\nstrat = BuyOnce()\nresult = Backtest(Market.sample(), strat).run()"},
        {"title": "A5. El mismo runner, dos vidas", "practice": "polimorfismo en producción",
         "statement": "Ejecuta `Hold` y `BuyOnce` (dadas) por el MISMO `Backtest.run()` y guarda `(eq_hold, eq_buy)`. Ni una línea del motor cambió.",
         "given": "from exchange.backtest import Backtest\nfrom exchange.market import Market\nfrom exchange.orders import Order, OrderType\nfrom exchange.strategy import NewOrder, Strategy\n\nclass Hold(Strategy):\n    def on_book_update(self, book):\n        return []\n\nclass BuyOnce(Strategy):\n    def __init__(self):\n        self._done = False\n    def on_book_update(self, book):\n        if self._done:\n            return []\n        self._done = True\n        return [NewOrder(Order('BTCUSDT', 'buy', 0.1, order_type=OrderType.MARKET))]\n",
         "starter": "eq_hold = None\neq_buy = None\n",
         "validator": "assert abs(eq_hold) < 1e-9\nassert abs(eq_buy) > 1e-9, 'BuyOnce tiene posicion: su equity se movio'\nprint(f'ok  hold={eq_hold} buy={eq_buy:.2f}')",
         "solution": "eq_hold = Backtest(Market.sample(), Hold()).run().final_equity\neq_buy = Backtest(Market.sample(), BuyOnce()).run().final_equity"},

        {"section": "Para terminar — profundización",
         "blurb": "Una estrategia con señal de verdad, lista para el juicio de L11."},
        {"title": "A6. Estrategia con señal", "practice": "decidir según el libro",
         "statement": "Define `ImbalanceBuyer`: compra 0.1 (market) solo cuando `book.imbalance(1) > 0.3`. Guarda `fills` del backtest.",
         "starter": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\nclass ImbalanceBuyer(Strategy):\n    def on_book_update(self, book):\n        pass\nfills = None\n",
         "validator": "assert fills is not None and fills >= 0\nprint('ok  fills=%d' % fills)",
         "solution": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\nclass ImbalanceBuyer(Strategy):\n    def on_book_update(self, book):\n        if book.imbalance(1) is not None and book.imbalance(1) > 0.3:\n            return [NewOrder(Order('BTCUSDT', Side.BUY, 0.1, order_type=OrderType.MARKET))]\n        return []\nfills = Backtest(Market.sample(), ImbalanceBuyer()).run().n_fills"},
    ],
})

# ---------------------------------------------------------------------------
# L11 — Primera estrategia + métricas
# ---------------------------------------------------------------------------
LESSONS.append({
    "n": 11, "slug": "11-first-strategy-metrics",
    "title": "Primera estrategia + métricas",
    "piece": "medir una estrategia contra un benchmark",
    "objective": "Someter el motor completo de L1–L10 a una estrategia con señal operativa y métricas honestas — PnL, posición, parent arrival para la decisión y decision mid para la ejecución de cada orden hija. Checkpoint integrador que depende directamente del contrato y el runner de L10.",
    "frase": "Sin benchmark no hay estrategia: parent arrival juzga la decisión; cada decision mid juzga su ejecución.",
    "concepts": [
        ("Una estrategia con criterio",
         "Compra cuando el libro empuja arriba (imbalance positivo), vende cuando empuja abajo. Simple, pero ya es una decisión basada en microestructura.",
         "if book.imbalance(3) > thr:  buy\nelif book.imbalance(3) < -thr: sell"),
        ("Dos llegadas, dos preguntas",
         "El parent arrival es el primer mid y evalúa la decisión completa. Cada orden hija tiene su propio decision mid y mide solo su ejecución. No se mezclan.",
         "parent_arrival = primer book.mid\nchild_slippage = sign * (fill - decision_mid)"),
        ("Leer el resultado con honestidad",
         "final_equity, posición final, número de fills. Un equity positivo con inventario enorme no es una buena estrategia: es riesgo escondido.",
         "result.final_equity, result.final_position,\nresult.n_fills"),
    ],
    "build": [
        {"title": "1. Estrategia de imbalance", "practice": "señal larga/corta",
         "statement": "Define `ImbalanceStrategy(thr)`: compra 0.05 si `imbalance(3) > thr`, vende 0.05 si `< -thr`. Market orders.",
         "given": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\n",
         "starter": "class ImbalanceStrategy(Strategy):\n    def __init__(self, thr=0.3):\n        self.thr = thr\n    def on_book_update(self, book):\n        pass\n",
         "validator": "r = Backtest(Market.sample(), ImbalanceStrategy(0.3)).run()\nassert r.n_steps == 500\nprint('ok ', r)",
         "solution": "class ImbalanceStrategy(Strategy):\n    def __init__(self, thr=0.3):\n        self.thr = thr\n    def on_book_update(self, book):\n        imb = book.imbalance(3)\n        if imb is None: return []\n        if imb > self.thr:\n            return [NewOrder(Order('BTCUSDT', Side.BUY, 0.05, order_type=OrderType.MARKET))]\n        if imb < -self.thr:\n            return [NewOrder(Order('BTCUSDT', Side.SELL, 0.05, order_type=OrderType.MARKET))]\n        return []"},
        {"title": "2. Mídela", "practice": "leer BacktestResult",
         "statement": "Corre la estrategia y guarda `equity`, `pos` y `fills` del resultado.",
         "given": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\nclass ImbalanceStrategy(Strategy):\n    def __init__(self, thr=0.3): self.thr=thr\n    def on_book_update(self, book):\n        imb = book.imbalance(3)\n        if imb is None: return []\n        if imb > self.thr: return [NewOrder(Order('BTCUSDT', Side.BUY, 0.05, order_type=OrderType.MARKET))]\n        if imb < -self.thr: return [NewOrder(Order('BTCUSDT', Side.SELL, 0.05, order_type=OrderType.MARKET))]\n        return []\n",
         "starter": "equity = None\npos = None\nfills = None\n",
         "validator": "assert isinstance(equity, float) and isinstance(fills, int)\nprint('ok  equity=%.2f pos=%.3f fills=%d' % (equity, pos, fills))",
         "solution": "r = Backtest(Market.sample(), ImbalanceStrategy(0.3)).run()\nequity = r.final_equity\npos = r.final_position\nfills = r.n_fills"},
        {"title": "3. Parent arrival", "practice": "primer mid de la decisión completa",
         "statement": "Guarda `arrival_mid`, el parent-order arrival: mid del primer snapshot del mercado.",
         "starter": "from exchange import Market\narrival_mid = None\n",
         "validator": "assert 90000 < arrival_mid < 110000\nprint('ok  arrival_mid=%.2f' % arrival_mid)",
         "pista": "Encadena: `Market.sample()` te da el mercado, `.step()` el primer libro, `.mid` su punto medio.",
         "solution": "from exchange import Market\narrival_mid = Market.sample().step().mid"},
        {"title": "4. Riesgo escondido", "practice": "interpretar inventario",
         "statement": "Para `thr=0.1` y `thr=0.5`, guarda en `pos_small_thr` y `pos_big_thr` la posición final. Un umbral bajo opera más y arriesga más inventario.",
         "given": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\nclass ImbalanceStrategy(Strategy):\n    def __init__(self, thr=0.3): self.thr=thr\n    def on_book_update(self, book):\n        imb = book.imbalance(3)\n        if imb is None: return []\n        if imb > self.thr: return [NewOrder(Order('BTCUSDT', Side.BUY, 0.05, order_type=OrderType.MARKET))]\n        if imb < -self.thr: return [NewOrder(Order('BTCUSDT', Side.SELL, 0.05, order_type=OrderType.MARKET))]\n        return []\n",
         "starter": "pos_small_thr = None\npos_big_thr = None\n",
         "validator": "assert pos_small_thr is not None and pos_big_thr is not None\nprint('ok  thr0.1 pos=%.3f | thr0.5 pos=%.3f' % (pos_small_thr, pos_big_thr))",
         "pista": "Dos backtests idénticos salvo el umbral: `Backtest(Market.sample(), ImbalanceStrategy(0.1)).run().final_position`, y lo mismo con 0.5. `Market.sample()` nuevo en cada uno, para que ambos vean el mismo día.",
         "solution": "pos_small_thr = Backtest(Market.sample(), ImbalanceStrategy(0.1)).run().final_position\npos_big_thr = Backtest(Market.sample(), ImbalanceStrategy(0.5)).run().final_position"},
    ],
    "aux": [
        {"section": "Gimnasio · Calentamiento — repaso exprés de L10",
         "blurb": "El contrato y el resultado del runner, en dos reps."},
        {"title": "C1. Contrato exprés", "practice": "repaso: Strategy",
         "statement": "Escribe `Hold(Strategy)` (devuelve `[]`) e instánciala en `h`.",
         "given": "from exchange.strategy import Strategy\n",
         "starter": "h = None\n",
         "validator": "assert h.on_book_update(None) == []\nprint('ok')",
         "solution": "class Hold(Strategy):\n    def on_book_update(self, book):\n        return []\n\nh = Hold()"},
        {"title": "C2. Leer el resultado", "practice": "repaso: BacktestResult",
         "statement": "De un run de Hold, guarda `pasos` y `n_fills`.",
         "given": "from exchange.backtest import Backtest\nfrom exchange.market import Market\nfrom exchange.strategy import Strategy\nclass Hold(Strategy):\n    def on_book_update(self, book):\n        return []\nresult = Backtest(Market.sample(), Hold()).run()\n",
         "starter": "pasos = None\nn_fills = None\n",
         "validator": "assert pasos == 500 and n_fills == 0\nprint('ok')",
         "solution": "pasos = result.n_steps\nn_fills = result.n_fills"},

        {"section": "Gimnasio · Bloque 1 — Medir con criterio",
         "blurb": "Arrival, slippage y benchmarks: la caja de herramientas del juicio."},
        {"title": "A1. El parent arrival mid", "practice": "benchmark de la decisión completa",
         "statement": "Guarda `arrival`: el mid del PRIMER snapshot (parent-order arrival, cuando decidiste empezar).",
         "given": "from exchange.market import Market\nm = Market.sample()\n",
         "starter": "arrival = None\n",
         "validator": "m2 = Market.sample()\nassert abs(arrival - m2.step().mid) < 1e-9\nprint(f'ok  arrival={arrival}')",
         "solution": "arrival = m.step().mid"},
        {"title": "A2. Slippage de un fill", "practice": "contra el decision mid de la orden hija",
         "statement": "Compra a 100024.5 con decision mid 100000; venta a 99980 con decision mid 100000. Calcula `slip_buy` y `slip_sell` (positivo = te costó dinero).",
         "starter": "slip_buy = None\nslip_sell = None\n",
         "validator": "assert abs(slip_buy - 24.5) < 1e-9, 'compra: precio - mid'\nassert abs(slip_sell - 20.0) < 1e-9, 'venta: mid - precio'\nprint('ok')",
         "solution": "slip_buy = 100024.5 - 100000\nslip_sell = 100000 - 99980"},
        {"title": "A3. El coste total de ejecutar", "practice": "slippage agregado",
         "statement": "Con `slips` (por unidad) y clip 0.05, calcula `coste = media × n × clip`.",
         "given": "slips = [5.2, 6.1, 4.8, 7.0, 5.9]\nclip = 0.05\n",
         "starter": "coste = None\n",
         "validator": "assert abs(coste - 1.45) < 1e-6\nprint(f'ok  coste={coste}')",
         "solution": "media = sum(slips) / len(slips)\ncoste = media * len(slips) * clip"},
        {"title": "A4. ¿Fuera de la nube?", "practice": "benchmark contra el azar",
         "statement": "Tu equity final fue `-27.3`; tres monos aleatorios hicieron `[5.4, -46.0, 8.6]`. Guarda `fuera` (True si tu resultado queda FUERA del rango de los monos).",
         "given": "mi_equity = -27.3\nmonos = [5.4, -46.0, 8.6]\n",
         "starter": "fuera = None\n",
         "validator": "assert fuera is False, 'dentro del rango del azar: nada demostrado'\nprint('ok — humildad estadistica')",
         "solution": "fuera = mi_equity < min(monos) or mi_equity > max(monos)"},
        {"title": "A5. PnL sin riesgo es media verdad", "practice": "comparar con inventario",
         "statement": "Dos estrategias: A = (PnL 30, máx inventario 2.0), B = (PnL 24, máx inventario 0.4). Guarda `mejor_por_unidad` ('A' o 'B') según PnL por unidad de inventario máximo.",
         "given": "pnl_a, inv_a = 30.0, 2.0\npnl_b, inv_b = 24.0, 0.4\n",
         "starter": "mejor_por_unidad = None\n",
         "validator": "assert mejor_por_unidad == 'B', '15 vs 60 de PnL por unidad de riesgo'\nprint('ok')",
         "solution": "ratio_a = pnl_a / inv_a\nratio_b = pnl_b / inv_b\nmejor_por_unidad = 'A' if ratio_a > ratio_b else 'B'"},

        {"section": "Para terminar — profundización OPTIONAL",
         "blurb": "La serie `equity_curve` ya se construyó en L9 y forma parte de `BacktestResult` desde L10. Aquí solo es OPTIONAL dibujarla con matplotlib."},
        {"title": "A6. Graficar la curva de equity", "practice": "visualización opcional con matplotlib",
         "statement": "Corre la estrategia y guarda `curve = result.equity_curve`. Verifica que tiene 500 puntos. Como profundización opcional, dibuja después esa serie con matplotlib.",
         "given": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\nclass S(Strategy):\n    def on_book_update(self, book):\n        return [NewOrder(Order('BTCUSDT', Side.BUY, 0.01, order_type=OrderType.MARKET))]\n",
         "starter": "curve = None\n",
         "validator": "assert len(curve) == 500\nprint('ok  puntos=%d' % len(curve))",
         "solution": "curve = Backtest(Market.sample(), S()).run().equity_curve"},

        {"section": "Transferencia — la misma idea, otro dominio",
         "blurb": "Medir PnL por unidad de riesgo (el A5 de arriba) es un caso de una idea universal: "
                  "no mires el resultado bruto, mira el resultado POR unidad de lo que gastas. "
                  "Aquí, comparar la compra del súper por valor nutricional por euro."},
        {"title": "T1. La cesta que rinde más (ratio, fuera del trading)",
         "practice": "resultado por unidad de coste, fuera del trading",
         "statement": "Dos cestas de la compra: A aporta 1800 kcal por 6.0 €, B aporta 1500 kcal por 4.0 €. "
                       "Igual que elegiste la estrategia por PnL-por-riesgo, elige `mejor` ('A' o 'B') por "
                       "**kcal por euro**. La bruta no decide: decide el ratio.",
         "given": "kcal_a, precio_a = 1800, 6.0\nkcal_b, precio_b = 1500, 4.0\n",
         "starter": "mejor = None\n",
         "validator": "assert mejor == 'B', '300 vs 375 kcal/€: la cesta más barata rinde más por euro'\nprint('ok — el Sharpe era esto: no el PnL bruto, sino el PnL por unidad de riesgo')",
         "pista": "Calca el A5: un ratio por lado (`kcal_a / precio_a` y el de B) y un ternario que "
                  "devuelve la letra del mayor.",
         "solution": "ratio_a = kcal_a / precio_a\nratio_b = kcal_b / precio_b\nmejor = 'A' if ratio_a > ratio_b else 'B'"},
    ],
})
