"""Specs de las lecciones de ejecución y market making (L12 VWAP, L13 MM, L14 A-S).

Todas las estrategias son subclases de Strategy y se enchufan al mismo motor.
El market making usa MMSimulation (modelo de intensidad de fills).
"""

LESSONS = []

# ---------------------------------------------------------------------------
# L12 — VWAP (baselines + dinámico)
# ---------------------------------------------------------------------------
LESSONS.append({
    "n": 12, "slug": "12-vwap-execution",
    "title": "VWAP — Ejecución",
    "piece": "VWAPStrategy: repartir una orden por el perfil de volumen (estático y dinámico)",
    "objective": "Primer algoritmo de ejecución: repartir una orden grande en trozos a lo largo de la sesión. Empezamos con baselines (TWAP, VWAP) y subimos a predecir el volumen con el flujo reciente.",
    "frase": "No mandes la orden de golpe: repártela. TWAP reparte en el tiempo; VWAP, donde hay volumen; y el flujo reciente afina el plan.",
    "concepts": [
        ("Por qué trocear",
         "Una orden grande de golpe barre el libro y paga slippage. Repartirla en el tiempo reduce el impacto.",
         "VWAPStrategy('BTC', Side.BUY,\n    total_size=1.0, horizon=20)"),
        ("TWAP vs VWAP",
         "TWAP parte en trozos iguales; VWAP pondera por el perfil de volumen para acercarse al precio medio ponderado por volumen.",
         "profile = [1/N]*N        # TWAP\nprofile = [.05,.10,.20,...] # VWAP"),
        ("Volumen dinámico",
         "El perfil fijo asume que hoy es como la media. Predecir el volumen del próximo intervalo con los últimos k afina el schedule.",
         "pred = sum(volumes[-k:]) / k"),
    ],
    "build": [
        {"title": "1. Schedule TWAP", "practice": "pesos uniformes",
         "statement": "Crea `profile`, una lista de 10 pesos iguales que sumen 1.",
         "starter": "N = 10\nprofile = None\n",
         "validator": "assert len(profile) == 10 and abs(sum(profile) - 1) < 1e-9\nassert len(set(profile)) == 1, 'TWAP: todos iguales'\nprint('ok')",
         "solution": "N = 10\nprofile = [1/N] * N"},
        {"title": "2. Lanza un VWAPStrategy", "practice": "estrategia de ejecución",
         "statement": "Ejecuta una compra total de 1.0 en horizonte 20 con `VWAPStrategy`. Guarda `executed` (suma de fills).",
         "given": "from exchange import Market, Backtest, Side\nfrom exchange.strategies import VWAPStrategy\n",
         "starter": "executed = None\n",
         "validator": "assert abs(executed - 1.0) < 1e-6, 'el VWAP debe ejecutar el total'\nprint('ok  executed=%.3f' % executed)",
         "solution": "strat = VWAPStrategy('BTCUSDT', Side.BUY, total_size=1.0, horizon=20)\nr = Backtest(Market.sample(), strat).run()\nexecuted = sum(f.size for f in r.fills)"},
        {"title": "3. Perfil VWAP a medida", "practice": "pasar un perfil",
         "statement": "Pasa un `profile` con más peso al principio (p.ej. decreciente) a `VWAPStrategy(..., profile=profile)`. Guarda `executed`.",
         "given": "from exchange import Market, Backtest, Side\nfrom exchange.strategies import VWAPStrategy\nprofile = [5,4,3,2,1]\n",
         "starter": "executed = None\n",
         "validator": "assert abs(executed - 1.0) < 1e-6\nprint('ok')",
         "solution": "strat = VWAPStrategy('BTCUSDT', Side.BUY, 1.0, horizon=5, profile=profile)\nr = Backtest(Market.sample(), strat).run()\nexecuted = sum(f.size for f in r.fills)"},
        {"title": "4. Precio medio de ejecución", "practice": "VWAP de tus fills",
         "statement": "Calcula `vwap_price`, el precio medio ponderado por tamaño de tus fills al ejecutar 1.0 en horizonte 20.",
         "given": "from exchange import Market, Backtest, Side\nfrom exchange.strategies import VWAPStrategy\n",
         "starter": "vwap_price = None\n",
         "validator": "assert 90000 < vwap_price < 110000\nprint('ok  vwap_price=%.2f' % vwap_price)",
         "solution": "r = Backtest(Market.sample(), VWAPStrategy('BTCUSDT', Side.BUY, 1.0, 20)).run()\nvwap_price = sum(f.price*f.size for f in r.fills) / sum(f.size for f in r.fills)"},
        {"title": "5. Media rolada", "practice": "ventana de los últimos k",
         "statement": "Escribe `rolling_mean(xs, k)` que devuelva la media de los últimos k elementos.",
         "starter": "def rolling_mean(xs, k):\n    pass\n",
         "validator": "assert abs(rolling_mean([1,2,3,4], 2) - 3.5) < 1e-9\nprint('ok')",
         "pista": "El slicing `xs[-k:]` te da exactamente los últimos k elementos; su `sum(...)` dividida entre `k` es la media.",
         "solution": "def rolling_mean(xs, k):\n    return sum(xs[-k:]) / k"},
        {"title": "6. Predice el próximo volumen", "practice": "usar la ventana",
         "statement": "Dada `volumes`, predice el siguiente como la media de los últimos 3. Guarda `pred`.",
         "given": "volumes = [100, 120, 90, 110, 130]\n",
         "starter": "pred = None\n",
         "validator": "assert abs(pred - 110) < 1e-9\nprint('ok  pred=%.1f' % pred)",
         "pista": "Es `rolling_mean(volumes, 3)` escrito a mano: `sum(volumes[-3:]) / 3`.",
         "solution": "pred = sum(volumes[-3:]) / 3"},
        {"title": "7. Perfil dinámico", "practice": "normalizar predicciones",
         "statement": "Dadas predicciones `preds`, conviértelas en un perfil que sume 1. Guarda `profile`.",
         "given": "preds = [120, 80, 200]\n",
         "starter": "profile = None\n",
         "validator": "assert abs(sum(profile) - 1) < 1e-9\nassert profile[2] > profile[0] > profile[1], 'más peso donde más volumen'\nprint('ok')",
         "pista": "Normalizar = dividir cada elemento entre el total: `total = sum(preds)` y luego `[p/total for p in preds]`. Comprueba mentalmente que la suma da 1.",
         "solution": "total = sum(preds)\nprofile = [p/total for p in preds]"},
        {"title": "8. Factor de corrección", "practice": "ir a tiempo",
         "statement": "Escribe `correction(target_so_far, executed, remaining_slices)`: cuánto mandar ahora para volver al plan.",
         "starter": "def correction(target_so_far, executed, remaining_slices):\n    pass\n",
         "validator": "assert abs(correction(0.5, 0.3, 2) - 0.1) < 1e-9, 'faltan 0.2 en 2 trozos -> 0.1'\nprint('ok')",
         "pista": "Lo que *deberías* llevar menos lo que llevas es el déficit: `target_so_far - executed`. Repártelo a partes iguales entre los slices que quedan.",
         "solution": "def correction(target_so_far, executed, remaining_slices):\n    return (target_so_far - executed) / remaining_slices"},
    ],
    "aux": [
        {"section": "Gimnasio · Calentamiento — repaso exprés de L11",
         "blurb": "Slippage y benchmarks, en dos reps antes de trocear."},
        {"title": "C1. Slippage exprés", "practice": "repaso: eff vs mid",
         "statement": "Vendiste con precio medio 99974.5 y el mid era 100000. Guarda `coste_bps`.",
         "given": "eff = 99974.5\nmid = 100000.0\n",
         "starter": "coste_bps = None\n",
         "validator": "assert abs(coste_bps - 2.55) < 1e-2\nprint('ok')",
         "solution": "coste_bps = (mid - eff) / mid * 10000"},
        {"title": "C2. Media ponderada exprés", "practice": "repaso: precio medio",
         "statement": "Con `fills = [(100, 2.0), (99, 1.0)]`, calcula `avg`.",
         "given": "fills = [(100, 2.0), (99, 1.0)]\n",
         "starter": "avg = None\n",
         "validator": "assert abs(avg - 99.6666666) < 1e-4\nprint('ok')",
         "solution": "avg = sum(p * s for p, s in fills) / sum(s for p, s in fills)"},

        {"section": "Gimnasio · Bloque 1 — Schedules y perfiles",
         "blurb": "Pesos, trozos y el precio medio: la mecánica del VWAP."},
        {"title": "A1. Pesos TWAP", "practice": "el baseline",
         "statement": "Construye `w`, los pesos TWAP para 20 intervalos. Deben sumar 1.",
         "starter": "w = None\n",
         "validator": "assert len(w) == 20\nassert abs(sum(w) - 1.0) < 1e-9\nassert abs(w[0] - 0.05) < 1e-9\nprint('ok')",
         "solution": "w = [1 / 20] * 20"},
        {"title": "A2. Normaliza el perfil", "practice": "de volumen a pesos",
         "statement": "El perfil crudo es `[3, 1, 1, 1, 4]` (la U). Normalízalo en `w` para que sume 1.",
         "given": "raw = [3, 1, 1, 1, 4]\n",
         "starter": "w = None\n",
         "validator": "assert abs(sum(w) - 1.0) < 1e-9\nassert abs(w[0] - 0.3) < 1e-9 and abs(w[-1] - 0.4) < 1e-9\nprint('ok')",
         "solution": "total = sum(raw)\nw = [x / total for x in raw]"},
        {"title": "A3. Del peso al trozo", "practice": "slice sizes",
         "statement": "Con total 5.0 BTC y los pesos dados, construye `slices` (tamaño por intervalo). Su suma debe dar el total.",
         "given": "total = 5.0\nw = [0.3, 0.1, 0.1, 0.1, 0.4]\n",
         "starter": "slices = None\n",
         "validator": "assert abs(sum(slices) - 5.0) < 1e-9\nassert abs(slices[0] - 1.5) < 1e-9\nprint('ok')",
         "solution": "slices = [total * x for x in w]"},
        {"title": "A4. El VWAP de la sesión", "practice": "el benchmark que da nombre",
         "statement": "Con precios y volúmenes de la sesión, calcula `vwap_sesion` = Σp·v / Σv.",
         "given": "precios = [100.0, 101.0, 102.0]\nvolumenes = [5.0, 2.0, 1.0]\n",
         "starter": "vwap_sesion = None\n",
         "validator": "assert abs(vwap_sesion - 100.5) < 1e-9\nprint('ok')",
         "solution": "vwap_sesion = sum(p * v for p, v in zip(precios, volumenes)) / sum(volumenes)"},
        {"title": "A5. La estrategia entera, por el motor", "practice": "VWAPStrategy real",
         "statement": "Ejecuta `VWAPStrategy('BTCUSDT', 'sell', 1.0, horizon=500)` (TWAP) por el Backtest y comprueba en `ejecutado` que vendió ~1.0.",
         "given": "from exchange.backtest import Backtest\nfrom exchange.market import Market\nfrom exchange.strategies.vwap import VWAPStrategy\n",
         "starter": "ejecutado = None\n",
         "validator": "assert abs(ejecutado - 1.0) < 0.05, 'el schedule completo casi todo el total'\nprint(f'ok  ejecutado={ejecutado:.3f}')",
         "solution": "strat = VWAPStrategy('BTCUSDT', 'sell', 1.0, horizon=500)\nresult = Backtest(Market.sample(), strat).run()\nejecutado = sum(f.size for f in result.fills)"},

        {"section": "Para terminar — profundización",
         "blurb": "La normalización interna y el puente a ML."},
        {"title": "A6. El perfil se normaliza solo", "practice": "pesos relativos",
         "statement": "Comprueba que un perfil `[2,2,2,2,2]` ejecuta lo mismo que `[1,1,1,1,1]`: guarda ambos `executed` en `a` y `b`.",
         "starter": "from exchange import Market, Backtest, Side\nfrom exchange.strategies import VWAPStrategy\na = None\nb = None\n",
         "validator": "assert abs(a - b) < 1e-9\nprint('ok')",
         "solution": "from exchange import Market, Backtest, Side\nfrom exchange.strategies import VWAPStrategy\ndef run(p):\n    r = Backtest(Market.sample(), VWAPStrategy('BTCUSDT', Side.BUY, 1.0, 5, profile=p)).run()\n    return sum(f.size for f in r.fills)\na = run([2,2,2,2,2]); b = run([1,1,1,1,1])"},
        {"title": "A7. Regresión lineal (extensión ML, stdlib)", "practice": "mínimos cuadrados a mano",
         "statement": "Escribe `slope(xs, ys)` = pendiente de la recta de mínimos cuadrados (cov/var). Es la base de predecir volumen con una feature.",
         "starter": "def slope(xs, ys):\n    pass\n",
         "validator": "assert abs(slope([1,2,3],[2,4,6]) - 2) < 1e-9\nprint('ok — esto es lo que hace LinearRegression por dentro')",
         "solution": "def slope(xs, ys):\n    n = len(xs); mx = sum(xs)/n; my = sum(ys)/n\n    cov = sum((x-mx)*(y-my) for x,y in zip(xs,ys))\n    var = sum((x-mx)**2 for x in xs)\n    return cov / var"},

        {"section": "Transferencia — la misma idea, otro dominio",
         "blurb": "El VWAP no inventa nada: reparte un total en el tiempo siguiendo un perfil de actividad. "
                  "La misma cuenta sirve para una panadería que hornea según la demanda por hora."},
        {"title": "T1. La panadería que sigue la demanda (VWAP sin mercado)",
         "practice": "perfil normalizado fuera del trading",
         "statement": "Una panadería quiere hornear **100 barras** repartidas en una jornada de 8 horas, "
                       "proporcionalmente a la demanda esperada `demanda` (clientes por hora). "
                       "Calcula `plan[i]` = barras a hornear en la hora i: normaliza `demanda` para que "
                       "sume 1 y multiplica por 100. Es exactamente el perfil VWAP.",
         "given": "demanda = [5, 10, 20, 25, 20, 10, 6, 4]  # clientes por hora\n",
         "starter": "plan = None\n",
         "validator": "assert abs(sum(plan) - 100) < 1e-9, 'el plan reparte las 100 barras enteras'\nassert plan.index(max(plan)) == demanda.index(max(demanda)), 'horneas más donde hay más demanda'\nprint('ok — el VWAP era repartir un total según un perfil; el pan no lo sabe, pero lo hace igual')",
         "pista": "Dos pasos, como el perfil dinámico (A/ejercicio 7 del build): `total = sum(demanda)` y "
                  "`plan = [d/total*100 for d in demanda]`. La normalización hace que sume justo 100.",
         "solution": "total = sum(demanda)\nplan = [d / total * 100 for d in demanda]"},
    ],
})

# ---------------------------------------------------------------------------
# L13 — Market making intro
# ---------------------------------------------------------------------------
LESSONS.append({
    "n": 13, "slug": "13-market-making-intro",
    "title": "Market making — Intro",
    "piece": "MarketMaker: cotizar a ambos lados y gestionar inventario",
    "objective": "El otro lado del mercado: en vez de cruzar, cotizas bid y ask y ganas el spread. Pero acumulas inventario, y el inventario es riesgo. Skew por inventario como primera defensa.",
    "frase": "El market maker gana el spread, pero su enemigo es el inventario: cotiza para volver a plano.",
    "concepts": [
        ("De dónde sale el PnL",
         "Compras en el bid, vendes en el ask, te quedas el spread. Si el flujo es equilibrado, ganas en cada vuelta.",
         "MarketMaker('BTC', half_spread=0.5)\n# bid = mid - 0.5, ask = mid + 0.5"),
        ("Riesgo de inventario y adverse selection",
         "Si solo te compran o solo te venden, acumulas posición justo cuando el mercado va en tu contra. Eso es adverse selection.",
         "inventario alto -> riesgo de que\nel mid se mueva en tu contra"),
        ("Skew por inventario",
         "Cuando estás largo, baja tus dos cotizaciones para que te compren menos y te vendan más, y vuelvas a plano.",
         "r = mid - skew * inventory\nbid = r - half_spread; ask = r + half_spread"),
    ],
    "build": [
        {"title": "1. Cotiza alrededor del mid", "practice": "MarketMaker.quotes",
         "statement": "Crea un `MarketMaker('BTC', half_spread=0.5)` y un libro con mid 100. Guarda `bid` y `ask` de `quotes(book)`.",
         "given": "from exchange import OrderBook, Level\nfrom exchange.strategies import MarketMaker\nbook = OrderBook('BTC', [Level(99.5,1)], [Level(100.5,1)])\n",
         "starter": "mm = None\nbid = None\nask = None\n",
         "validator": "assert bid < 100 < ask, 'cotizas por debajo y por encima del mid'\nassert abs((ask - bid) - 1.0) < 1e-9, 'spread = 2*half_spread'\nprint('ok  bid=%.2f ask=%.2f' % (bid, ask))",
         "solution": "from exchange import OrderBook, Level\nfrom exchange.strategies import MarketMaker\nmm = MarketMaker('BTC', half_spread=0.5)\nbid, ask = mm.quotes(book)"},
        {"title": "2. El skew baja las cotizaciones si estás largo", "practice": "inventario -> reservation price",
         "statement": "Con el mismo MM, fija `mm._inventory = 2` y vuelve a cotizar. El nuevo `bid2` debe ser menor que el bid de inventario 0.",
         "given": "from exchange import OrderBook, Level\nfrom exchange.strategies import MarketMaker\nbook = OrderBook('BTC', [Level(99.5,1)], [Level(100.5,1)])\nmm = MarketMaker('BTC', half_spread=0.5, inventory_skew=1.0)\nbid0, _ = mm.quotes(book)\n",
         "starter": "bid2 = None\n",
         "validator": "assert bid2 < bid0, 'largo de inventario -> cotizas más bajo para soltar'\nprint('ok  bid0=%.2f bid2=%.2f' % (bid0, bid2))",
         "solution": "mm._inventory = 2\nbid2, _ = mm.quotes(book)"},
        {"title": "3. Reservation price", "practice": "centro de las cotizaciones",
         "statement": "El reservation price con inventario positivo debe estar por debajo del mid. Guarda `r` con `mm._inventory=2`, mid 100.",
         "given": "from exchange.strategies import MarketMaker\nmm = MarketMaker('BTC', inventory_skew=1.0)\nmm._inventory = 2\n",
         "starter": "r = None\n",
         "validator": "assert r < 100, 'largo -> reservation price por debajo del mid'\nprint('ok  r=%.2f' % r)",
         "pista": "Solo llamas al método: `mm.reservation_price(100)`. La gracia está en comprobar que, con inventario +2, sale por debajo de 100 — el MM quiere vender.",
         "solution": "r = mm.reservation_price(100)"},
        {"title": "4. Simula al market maker", "practice": "MMSimulation",
         "statement": "Corre `MMSimulation(MarketMaker('BTC', half_spread=0.3), steps=300)`. Guarda `pnl` y `max_inv` del resultado.",
         "given": "from exchange.strategies import MarketMaker\nfrom exchange.simulation import MMSimulation\n",
         "starter": "pnl = None\nmax_inv = None\n",
         "validator": "assert isinstance(pnl, float) and max_inv >= 0\nprint('ok  pnl=%.2f max|inv|=%.2f' % (pnl, max_inv))",
         "pista": "Encadena construcción y ejecución: `MMSimulation(MarketMaker('BTC', half_spread=0.3), steps=300).run()` devuelve un resultado con `.final_pnl` y `.max_inventory`.",
         "solution": "res = MMSimulation(MarketMaker('BTC', half_spread=0.3), steps=300).run()\npnl = res.final_pnl\nmax_inv = res.max_inventory"},
    ],
    "aux": [
        {"section": "Gimnasio · Calentamiento — repaso exprés de L12",
         "blurb": "Pesos y precio medio, en dos reps antes de cambiar de bando."},
        {"title": "C1. Pesos exprés", "practice": "repaso: normalizar",
         "statement": "Normaliza `[2, 1, 1]` en `w`.",
         "given": "raw = [2, 1, 1]\n",
         "starter": "w = None\n",
         "validator": "assert abs(sum(w) - 1.0) < 1e-9 and abs(w[0] - 0.5) < 1e-9\nprint('ok')",
         "solution": "w = [x / sum(raw) for x in raw]"},
        {"title": "C2. Precio medio exprés", "practice": "repaso: media ponderada",
         "statement": "`fills = [(99.4, 0.1), (100.6, 0.1)]` — calcula `avg`.",
         "given": "fills = [(99.4, 0.1), (100.6, 0.1)]\n",
         "starter": "avg = None\n",
         "validator": "assert abs(avg - 100.0) < 1e-9\nprint('ok')",
         "solution": "avg = sum(p * s for p, s in fills) / sum(s for p, s in fills)"},

        {"section": "Gimnasio · Bloque 1 — Cotizar e inventario",
         "blurb": "Quotes, skew y el spread cobrado: la mecánica del market maker."},
        {"title": "A1. Tus primeras quotes", "practice": "MarketMaker.quotes",
         "statement": "Crea un `MarketMaker('SIM', half_spread=0.6)` y pídele quotes sobre el libro dado. Guarda `(bid_px, ask_px)`.",
         "given": "from exchange.book import Level, OrderBook\nfrom exchange.strategies.market_maker import MarketMaker\nbook = OrderBook('SIM', [Level(99.5, 1.0)], [Level(100.5, 1.0)])\n",
         "starter": "bid_px = None\nask_px = None\n",
         "validator": "assert abs(bid_px - 99.4) < 1e-9 and abs(ask_px - 100.6) < 1e-9\nprint('ok')",
         "solution": "mm = MarketMaker('SIM', half_spread=0.6)\nbid_px, ask_px = mm.quotes(book)"},
        {"title": "A2. El spread de una vuelta", "practice": "el negocio en un número",
         "statement": "Te ejecutan el bid (compras 0.1 a 99.4) y luego el ask (vendes 0.1 a 100.6). Calcula `ganancia`.",
         "starter": "ganancia = None\n",
         "validator": "assert abs(ganancia - 0.12) < 1e-9, 'el spread entero por el tamano'\nprint('ok')",
         "solution": "ganancia = -99.4 * 0.1 + 100.6 * 0.1"},
        {"title": "A3. El skew en acción", "practice": "reservation_price",
         "statement": "Con `inventory_skew=2.0` e inventario +0.3, calcula el reservation price del MarketMaker sobre mid 100. Guarda `r`.",
         "given": "from exchange.strategies.market_maker import MarketMaker\nmm = MarketMaker('SIM', half_spread=0.6, inventory_skew=2.0)\nmm._inventory = 0.3\n",
         "starter": "r = None\n",
         "validator": "assert abs(r - 99.4) < 1e-9, 'largo -> el centro baja'\nassert abs(r - mm.reservation_price(100.0)) < 1e-9\nprint('ok')",
         "solution": "r = mm.reservation_price(100.0)"},
        {"title": "A4. El signo de la correa", "practice": "corto → r sube",
         "statement": "Mismo MarketMaker pero CORTO (inventario −0.5). Guarda `r` y `sube` (True si r queda por encima del mid).",
         "given": "from exchange.strategies.market_maker import MarketMaker\nmm = MarketMaker('SIM', half_spread=0.6, inventory_skew=2.0)\nmm._inventory = -0.5\n",
         "starter": "r = None\nsube = None\n",
         "validator": "assert abs(r - 101.0) < 1e-9\nassert sube is True, 'corto -> cotizas mas arriba para recomprar'\nprint('ok')",
         "solution": "r = mm.reservation_price(100.0)\nsube = r > 100.0"},
        {"title": "A5. La simulación en corto", "practice": "MMSimulation",
         "statement": "Corre `MMSimulation` 50 pasos con tu MarketMaker (seed=1) y guarda `res`. Comprueba que hay 50 puntos de PnL.",
         "given": "from exchange.simulation import MMSimulation\nfrom exchange.strategies.market_maker import MarketMaker\nmm = MarketMaker('SIM', quote_size=0.1, half_spread=0.6, inventory_skew=2.0)\n",
         "starter": "res = None\n",
         "validator": "assert len(res.pnl) == 50\nassert res.max_inventory >= 0\nprint(f'ok  pnl={res.final_pnl:.2f} maxInv={res.max_inventory:.2f}')",
         "solution": "res = MMSimulation(mm, steps=50, seed=1).run()"},

        {"section": "Para terminar — profundización",
         "blurb": "La utilidad CARA: de dónde saldrá el gamma de mañana."},
        {"title": "A6. Utilidad CARA", "practice": "aversión al riesgo",
         "statement": "Escribe `cara_utility(wealth, gamma)` = -exp(-gamma * wealth). Más gamma = más aversión. Comprueba que es creciente en wealth.",
         "starter": "import math\ndef cara_utility(wealth, gamma):\n    pass\n",
         "validator": "assert cara_utility(10, 0.1) > cara_utility(5, 0.1)\nprint('ok')",
         "solution": "import math\ndef cara_utility(wealth, gamma):\n    return -math.exp(-gamma * wealth)"},
    ],
})

# ---------------------------------------------------------------------------
# L14 — Avellaneda-Stoikov (modelo + simulación)
# ---------------------------------------------------------------------------
LESSONS.append({
    "n": 14, "slug": "14-avellaneda-stoikov",
    "title": "Avellaneda-Stoikov — modelo y simulación",
    "piece": "AvellanedaStoikov: reservation price, optimal spread y barridos de gamma",
    "objective": "Sustituir el skew heurístico por el resultado del modelo de Avellaneda-Stoikov (reservation price + optimal spread), y ponerlo a correr: simular, ver cómo controla el inventario y barrer gamma.",
    "frase": "El reservation price inclina según inventario y tiempo; el optimal spread cobra por el riesgo. Más gamma = más defensivo, menos inventario, menos PnL.",
    "concepts": [
        ("De dónde sale el modelo",
         "Maximizas utilidad CARA sobre tu riqueza final con inventario incierto. La solución (vía HJB) da dos fórmulas cerradas.",
         "r = s - q*gamma*sigma^2*(T-t)\nd = gamma*sigma^2*(T-t) + (2/gamma)*ln(1+gamma/kappa)"),
        ("Reservation price y optimal spread",
         "r es el mid ajustado por inventario y tiempo; d es cuánto separas las cotizaciones. Al cierre, el ajuste por inventario se apaga.",
         "bid = r - d/2\nask = r + d/2"),
        ("Simular y barrer gamma",
         "MMSimulation mueve el mid y te ejecuta según la distancia. Más gamma controla mejor el inventario, pero captura menos spread. No hay free lunch.",
         "for gamma in [0.05, 0.2, 0.8]: simula"),
    ],
    "build": [
        {"title": "1. Reservation price con inventario", "practice": "fórmula r",
         "statement": "Crea `AvellanedaStoikov('BTC', horizon=500)`, fija `_inventory=3`, `_t=0`. Guarda `r = reservation_price(100)`. Debe ser < 100.",
         "given": "from exchange.strategies import AvellanedaStoikov\nstrat = AvellanedaStoikov('BTC', gamma=0.1, sigma=10, kappa=1.5, horizon=500)\nstrat._inventory = 3\nstrat._t = 0\n",
         "starter": "r = None\n",
         "validator": "assert r < 100, 'inventario largo -> r por debajo del mid'\nprint('ok  r=%.2f' % r)",
         "solution": "r = strat.reservation_price(100)"},
        {"title": "2. Optimal spread positivo", "practice": "fórmula d",
         "statement": "Guarda `d = strat.optimal_spread()`. Debe ser positivo.",
         "given": "from exchange.strategies import AvellanedaStoikov\nstrat = AvellanedaStoikov('BTC', gamma=0.1, sigma=10, kappa=1.5, horizon=500)\nstrat._t = 0\n",
         "starter": "d = None\n",
         "validator": "assert d > 0, 'el spread óptimo es positivo'\nprint('ok  d=%.4f' % d)",
         "solution": "d = strat.optimal_spread()"},
        {"title": "3. Cotizaciones A-S", "practice": "quotes simétricas en torno a r",
         "statement": "Con inventario 0, las cotizaciones deben estar centradas en el mid. Guarda `bid`, `ask` con un libro de mid 100.",
         "given": "from exchange import OrderBook, Level\nfrom exchange.strategies import AvellanedaStoikov\nstrat = AvellanedaStoikov('BTC', gamma=0.1, sigma=10, kappa=1.5, horizon=500)\nstrat._t = 0\nbook = OrderBook('BTC', [Level(99.5,1)], [Level(100.5,1)])\n",
         "starter": "bid = None\nask = None\n",
         "validator": "assert bid < 100 < ask\nassert abs((bid + ask)/2 - 100) < 1e-6, 'inventario 0 -> centradas en el mid'\nprint('ok  bid=%.3f ask=%.3f' % (bid, ask))",
         "solution": "bid, ask = strat.quotes(book)"},
        {"title": "4. Inventario inclina el centro", "practice": "A-S vs naive",
         "statement": "Con `_inventory=5`, el centro `(bid+ask)/2` debe quedar por debajo del mid (inclina para soltar). Guarda `center`.",
         "given": "from exchange import OrderBook, Level\nfrom exchange.strategies import AvellanedaStoikov\nstrat = AvellanedaStoikov('BTC', gamma=0.1, sigma=10, kappa=1.5, horizon=500)\nstrat._t = 0\nstrat._inventory = 5\nbook = OrderBook('BTC', [Level(99.5,1)], [Level(100.5,1)])\n",
         "starter": "center = None\n",
         "validator": "assert center < 100, 'largo -> centro por debajo del mid'\nprint('ok  center=%.2f' % center)",
         "solution": "bid, ask = strat.quotes(book)\ncenter = (bid + ask) / 2"},
        {"title": "5. Simula el A-S", "practice": "MMSimulation con A-S",
         "statement": "Simula `AvellanedaStoikov('BTC', gamma=0.1, sigma=0.5, horizon=400)` con `steps=400`. Guarda `max_inv` y `pnl`.",
         "given": "from exchange.strategies import AvellanedaStoikov\nfrom exchange.simulation import MMSimulation\n",
         "starter": "max_inv = None\npnl = None\n",
         "validator": "assert max_inv >= 0 and isinstance(pnl, float)\nprint('ok  max|inv|=%.2f pnl=%.2f' % (max_inv, pnl))",
         "pista": "Mismo patrón que la simulación de L13, cambiando la estrategia: `MMSimulation(AvellanedaStoikov('BTC', gamma=0.1, sigma=0.5, horizon=400), steps=400).run()`.",
         "solution": "res = MMSimulation(AvellanedaStoikov('BTC', gamma=0.1, sigma=0.5, horizon=400), steps=400).run()\nmax_inv = res.max_inventory\npnl = res.final_pnl"},
        {"title": "6. El skew reduce el inventario", "practice": "comparar con / sin skew",
         "statement": "Con la misma semilla, simula un MarketMaker con skew (2.0) y otro sin skew (0.0), half_spread 0.3. Guarda `inv_skew` e `inv_noskew` (max inventario). El skew debe dejar menos inventario.",
         "given": "from exchange.strategies import MarketMaker\nfrom exchange.simulation import MMSimulation\n",
         "starter": "inv_skew = None\ninv_noskew = None\n",
         "validator": "assert inv_skew <= inv_noskew + 1e-9, 'el skew empuja el inventario hacia 0'\nprint('ok  skew=%.3f noskew=%.3f' % (inv_skew, inv_noskew))",
         "pista": "Dos simulaciones que solo difieren en `inventory_skew` (2.0 frente a 0.0). De cada `run()` te quedas con `.max_inventory`.",
         "solution": "inv_skew = MMSimulation(MarketMaker('BTC', half_spread=0.3, inventory_skew=2.0), steps=400).run().max_inventory\ninv_noskew = MMSimulation(MarketMaker('BTC', half_spread=0.3, inventory_skew=0.0), steps=400).run().max_inventory"},
        {"title": "7. Más gamma, más inclina el reservation price", "practice": "trade-off riesgo/PnL",
         "statement": "Con inventario fijo (5), mide cuánto se aleja el reservation price del mid para gamma 0.05 y 0.8. Guarda `skew_low_gamma` y `skew_high_gamma` (= |r - mid|).",
         "given": "from exchange.strategies import AvellanedaStoikov\ndef skew_mag(g):\n    s = AvellanedaStoikov('BTC', gamma=g, sigma=10, kappa=1.5, horizon=500)\n    s._inventory = 5; s._t = 0\n    return abs(s.reservation_price(100) - 100)\n",
         "starter": "skew_low_gamma = None\nskew_high_gamma = None\n",
         "validator": "assert skew_high_gamma > skew_low_gamma, 'más gamma = más aversión = más inclinación'\nprint('ok  g=0.05 -> %.1f | g=0.8 -> %.1f' % (skew_low_gamma, skew_high_gamma))",
         "pista": "`skew_mag` ya viene definida en el given: recibe una gamma y devuelve `|r − mid|` con inventario 5. Llámala dos veces.",
         "solution": "skew_low_gamma = skew_mag(0.05)\nskew_high_gamma = skew_mag(0.8)"},
    ],
    "aux": [
        {"section": "Gimnasio · Calentamiento — repaso exprés de L13",
         "blurb": "Reservation y la vuelta completa, antes del modelo."},
        {"title": "C1. Reservation exprés", "practice": "repaso: skew naive",
         "statement": "mid 100, skew 2.0, inventario +0.4 → calcula `r`.",
         "starter": "r = None\n",
         "validator": "assert abs(r - 99.2) < 1e-9\nprint('ok')",
         "solution": "r = 100 - 2.0 * 0.4"},
        {"title": "C2. La vuelta exprés", "practice": "repaso: el spread cobrado",
         "statement": "Bid 99.4 y ask 100.6, tamaño 0.2 por lado, ida y vuelta completa → `ganancia`.",
         "starter": "ganancia = None\n",
         "validator": "assert abs(ganancia - 0.24) < 1e-9\nprint('ok')",
         "solution": "ganancia = (100.6 - 99.4) * 0.2"},

        {"section": "Gimnasio · Bloque 1 — Las fórmulas, con las manos",
         "blurb": "Reservation, optimal spread y el papel de cada letra."},
        {"title": "A1. Reservation A-S a mano", "practice": "r = mid − q·γ·σ²·τ",
         "statement": "Con mid=100, q=1, γ=0.5, σ=0.5 y τ=1, calcula `r`.",
         "starter": "r = None\n",
         "validator": "assert abs(r - 99.875) < 1e-9\nprint('ok')",
         "solution": "r = 100 - 1 * 0.5 * 0.5**2 * 1"},
        {"title": "A2. Optimal spread a mano", "practice": "δ = γσ²τ + (2/γ)ln(1+γ/κ)",
         "statement": "Con γ=0.5, σ=0.5, τ=1 y κ=1.5, calcula `d` (usa `math.log`).",
         "given": "import math\n",
         "starter": "d = None\n",
         "validator": "assert abs(d - 1.2757) < 1e-3\nprint(f'ok  d={d:.4f}')",
         "solution": "gamma, sigma, tau, kappa = 0.5, 0.5, 1, 1.5\nd = gamma * sigma**2 * tau + (2 / gamma) * math.log(1 + gamma / kappa)"},
        {"title": "A3. γ manda en el miedo", "practice": "sensibilidad al inventario",
         "statement": "Con q=1, σ=0.5, τ=1: calcula el desplazamiento del reservation (|mid−r|) para γ=0.1 y γ=1.0. Guarda `shift_g01`, `shift_g10` y `mas_miedo_mas_skew` (True/False).",
         "starter": "shift_g01 = None\nshift_g10 = None\nmas_miedo_mas_skew = None\n",
         "validator": "assert abs(shift_g01 - 0.025) < 1e-9\nassert abs(shift_g10 - 0.25) < 1e-9\nassert mas_miedo_mas_skew is True\nprint('ok')",
         "solution": "shift_g01 = 1 * 0.1 * 0.25 * 1\nshift_g10 = 1 * 1.0 * 0.25 * 1\nmas_miedo_mas_skew = shift_g10 > shift_g01"},
        {"title": "A4. El reloj lo apaga", "practice": "τ = 0",
         "statement": "Crea un `AvellanedaStoikov(horizon=100)`, ponle inventario +1 y avanza su reloj hasta el final (`mm._t = 100`). Comprueba que `reservation_price(100.0)` vuelve al mid.",
         "given": "from exchange.strategies.market_maker import AvellanedaStoikov\nmm = AvellanedaStoikov('SIM', gamma=0.5, sigma=0.5, horizon=100)\nmm._inventory = 1.0\n",
         "starter": "r_final = None\n",
         "validator": "assert abs(r_final - 100.0) < 1e-9, 'tau=0 apaga el termino de inventario'\nprint('ok — se acabo el partido, suelta el skew')",
         "solution": "mm._t = 100\nr_final = mm.reservation_price(100.0)"},
        {"title": "A5. El barrido de γ, tuyo", "practice": "la frontera riesgo/retorno",
         "statement": "Corre `MMSimulation` (50 pasos, seed=3) con γ=0.1 y γ=1.0 y guarda `(inv_low, inv_high)`: el inventario máximo de cada una. ¿Quién controla más?",
         "given": "from exchange.simulation import MMSimulation\nfrom exchange.strategies.market_maker import AvellanedaStoikov\n\ndef corre(gamma):\n    mm = AvellanedaStoikov('SIM', quote_size=0.1, gamma=gamma, sigma=0.5, horizon=50)\n    return MMSimulation(mm, steps=50, seed=3).run()\n",
         "starter": "inv_low = None\ninv_high = None\n",
         "validator": "assert inv_low >= inv_high, 'mas gamma = menos inventario maximo (o igual)'\nprint(f'ok  g=0.1 -> {inv_low:.2f} | g=1.0 -> {inv_high:.2f}')",
         "solution": "inv_low = corre(0.1).max_inventory\ninv_high = corre(1.0).max_inventory"},

        {"section": "Para terminar — profundización",
         "blurb": "El decaimiento temporal completo y TU market maker — la plantilla del examen."},
        {"title": "A6. El tiempo apaga el ajuste", "practice": "decaimiento temporal",
         "statement": "El término de inventario se hace 0 al cierre. Guarda `r_start` (t=0) y `r_end` (t=horizon) con inventario 5: r_end debe estar más cerca del mid.",
         "starter": "from exchange.strategies import AvellanedaStoikov\nr_start = None\nr_end = None\n",
         "validator": "assert abs(r_end - 100) < abs(r_start - 100), 'al cierre, r vuelve al mid'\nprint('ok  r_start=%.2f r_end=%.2f' % (r_start, r_end))",
         "solution": "from exchange.strategies import AvellanedaStoikov\ns = AvellanedaStoikov('BTC', gamma=0.1, sigma=10, kappa=1.5, horizon=500)\ns._inventory = 5\ns._t = 0;   r_start = s.reservation_price(100)\ns._t = 500; r_end = s.reservation_price(100)"},
        {"title": "A7. Tu propio market maker", "practice": "subclasear MarketMaker",
         "statement": "Crea `FlatMaker(MarketMaker)` que cotice siempre simétrico al mid (sin skew): override `reservation_price` para devolver el mid. Simúlalo y guarda `max_inv`.",
         "starter": "from exchange.strategies import MarketMaker\nfrom exchange.simulation import MMSimulation\nclass FlatMaker(MarketMaker):\n    def reservation_price(self, mid):\n        pass\nmax_inv = None\n",
         "validator": "assert max_inv is not None\nprint('ok — has escrito tu propia estrategia y la has enchufado al simulador')",
         "solution": "from exchange.strategies import MarketMaker\nfrom exchange.simulation import MMSimulation\nclass FlatMaker(MarketMaker):\n    def reservation_price(self, mid):\n        return mid\nmax_inv = MMSimulation(FlatMaker('BTC', half_spread=0.3), steps=400).run().max_inventory"},

        {"section": "Transferencia — la misma idea, otro dominio",
         "blurb": "La γ de Avellaneda-Stoikov es aversión al riesgo: cuánto castigas la incertidumbre. "
                  "Esa misma idea es la que decide cuánto pagarías por un seguro. Sin mercado, misma fórmula."},
        {"title": "T1. Cuánto pagas por dormir tranquilo (la γ, fuera del mercado)",
         "practice": "aversión al riesgo fuera del trading",
         "statement": "El reservation price de A-S es `mid − γ·(riesgo)`: al valor justo le restas un castigo "
                       "proporcional a tu aversión γ. En seguros es idéntico: el **equivalente de certeza** "
                       "de una apuesta incierta es `media − γ·varianza`. Escribe "
                       "`equiv_certeza(media, gamma, var)` y guarda `barato` (γ=0.1) y `caro` (γ=2.0) "
                       "para media 100 y varianza 30. El más averso al riesgo la valora MÁS bajo "
                       "(y por tanto pagaría más por asegurarse).",
         "given": "",
         "starter": "def equiv_certeza(media, gamma, var):\n    pass\nbarato = None\ncaro = None\n",
         "validator": "assert abs(equiv_certeza(100, 0.1, 30) - 97) < 1e-9\nassert caro < barato, 'más aversión (γ alta) = valoras más bajo lo incierto = pagas más por el seguro'\nprint('ok — la γ de Avellaneda-Stoikov era aversión al riesgo; el seguro usa la misma resta')",
         "pista": "La función es una sola resta: `return media - gamma * var`. Es la misma forma que "
                  "`reservation_price = mid - gamma * sigma**2 * inventory`, con `var` haciendo de riesgo.",
         "solution": "def equiv_certeza(media, gamma, var):\n    return media - gamma * var\nbarato = equiv_certeza(100, 0.1, 30)\ncaro = equiv_certeza(100, 2.0, 30)"},
    ],
})
