"""Specs de las lecciones del motor y framework (L5-L9).

A partir de aquí los ejercicios usan el paquete `exchange` que el alumno ha ido
construyendo. Market.sample() da 500 snapshots de BTCUSDT sin configurar rutas.
"""

LESSONS = []

# ---------------------------------------------------------------------------
# L5 — Microstructure — Leer el libro
# ---------------------------------------------------------------------------
LESSONS.append({
    "n": 7, "slug": "07-microstructure-reading-book",
    "title": "Microestructura — Leer el libro",
    "piece": "métricas de mercado sobre snapshots reales de BTC",
    "objective": "Cargar 500 snapshots reales de BTCUSDT y leer el mercado: spread, mid, imbalance, microprice y profundidad. El OrderBook deja de ser una foto y se vuelve una lente.",
    "frase": "El imbalance y el microprice te dicen hacia dónde empuja el libro antes de que se mueva el mid.",
    "concepts": [
        ("El libro como lente",
         "Cargas un snapshot y el OrderBook te da spread y mid en una línea. Pero lo interesante está más adentro: cuánta liquidez hay, y de qué lado.",
         "from exchange import Market\nm = Market.sample()\nbook = m.step()\nbook.spread, book.mid"),
        ("Imbalance: presión del libro",
         "Más tamaño en bids que en asks (imbalance > 0) suele preceder subidas de mid. Es una de las señales más usadas en microestructura.",
         "book.imbalance(levels=1)   # nivel 1\nbook.imbalance(levels=5)   # 5 niveles"),
        ("Microprice y profundidad",
         "El microprice pondera el mid por el tamaño contrario: mejor predictor a corto que el mid simple. La profundidad mide cuánto aguanta el libro un golpe.",
         "book.microprice\nbook.depth(Side.BUY, levels=5)"),
    ],
    "build": [
        {"title": "1. Carga el mercado", "practice": "Market.sample y step",
         "statement": "Crea `m = Market.sample()` y avanza un snapshot: `book = m.step()`. Guarda `n = len(m)`.",
         "starter": "from exchange import Market\n# m, book, n\n",
         "validator": "from exchange import OrderBook\nassert n == 500, 'deben ser 500 snapshots'\nassert isinstance(book, OrderBook)\nprint('ok')",
         "solution": "from exchange import Market\nm = Market.sample()\nbook = m.step()\nn = len(m)"},
        {"title": "2. Spread y mid del primer snapshot", "practice": "propiedades del libro",
         "statement": "Del `book`, guarda `spread` y `mid`.",
         "given": "from exchange import Market\nbook = Market.sample().step()\n",
         "starter": "spread = None\nmid = None\n",
         "validator": "assert spread > 0, 'el spread debe ser positivo'\nassert book.best_bid < mid < book.best_ask\nprint('ok  spread=%.2f mid=%.2f' % (spread, mid))",
         "solution": "spread = book.spread\nmid = book.mid"},
        {"title": "3. Imbalance a 1 y 5 niveles", "practice": "imbalance(levels)",
         "statement": "Guarda `imb1 = book.imbalance(1)` e `imb5 = book.imbalance(5)`. Ambos en [-1, 1].",
         "given": "from exchange import Market\nbook = Market.sample().step()\n",
         "starter": "imb1 = None\nimb5 = None\n",
         "validator": "assert -1 <= imb1 <= 1 and -1 <= imb5 <= 1\nprint('ok  imb1=%.3f imb5=%.3f' % (imb1, imb5))",
         "solution": "imb1 = book.imbalance(1)\nimb5 = book.imbalance(5)"},
        {"title": "4. Microprice", "practice": "microprice",
         "statement": "Guarda `micro = book.microprice`. Debe caer entre best_bid y best_ask.",
         "given": "from exchange import Market\nbook = Market.sample().step()\n",
         "starter": "micro = None\n",
         "validator": "assert book.best_bid <= micro <= book.best_ask\nprint('ok  micro=%.2f mid=%.2f' % (micro, book.mid))",
         "solution": "micro = book.microprice"},
        {"title": "5. Profundidad por lado", "practice": "depth(side, levels)",
         "statement": "Importa `Side` y guarda `bid_depth` y `ask_depth` sumando 5 niveles de cada lado.",
         "given": "from exchange import Market\nbook = Market.sample().step()\n",
         "starter": "from exchange import Side\nbid_depth = None\nask_depth = None\n",
         "validator": "assert bid_depth > 0 and ask_depth > 0\nprint('ok  bid=%.2f ask=%.2f' % (bid_depth, ask_depth))",
         "pista": "La firma es `book.depth(side, niveles)`; los lados son `Side.BUY` y `Side.SELL` del enum que acabas de importar.",
         "solution": "from exchange import Side\nbid_depth = book.depth(Side.BUY, 5)\nask_depth = book.depth(Side.SELL, 5)"},
    ],
    "aux": [
        {"section": "Gimnasio · Calentamiento — repaso exprés de L6",
         "blurb": "Herencia y polimorfismo en dos reps antes de tocar datos reales."},
        {"title": "C1. Override exprés", "practice": "repaso: herencia",
         "statement": "Con la base dada, escribe `Alcista(Strategy)` cuyo `decide` devuelva siempre `'buy'`.",
         "given": "class Strategy:\n    def decide(self, imbalance):\n        return 'hold'\n",
         "starter": "a = None\n",
         "validator": "assert a.decide(-1) == 'buy'\nprint('ok')",
         "solution": "class Alcista(Strategy):\n    def decide(self, imbalance):\n        return 'buy'\n\na = Alcista()"},
        {"title": "C2. El bucle exprés", "practice": "repaso: polimorfismo",
         "statement": "Recorre `familia` llamando `decide(0.5)` y guarda las respuestas en `res`.",
         "given": "class Strategy:\n    def decide(self, imbalance):\n        return 'hold'\nclass Alcista(Strategy):\n    def decide(self, imbalance):\n        return 'buy'\nfamilia = [Strategy(), Alcista()]\n",
         "starter": "res = None\n",
         "validator": "assert res == ['hold', 'buy']\nprint('ok')",
         "solution": "res = [s.decide(0.5) for s in familia]"},

        {"section": "Gimnasio · Bloque 1 — Leer el libro real",
         "blurb": "Las lentes de la clase, aplicadas a los 500 snapshots de verdad."},
        {"title": "A1. La primera foto", "practice": "Market.sample + métricas",
         "statement": "Carga `Market.sample()`, avanza un paso y guarda `spread0` y `mid0` del libro.",
         "given": "from exchange.market import Market\n",
         "starter": "spread0 = None\nmid0 = None\n",
         "validator": "m = Market.sample(); b = m.step()\nassert abs(spread0 - b.spread) < 1e-9\nassert abs(mid0 - b.mid) < 1e-9\nprint('ok ->', spread0, mid0)",
         "solution": "m = Market.sample()\nbook = m.step()\nspread0 = book.spread\nmid0 = book.mid"},
        {"title": "A2. Dos imbalances, dos historias", "practice": "imbalance(levels)",
         "statement": "Sobre el primer snapshot, guarda `im1 = book.imbalance(1)` e `im5 = book.imbalance(5)`.",
         "given": "from exchange.market import Market\nbook = Market.sample().step()\n",
         "starter": "im1 = None\nim5 = None\n",
         "validator": "assert -1 <= im1 <= 1 and -1 <= im5 <= 1\nassert abs(im1 - book.imbalance(1)) < 1e-9\nprint(f'ok  im1={im1:.3f} im5={im5:.3f}')",
         "solution": "im1 = book.imbalance(1)\nim5 = book.imbalance(5)"},
        {"title": "A3. La inclinación del microprice", "practice": "microprice vs mid",
         "statement": "Guarda `tilt = book.microprice - book.mid`. Su signo dice hacia dónde se inclina el libro.",
         "given": "from exchange.market import Market\nbook = Market.sample().step()\n",
         "starter": "tilt = None\n",
         "validator": "assert abs(tilt) < book.spread, 'el microprice vive dentro del spread'\nassert abs(tilt - (book.microprice - book.mid)) < 1e-9\nprint(f'ok  tilt={tilt:.3f}')",
         "solution": "tilt = book.microprice - book.mid"},
        {"title": "A4. depth, comprobada a mano", "practice": "depth vs suma manual",
         "statement": "Calcula `d3 = book.depth(Side.BUY, 3)` y comprueba que coincide con sumar a mano los 3 primeros bids en `manual`.",
         "given": "from exchange.market import Market\nfrom exchange.orders import Side\nbook = Market.sample().step()\n",
         "starter": "d3 = None\nmanual = None\n",
         "validator": "assert abs(d3 - manual) < 1e-9, 'depth es exactamente esa suma'\nprint(f'ok  d3={d3:.3f}')",
         "solution": "d3 = book.depth(Side.BUY, 3)\nmanual = sum(lv.size for lv in book.bids[:3])"},
        {"title": "A5. El techo del día", "practice": "recorrer los 500",
         "statement": "Recorre TODO el mercado con `step()` y guarda `high` (el mid más alto del día).",
         "given": "from exchange.market import Market\nm = Market.sample()\n",
         "starter": "high = None\n",
         "validator": "m2 = Market.sample(); mids = []\nwhile m2.step() is not None:\n    mids.append(m2.book.mid)\nassert abs(high - max(mids)) < 1e-9\nprint(f'ok  high={high}')",
         "solution": "high = None\nwhile m.step() is not None:\n    if high is None or m.book.mid > high:\n        high = m.book.mid"},

        {"section": "Para terminar — profundización",
         "blurb": "El spread medio de la sesión y la pregunta de si el imbalance predice."},
        {"title": "A6. Spread medio de la sesión", "practice": "recorrer el mercado",
         "statement": "Recorre todos los snapshots y guarda `avg_spread`, la media del spread.",
         "starter": "from exchange import Market\nm = Market.sample()\navg_spread = None\n",
         "validator": "assert avg_spread > 0\nprint('ok  avg_spread=%.2f' % avg_spread)",
         "solution": "from exchange import Market\nm = Market.sample()\nspreads = []\nwhile True:\n    b = m.step()\n    if b is None: break\n    spreads.append(b.spread)\navg_spread = sum(spreads) / len(spreads)"},
        {"title": "A7. ¿Predice el imbalance?", "practice": "señal vs siguiente mid",
         "statement": "Cuenta cuántas veces, cuando `imbalance(1) > 0`, el mid del siguiente snapshot sube. Guarda el conteo en `up_after_positive`.",
         "starter": "from exchange import Market\nm = Market.sample()\nup_after_positive = 0\n",
         "validator": "assert up_after_positive != 0, 'sigue en 0: recorre el dia comparando cada mid con el anterior'\nassert up_after_positive == 117, f'obtuviste {up_after_positive}; cuenta solo cuando imbalance(1) > 0 Y el mid del snapshot siguiente sube'\nprint('ok  veces que sube tras imbalance+:', up_after_positive)",
         "solution": "from exchange import Market\nm = Market.sample()\nprev = m.step()\nup_after_positive = 0\nwhile True:\n    cur = m.step()\n    if cur is None: break\n    if prev.imbalance(1) is not None and prev.imbalance(1) > 0 and cur.mid > prev.mid:\n        up_after_positive += 1\n    prev = cur"},
    ],
})

# ---------------------------------------------------------------------------
# L6 — Órdenes y matching
# ---------------------------------------------------------------------------
LESSONS.append({
    "n": 8, "slug": "08-order-types-matching",
    "title": "Órdenes y matching",
    "piece": "MatchingEngine: cómo se cruzan las órdenes",
    "objective": "Enviar órdenes contra el libro y ver cómo se cruzan. Market, limit, IOC y FOK: cada tipo cambia el coste, la probabilidad de ejecución y el riesgo.",
    "frase": "La forma en que envías la orden decide tu coste: cruzar ya, o esperar barato y arriesgarte a no ejecutar.",
    "concepts": [
        ("El motor de cruce",
         "MatchingEngine.process(order, book) recorre el lado contrario, consume liquidez y devuelve los fills. El libro queda modificado.",
         "from exchange import MatchingEngine\nfills = MatchingEngine().process(order, book)"),
        ("Market vs limit",
         "Una market cruza al precio que haga falta hasta llenarse (caro pero seguro). Una limit solo cruza a tu precio o mejor; el resto descansa (barato pero incierto).",
         "Order('BTC', Side.BUY, 0.5, order_type=OrderType.MARKET)\nOrder('BTC', Side.BUY, 0.5, price=100, order_type=OrderType.LIMIT)"),
        ("IOC y FOK",
         "IOC cruza lo que pueda y cancela el resto (nada descansa). FOK es todo-o-nada: si no se llena entera, no se ejecuta nada.",
         "OrderType.IOC   # immediate-or-cancel\nOrderType.FOK   # fill-or-kill"),
    ],
    "build": [
        {"title": "1. Una market order se llena", "practice": "MatchingEngine + MARKET",
         "statement": "Cruza una market buy de 0.5 contra el primer snapshot. Guarda `fills` y `filled` (suma de tamaños).",
         "given": "from exchange import Market, MatchingEngine, Order, Side, OrderType\nbook = Market.sample().step()\neng = MatchingEngine()\n",
         "starter": "fills = None\nfilled = None\n",
         "validator": "assert abs(filled - 0.5) < 1e-9, 'una market siempre se llena si hay liquidez'\nassert all(f.side == Side.BUY for f in fills)\nprint('ok  fills=%d' % len(fills))",
         "solution": "order = Order('BTCUSDT', Side.BUY, 0.5, order_type=OrderType.MARKET)\nfills = eng.process(order, book)\nfilled = sum(f.size for f in fills)"},
        {"title": "2. Una limit cruza solo a su precio", "practice": "LIMIT + remanente",
         "statement": "Envía una limit buy enorme (size=999) al `best_bid` actual. No debería cruzar nada (precio por debajo del ask). Guarda `n_fills`.",
         "given": "from exchange import Market, MatchingEngine, Order, Side, OrderType\nbook = Market.sample().step()\neng = MatchingEngine()\nbb = book.best_bid\n",
         "starter": "n_fills = None\n",
         "validator": "assert n_fills == 0, 'comprar al best_bid no cruza el ask'\nprint('ok')",
         "solution": "order = Order('BTCUSDT', Side.BUY, 999, price=bb, order_type=OrderType.LIMIT)\nfills = eng.process(order, book)\nn_fills = len(fills)"},
        {"title": "3. Una market crossing limit sí cruza", "practice": "limit marketable",
         "statement": "Envía una limit buy de 0.3 a un precio por encima del `best_ask` (best_ask + 100). Cruza. Guarda `filled`.",
         "given": "from exchange import Market, MatchingEngine, Order, Side, OrderType\nbook = Market.sample().step()\neng = MatchingEngine()\nba = book.best_ask\n",
         "starter": "filled = None\n",
         "validator": "assert abs(filled - 0.3) < 1e-9\nprint('ok')",
         "pista": "Calcula el precio límite desde la variable dada: `price=ba+100`, con `order_type=OrderType.LIMIT`. Después, `filled` suma `f.size` de los fills que devuelve `eng.process(order, book)`.",
         "solution": "order = Order('BTCUSDT', Side.BUY, 0.3, price=ba+100, order_type=OrderType.LIMIT)\nfills = eng.process(order, book)\nfilled = sum(f.size for f in fills)"},
        {"title": "4. FOK: todo o nada", "practice": "OrderType.FOK",
         "statement": "Envía una FOK buy de tamaño 9999 (más de lo que hay) a precio muy alto. Debe devolver 0 fills. Guarda `n_fills`.",
         "given": "from exchange import Market, MatchingEngine, Order, Side, OrderType\nbook = Market.sample().step()\neng = MatchingEngine()\nba = book.best_ask\n",
         "starter": "n_fills = None\n",
         "validator": "assert n_fills == 0, 'FOK no se llena entera -> 0 fills'\nprint('ok')",
         "pista": "Construye la orden con `order_type=OrderType.FOK` y tamaño 9999. Como no hay liquidez para todo, `eng.process` devuelve una lista vacía — `n_fills = len(fills)`.",
         "solution": "order = Order('BTCUSDT', Side.BUY, 9999, price=ba+1000, order_type=OrderType.FOK)\nfills = eng.process(order, book)\nn_fills = len(fills)"},
        {"title": "5. Precio efectivo de una market", "practice": "vwap de los fills",
         "statement": "Cruza una market buy de 1.0 y calcula `eff_price` = nocional total / tamaño total. Debe ser >= best_ask (pagas el barrido).",
         "given": "from exchange import Market, MatchingEngine, Order, Side, OrderType\nbook = Market.sample().step()\nba = book.best_ask\neng = MatchingEngine()\n",
         "starter": "eff_price = None\n",
         "validator": "assert eff_price >= ba - 1e-6, 'una market barre niveles: precio efectivo >= best_ask'\nprint('ok  eff=%.2f best_ask=%.2f' % (eff_price, ba))",
         "pista": "Una market no lleva `price`. El precio efectivo pondera cada fill: `sum(f.price*f.size for f in fills) / sum(f.size for f in fills)`.",
         "solution": "order = Order('BTCUSDT', Side.BUY, 1.0, order_type=OrderType.MARKET)\nfills = eng.process(order, book)\neff_price = sum(f.price*f.size for f in fills) / sum(f.size for f in fills)"},
    ],
    "aux": [
        {"section": "Gimnasio · Calentamiento — repaso exprés de L7",
         "blurb": "Dos lecturas rápidas del libro real antes de dispararle."},
        {"title": "C1. Foto exprés", "practice": "repaso: mid y spread",
         "statement": "Del primer snapshot, guarda `mid0` y `spread0`.",
         "given": "from exchange.market import Market\nbook = Market.sample().step()\n",
         "starter": "mid0 = None\nspread0 = None\n",
         "validator": "assert abs(mid0 - book.mid) < 1e-9 and abs(spread0 - book.spread) < 1e-9\nprint('ok')",
         "solution": "mid0 = book.mid\nspread0 = book.spread"},
        {"title": "C2. Liquidez exprés", "practice": "repaso: depth",
         "statement": "¿Cuánto se puede comprar contra los 3 primeros asks? Guarda `d3`.",
         "given": "from exchange.market import Market\nfrom exchange.orders import Side\nbook = Market.sample().step()\n",
         "starter": "d3 = None\n",
         "validator": "assert abs(d3 - book.depth(Side.SELL, 3)) < 1e-9\nprint(f'ok  d3={d3:.3f}')",
         "solution": "d3 = book.depth(Side.SELL, 3)"},

        {"section": "Gimnasio · Bloque 1 — Fills, barridos y el peaje",
         "blurb": "La aritmética del matching, contra el motor real."},
        {"title": "A1. La orden pequeña no barre", "practice": "market vs nivel 1",
         "statement": "Envía una market buy de la MITAD del mejor ask. Comprueba que sale UN fill al precio `best_ask`. Guarda `fills`.",
         "given": "from exchange.market import Market\nfrom exchange.matching import MatchingEngine\nfrom exchange.orders import Order, OrderType\nbook = Market.sample().step()\nsize = book.asks[0].size / 2\nbest_ask_antes = book.asks[0].price  # process() consume el libro: captura antes\n",
         "starter": "fills = None\n",
         "validator": "assert len(fills) == 1, 'cabe entera en el nivel 1: un solo fill'\nassert abs(fills[0].price - best_ask_antes) < 1e-9, 'se llena AL precio del mejor ask'\nassert abs(fills[0].size - size) < 1e-9\nprint('ok ->', fills[0])",
         "solution": "engine = MatchingEngine()\nfills = engine.process(Order('BTCUSDT', 'buy', size, order_type=OrderType.MARKET), book)"},
        {"title": "A2. Precio efectivo", "practice": "media ponderada de fills",
         "statement": "Con los fills dados (tuplas precio-tamaño), calcula `eff`, el precio medio ponderado.",
         "given": "fills = [(100010.0, 0.8), (100025.0, 0.5), (100040.0, 0.7)]\n",
         "starter": "eff = None\n",
         "validator": "assert abs(eff - 100024.25) < 1e-2, 'suma p*s / suma s'\nprint(f'ok  eff={eff:.2f}')",
         "solution": "eff = sum(p * s for p, s in fills) / sum(s for p, s in fills)"},
        {"title": "A3. El slippage con signo", "practice": "eff vs mid",
         "statement": "Compraste con `eff = 100024.25` y el mid era `100000.0`. Guarda `slip` (positivo = pagaste de más) y `slip_bps`.",
         "given": "eff = 100024.25\nmid = 100000.0\n",
         "starter": "slip = None\nslip_bps = None\n",
         "validator": "assert abs(slip - 24.25) < 1e-9\nassert abs(slip_bps - 2.425) < 1e-3\nprint('ok')",
         "solution": "slip = eff - mid\nslip_bps = slip / mid * 10000"},
        {"title": "A4. El barrido, medido", "practice": "el motor contra el libro real",
         "statement": "Dispara una market buy que se coma los 2 primeros niveles ask enteros. Comprueba que salen 2 fills y guarda `eff`.",
         "given": "from exchange.market import Market\nfrom exchange.matching import MatchingEngine\nfrom exchange.orders import Order, OrderType\nbook = Market.sample().step()\nsize = book.asks[0].size + book.asks[1].size\nmid_antes = book.mid  # process() consume el libro: captura antes\n",
         "starter": "eff = None\n",
         "validator": "assert eff is not None, 'calcula el precio efectivo de los fills'\nassert eff > mid_antes, 'compras barriendo: el efectivo queda POR ENCIMA del mid'\nprint(f'ok  eff={eff:.2f}  (mid era {mid_antes:.2f})')",
         "solution": "engine = MatchingEngine()\nfills = engine.process(Order('BTCUSDT', 'buy', size, order_type=OrderType.MARKET), book)\neff = sum(f.price * f.size for f in fills) / sum(f.size for f in fills)"},
        {"title": "A5. FOK: todo o nada", "practice": "el contrato FOK",
         "statement": "Envía una FOK de compra MÁS GRANDE que toda la liquidez ask visible, a precio del último nivel. Comprueba que devuelve 0 fills y que el libro queda intacto.",
         "given": "from exchange.market import Market\nfrom exchange.matching import MatchingEngine\nfrom exchange.orders import Order, OrderType\nbook = Market.sample().step()\ntotal_ask = sum(lv.size for lv in book.asks)\nask_antes = book.best_ask\n",
         "starter": "fills = None\n",
         "validator": "assert fills == []\nassert abs(book.best_ask - ask_antes) < 1e-9, 'FOK imposible no toca el libro'\nprint('ok — todo o nada')",
         "solution": "engine = MatchingEngine()\nfills = engine.process(Order('BTCUSDT', 'buy', total_ask * 2, price=book.asks[-1].price, order_type=OrderType.FOK), book)"},

        {"section": "Para terminar — profundización",
         "blurb": "El slippage como función del tamaño, sistematizado."},
        {"title": "A6. Slippage por tamaño", "practice": "coste vs tamaño",
         "statement": "Para tamaños 0.1, 1.0 y 5.0, calcula el precio efectivo de una market buy. Guarda la lista `eff_prices`. Debe ser creciente (más tamaño, peor precio).",
         "starter": "from exchange import Market, MatchingEngine, Order, Side, OrderType\neff_prices = []\n",
         "validator": "assert len(eff_prices) == 3, '⏸ llena eff_prices con los 3 precios efectivos antes de validar'\nassert eff_prices[0] <= eff_prices[1] <= eff_prices[2], 'más tamaño = peor precio'\nprint('ok', [round(p,1) for p in eff_prices])",
         "solution": "from exchange import Market, MatchingEngine, Order, Side, OrderType\neng = MatchingEngine()\neff_prices = []\nfor size in (0.1, 1.0, 5.0):\n    book = Market.sample().step()\n    fills = eng.process(Order('BTCUSDT', Side.BUY, size, order_type=OrderType.MARKET), book)\n    eff_prices.append(sum(f.price*f.size for f in fills)/sum(f.size for f in fills))"},
    ],
})

# ---------------------------------------------------------------------------
# L7 — Loop de simulación
# ---------------------------------------------------------------------------
LESSONS.append({
    "n": 9, "slug": "09-market-simulation-loop",
    "title": "El loop de simulación",
    "piece": "Market: reproducir snapshots y ejecutar en el tiempo",
    "objective": "Poner el tiempo en marcha: recorrer los snapshots, enviar órdenes en cada paso y llevar la cuenta de caja, inventario y equity con PositionTracker.",
    "frase": "Mercado = estado (libro) + dinámica (matching) + tiempo (el loop). Todo junto, ya simulas.",
    "concepts": [
        ("step() avanza el tiempo",
         "Market.step() reconstruye el libro desde el siguiente snapshot y lo devuelve. Cuando se acaban, devuelve None. Ese es tu reloj.",
         "while True:\n    book = m.step()\n    if book is None: break\n    ..."),
        ("submit() ejecuta contra el libro actual",
         "En cada paso puedes enviar una orden: m.submit(order) la cruza contra el libro de ese instante y te devuelve los fills.",
         "fills = m.submit(order)"),
        ("PositionTracker lleva la cuenta",
         "Aplicas cada fill al tracker y en cualquier momento consultas equity(mid). Esa es tu curva de PnL.",
         "for f in fills:\n    tracker.apply_fill(f)\ntracker.equity(book.mid)"),
    ],
    "build": [
        {"title": "1. Cuenta los pasos", "practice": "el loop step()",
         "statement": "Recorre todo el mercado con un while y cuenta los snapshots en `steps`.",
         "starter": "from exchange import Market\nm = Market.sample()\nsteps = 0\n",
         "validator": "assert steps == 500\nprint('ok')",
         "solution": "from exchange import Market\nm = Market.sample()\nsteps = 0\nwhile True:\n    book = m.step()\n    if book is None: break\n    steps += 1"},
        {"title": "2. Ejecuta una orden en un paso", "practice": "submit",
         "statement": "Avanza un paso y envía una market buy de 0.2 con `m.submit(...)`. Guarda `filled`.",
         "given": "from exchange import Market, Order, Side, OrderType\nm = Market.sample()\nm.step()\n",
         "starter": "filled = None\n",
         "validator": "assert abs(filled - 0.2) < 1e-9\nprint('ok')",
         "solution": "fills = m.submit(Order('BTCUSDT', Side.BUY, 0.2, order_type=OrderType.MARKET))\nfilled = sum(f.size for f in fills)"},
        {"title": "3. Acumula posición en el tiempo", "practice": "loop + tracker",
         "statement": "Cada 50 pasos compra 0.1 (market). Aplica los fills a un `PositionTracker`. Guarda `final_pos`.",
         "given": "from exchange import Market, Order, Side, OrderType, PositionTracker\nm = Market.sample()\ntracker = PositionTracker()\n",
         "starter": "i = 0\nfinal_pos = None\n",
         "validator": "assert final_pos > 0, 'has comprado varias veces: posición larga'\nprint('ok  pos=%.2f' % final_pos)",
         "pista": "El esqueleto del loop es el del ejercicio 1 (`while True` + `m.step()` + `break` si `None`). Añade: si `i % 50 == 0`, recorre los fills de `m.submit(...)` aplicándolos al tracker. No olvides `i += 1`.",
         "solution": "i = 0\nwhile True:\n    book = m.step()\n    if book is None: break\n    if i % 50 == 0:\n        for f in m.submit(Order('BTCUSDT', Side.BUY, 0.1, order_type=OrderType.MARKET)):\n            tracker.apply_fill(f)\n    i += 1\nfinal_pos = tracker.position"},
        {"title": "4. Equity final", "practice": "marcar a mercado",
         "statement": "Continuando, marca el equity al último mid visto. Guarda `equity`.",
         "given": "from exchange import Market, Order, Side, OrderType, PositionTracker\nm = Market.sample()\ntracker = PositionTracker()\nlast_mid = 0\ni = 0\nwhile True:\n    book = m.step()\n    if book is None: break\n    last_mid = book.mid\n    if i % 50 == 0:\n        for f in m.submit(Order('BTCUSDT', Side.BUY, 0.1, order_type=OrderType.MARKET)):\n            tracker.apply_fill(f)\n    i += 1\n",
         "starter": "equity = None\n",
         "validator": "assert isinstance(equity, float)\nprint('ok  equity=%.2f' % equity)",
         "pista": "Ya lo tienes todo: `tracker.equity(last_mid)`. `last_mid` quedó guardado en el loop anterior; el tracker arrastra caja y posición.",
         "solution": "equity = tracker.equity(last_mid)"},
    ],
    "aux": [
        {"section": "Gimnasio · Calentamiento — repaso exprés de L8",
         "blurb": "Un disparo y su factura, antes de poner el tiempo en marcha."},
        {"title": "C1. Disparo exprés", "practice": "repaso: market order",
         "statement": "Contra el primer libro, envía una market buy de 0.05 con el engine y guarda `n_fills`.",
         "given": "from exchange.market import Market\nfrom exchange.matching import MatchingEngine\nfrom exchange.orders import Order, OrderType\nbook = Market.sample().step()\n",
         "starter": "n_fills = None\n",
         "validator": "assert n_fills >= 1\nprint('ok ->', n_fills)",
         "solution": "engine = MatchingEngine()\nfills = engine.process(Order('BTCUSDT', 'buy', 0.05, order_type=OrderType.MARKET), book)\nn_fills = len(fills)"},
        {"title": "C2. Factura exprés", "practice": "repaso: precio efectivo",
         "statement": "Con `fills = [(100.0, 1.0), (101.0, 1.0)]`, calcula `eff`.",
         "given": "fills = [(100.0, 1.0), (101.0, 1.0)]\n",
         "starter": "eff = None\n",
         "validator": "assert eff == 100.5\nprint('ok')",
         "solution": "eff = sum(p * s for p, s in fills) / sum(s for p, s in fills)"},

        {"section": "Gimnasio · Bloque 1 — El loop y la cuenta",
         "blurb": "step, submit, equity: el latido del backtest, drill a drill."},
        {"title": "A1. Contar el día", "practice": "el while de step()",
         "statement": "Recorre `Market.sample()` con un while y cuenta los pasos en `n`.",
         "given": "from exchange.market import Market\nm = Market.sample()\n",
         "starter": "n = 0\n",
         "validator": "assert n == 500, 'el dia tiene 500 snapshots'\nprint('ok')",
         "solution": "n = 0\nwhile m.step() is not None:\n    n = n + 1"},
        {"title": "A2. Apertura y cierre", "practice": "primer y último mid",
         "statement": "Recorre el día y guarda `first_mid` y `last_mid`.",
         "given": "from exchange.market import Market\nm = Market.sample()\n",
         "starter": "first_mid = None\nlast_mid = None\n",
         "validator": "assert first_mid is not None and last_mid is not None\nm2 = Market.sample(); b = m2.step()\nassert abs(first_mid - b.mid) < 1e-9\nprint(f'ok  {first_mid} -> {last_mid}')",
         "solution": "first_mid = None\nlast_mid = None\nwhile m.step() is not None:\n    if first_mid is None:\n        first_mid = m.book.mid\n    last_mid = m.book.mid"},
        {"title": "A3. La orden en su momento", "practice": "submit dentro del loop",
         "statement": "Avanza 10 pasos y en el 10º envía una market buy de 0.05 con `m.submit(...)`. Guarda `fills`.",
         "given": "from exchange.market import Market\nfrom exchange.orders import Order, OrderType\nm = Market.sample()\n",
         "starter": "fills = None\n",
         "validator": "assert fills and sum(f.size for f in fills) > 0\nprint('ok ->', fills[0])",
         "solution": "for _ in range(10):\n    m.step()\nfills = m.submit(Order('BTCUSDT', 'buy', 0.05, order_type=OrderType.MARKET))"},
        {"title": "A4. La cuenta tras el fill", "practice": "PositionTracker en el loop",
         "statement": "Aplica los fills dados a un `PositionTracker` y guarda `eq = tracker.equity(100000.0)`.",
         "given": "from exchange.portfolio import PositionTracker\nfrom exchange.trades import Fill\nfills = [Fill(1, 'BTCUSDT', 'buy', 99990.0, 0.1)]\n",
         "starter": "eq = None\n",
         "validator": "assert abs(eq - 1.0) < 1e-6, 'pagaste 9999, vale 10000: +1'\nprint('ok')",
         "solution": "tracker = PositionTracker()\nfor f in fills:\n    tracker.apply_fill(f)\neq = tracker.equity(100000.0)"},
        {"title": "A5. Sin posición no hay historia", "practice": "la curva plana",
         "statement": "Simula 5 pasos SIN operar, apuntando `tracker.equity(m.book.mid)` en `curva`. Comprueba que es plana en 0.",
         "given": "from exchange.market import Market\nfrom exchange.portfolio import PositionTracker\nm = Market.sample()\ntracker = PositionTracker()\n",
         "starter": "curva = []\n",
         "validator": "assert len(curva) == 5\nassert all(abs(x) < 1e-9 for x in curva), 'sin fills, el equity no se mueve'\nprint('ok — la parte plana de la curva')",
         "solution": "curva = []\nfor _ in range(5):\n    m.step()\n    curva.append(tracker.equity(m.book.mid))"},

        {"section": "Para terminar — profundización",
         "blurb": "Trocear la ejecución a lo largo del loop: la semilla del VWAP."},
        {"title": "A6. Schedule de participación", "practice": "repartir un objetivo",
         "statement": "Reparte una compra total de 1.0 en 10 trozos iguales, uno cada 50 pasos. Guarda `executed` (debe sumar ~1.0).",
         "starter": "from exchange import Market, Order, Side, OrderType, PositionTracker\nexecuted = 0.0\n",
         "validator": "assert abs(executed - 1.0) < 1e-6\nprint('ok')",
         "solution": "from exchange import Market, Order, Side, OrderType, PositionTracker\nm = Market.sample(); i = 0; executed = 0.0\nwhile True:\n    book = m.step()\n    if book is None: break\n    if i % 50 == 0 and executed < 1.0 - 1e-9:\n        for f in m.submit(Order('BTCUSDT', Side.BUY, 0.1, order_type=OrderType.MARKET)):\n            executed += f.size\n    i += 1"},

        {"section": "Transferencia — la misma idea, otro dominio",
         "blurb": "El bucle de simulación (leer estado → decidir → acumular → avanzar) no es del mercado: "
                  "es como se simula CUALQUIER sistema en el tiempo. Aquí, el consumo eléctrico de una casa."},
        {"title": "T1. El contador de la luz (mismo loop, otro sistema)",
         "practice": "bucle paso a paso fuera del trading",
         "statement": "Una casa consume, cada hora, `lecturas[i]` kWh. Recórrelas con un bucle acumulando "
                       "el total en `consumido` y, en paralelo, apuntando el acumulado en `curva` "
                       "(como la equity curve, pero de kWh). Es el mismo patrón `step → acumula → avanza`.",
         "given": "lecturas = [0.4, 0.6, 1.2, 0.9, 0.3, 0.5]\n",
         "starter": "consumido = 0.0\ncurva = []\n",
         "validator": "assert abs(consumido - 3.9) < 1e-9, 'la suma de todas las lecturas'\nassert curva == [0.4, 1.0, 2.2, 3.1, 3.4, 3.9], 'la curva es el acumulado paso a paso'\nprint('ok — un loop de simulación es un loop de simulación, venda kWh o BTC')",
         "pista": "Un solo `for x in lecturas:` que haga `consumido += x` y luego "
                  "`curva.append(consumido)`. Es la misma forma que la equity curve del ejercicio A5.",
         "solution": "consumido = 0.0\ncurva = []\nfor x in lecturas:\n    consumido += x\n    curva.append(consumido)"},
    ],
})

# ---------------------------------------------------------------------------
# L8 — Strategy + Backtest (el pico arquitectónico)
# ---------------------------------------------------------------------------
LESSONS.append({
    "n": 10, "slug": "10-strategy-framework",
    "title": "El framework: Strategy + Backtest",
    "piece": "interfaz Strategy (ABC) y el runner Backtest",
    "objective": "El corazón del curso: una estrategia solo reacciona al libro y devuelve acciones. El Backtest la cablea con el mercado y el portfolio. Cualquier estrategia se enchufa igual.",
    "frase": "Escribe una subclase de Strategy y enchúfala al mismo Backtest. Eso es polimorfismo, y es lo que hace todo modular.",
    "concepts": [
        ("La interfaz Strategy",
         "Una estrategia implementa on_book_update(book) y devuelve una lista de acciones (NewOrder/Cancel). No sabe nada del motor. Esa ignorancia es lo que la hace enchufable.",
         "class Strategy(ABC):\n    @abstractmethod\n    def on_book_update(self, book) -> list[Action]:\n        ..."),
        ("Acciones, no efectos",
         "La estrategia no ejecuta órdenes: las pide. Devuelve NewOrder(order). El Backtest decide qué hacer con ellas. Separar decisión de ejecución es la clave del diseño.",
         "return [NewOrder(Order('BTC', Side.BUY, 0.1,\n        order_type=OrderType.MARKET))]"),
        ("El Backtest lo cablea todo",
         "Recorre el mercado, pasa cada libro a la estrategia, ejecuta sus acciones contra el matching, actualiza el portfolio y mide. El mismo run() para cualquier estrategia.",
         "result = Backtest(market, mi_estrategia).run()\nresult.final_equity, result.n_fills"),
    ],
    "build": [
        {"title": "1. Tu primera estrategia", "practice": "heredar de Strategy",
         "statement": "Define `BuyOnce(Strategy)`: en el primer libro envía una market buy de 0.5; después nada.",
         "given": "from exchange import Strategy, NewOrder, Order, Side, OrderType\n",
         "starter": "class BuyOnce(Strategy):\n    def __init__(self):\n        self.done = False\n    def on_book_update(self, book):\n        pass\n",
         "validator": "from exchange import Market, Backtest\nr = Backtest(Market.sample(), BuyOnce()).run()\nassert r.n_fills >= 1 and r.final_position > 0\nprint('ok  fills=%d pos=%.2f' % (r.n_fills, r.final_position))",
         "solution": "class BuyOnce(Strategy):\n    def __init__(self):\n        self.done = False\n    def on_book_update(self, book):\n        if self.done:\n            return []\n        self.done = True\n        return [NewOrder(Order('BTCUSDT', Side.BUY, 0.5, order_type=OrderType.MARKET))]"},
        {"title": "2. Corre el Backtest", "practice": "Backtest.run",
         "statement": "Corre `BuyOnce` con `Backtest(Market.sample(), BuyOnce()).run()`. Guarda `result` y `equity`.",
         "given": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\nclass BuyOnce(Strategy):\n    def __init__(self): self.done=False\n    def on_book_update(self, book):\n        if self.done: return []\n        self.done=True\n        return [NewOrder(Order('BTCUSDT', Side.BUY, 0.5, order_type=OrderType.MARKET))]\n",
         "starter": "result = None\nequity = None\n",
         "validator": "assert result.n_steps == 500\nassert isinstance(equity, float)\nprint('ok ', result)",
         "solution": "result = Backtest(Market.sample(), BuyOnce()).run()\nequity = result.final_equity"},
        {"title": "3. Reacciona a tus fills", "practice": "el hook on_fill",
         "statement": "Define `CountingBuyer(Strategy)` que cuente sus fills en `self.n` vía `on_fill`. Compra 0.1 cada paso.",
         "given": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\n",
         "starter": "class CountingBuyer(Strategy):\n    def __init__(self):\n        self.n = 0\n    def on_book_update(self, book):\n        return [NewOrder(Order('BTCUSDT', Side.BUY, 0.1, order_type=OrderType.MARKET))]\n    def on_fill(self, fill):\n        pass\n",
         "validator": "s = CountingBuyer()\nBacktest(Market.sample(), s).run()\nassert s.n >= 1, 'on_fill debe haberse llamado'\nprint('ok  on_fill llamado %d veces' % s.n)",
         "pista": "Solo falta `on_fill`: recibe un `fill` y hace `self.n += 1`. El `on_book_update` ya está en el starter.",
         "solution": "class CountingBuyer(Strategy):\n    def __init__(self):\n        self.n = 0\n    def on_book_update(self, book):\n        return [NewOrder(Order('BTCUSDT', Side.BUY, 0.1, order_type=OrderType.MARKET))]\n    def on_fill(self, fill):\n        self.n += 1"},
        {"title": "4. Polimorfismo: cambia la estrategia, no el runner", "practice": "intercambiar subclases",
         "statement": "Define `SellOnce` (igual que BuyOnce pero vende). Córrela en el MISMO Backtest. Guarda `pos` (debe ser < 0).",
         "given": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\n",
         "starter": "class SellOnce(Strategy):\n    def __init__(self): self.done=False\n    def on_book_update(self, book):\n        pass\n\npos = None\n",
         "validator": "assert pos < 0, 'SellOnce deja posición corta — mismo runner, otra estrategia'\nprint('ok  pos=%.2f' % pos)",
         "pista": "Copia el patrón BuyOnce: si `self.done`, devuelve `[]`; si no, márcalo y devuelve `[NewOrder(Order(..., Side.SELL, 0.5, order_type=OrderType.MARKET))]`. Luego `Backtest(Market.sample(), SellOnce()).run().final_position`.",
         "solution": "class SellOnce(Strategy):\n    def __init__(self): self.done=False\n    def on_book_update(self, book):\n        if self.done: return []\n        self.done=True\n        return [NewOrder(Order('BTCUSDT', Side.SELL, 0.5, order_type=OrderType.MARKET))]\npos = Backtest(Market.sample(), SellOnce()).run().final_position"},
    ],
    "aux": [
        {"section": "Gimnasio · Calentamiento — repaso exprés de L9",
         "blurb": "El loop y la fórmula de la cuenta, en dos reps."},
        {"title": "C1. El día exprés", "practice": "repaso: contar pasos",
         "statement": "¿Cuántos pasos tiene `Market.sample()`? Cuéntalos en `n` (o usa `len`).",
         "given": "from exchange.market import Market\nm = Market.sample()\n",
         "starter": "n = None\n",
         "validator": "assert n == 500\nprint('ok')",
         "solution": "n = len(m)"},
        {"title": "C2. equity exprés", "practice": "repaso: la fórmula",
         "statement": "Con `cash = -9999.0` y `position = 0.1`, calcula `eq` al mark 100000.",
         "given": "cash = -9999.0\nposition = 0.1\n",
         "starter": "eq = None\n",
         "validator": "assert abs(eq - 1.0) < 1e-9\nprint('ok')",
         "solution": "eq = cash + position * 100000"},

        {"section": "Gimnasio · Bloque 1 — El contrato Strategy",
         "blurb": "Subclases, acciones y el runner: el enchufe, drill a drill."},
        {"title": "A1. La estrategia que no hace nada", "practice": "el contrato mínimo",
         "statement": "Escribe `Hold(Strategy)` cuyo `on_book_update` devuelva `[]`. Pásala por el Backtest y guarda `result`.",
         "given": "from exchange.backtest import Backtest\nfrom exchange.market import Market\nfrom exchange.strategy import Strategy\n",
         "starter": "result = None\n",
         "validator": "assert result.n_steps == 500 and result.n_fills == 0\nassert abs(result.final_equity) < 1e-9\nprint('ok ->', result)",
         "solution": "class Hold(Strategy):\n    def on_book_update(self, book):\n        return []\n\nresult = Backtest(Market.sample(), Hold()).run()"},
        {"title": "A2. Una acción de verdad", "practice": "NewOrder",
         "statement": "Construye la acción `a = NewOrder(Order('BTCUSDT', 'buy', 0.05, order_type=OrderType.MARKET))` y comprueba sus campos.",
         "given": "from exchange.orders import Order, OrderType\nfrom exchange.strategy import NewOrder\n",
         "starter": "a = None\n",
         "validator": "assert isinstance(a, NewOrder)\nassert a.order.side == 'buy' and a.order.size == 0.05\nprint('ok ->', a.order)",
         "solution": "a = NewOrder(Order('BTCUSDT', 'buy', 0.05, order_type=OrderType.MARKET))"},
        {"title": "A3. BuyOnce, tuya", "practice": "la subclase clásica",
         "statement": "Escribe `BuyOnce(Strategy)`: en el primer libro devuelve UNA market buy de 0.1 y después siempre `[]`. Ejecútala y guarda `result`.",
         "given": "from exchange.backtest import Backtest\nfrom exchange.market import Market\nfrom exchange.orders import Order, OrderType\nfrom exchange.strategy import NewOrder, Strategy\n",
         "starter": "result = None\n",
         "validator": "assert result.n_fills >= 1\nassert result.final_position > 0\nprint('ok ->', result)",
         "solution": "class BuyOnce(Strategy):\n    def __init__(self):\n        self._done = False\n    def on_book_update(self, book):\n        if self._done:\n            return []\n        self._done = True\n        return [NewOrder(Order('BTCUSDT', 'buy', 0.1, order_type=OrderType.MARKET))]\n\nresult = Backtest(Market.sample(), BuyOnce()).run()"},
        {"title": "A4. El gancho on_fill", "practice": "feedback del motor",
         "statement": "Añade a tu BuyOnce un contador `self.n_fills` que crezca en `on_fill`. Tras el run, debe coincidir con `result.n_fills`.",
         "given": "from exchange.backtest import Backtest\nfrom exchange.market import Market\nfrom exchange.orders import Order, OrderType\nfrom exchange.strategy import NewOrder, Strategy\n",
         "starter": "strat = None\nresult = None\n",
         "validator": "assert strat.n_fills == result.n_fills\nassert strat.n_fills >= 1\nprint('ok ->', strat.n_fills, 'fills contados por la estrategia')",
         "solution": "class BuyOnce(Strategy):\n    def __init__(self):\n        self._done = False\n        self.n_fills = 0\n    def on_book_update(self, book):\n        if self._done:\n            return []\n        self._done = True\n        return [NewOrder(Order('BTCUSDT', 'buy', 0.1, order_type=OrderType.MARKET))]\n    def on_fill(self, fill):\n        self.n_fills += 1\n\nstrat = BuyOnce()\nresult = Backtest(Market.sample(), strat).run()"},
        {"title": "A5. El mismo runner, dos vidas", "practice": "polimorfismo en producción",
         "statement": "Ejecuta `Hold` y `BuyOnce` (dadas) por el MISMO `Backtest.run()` y guarda `(eq_hold, eq_buy)`. Ni una línea del motor cambió.",
         "given": "from exchange.backtest import Backtest\nfrom exchange.market import Market\nfrom exchange.orders import Order, OrderType\nfrom exchange.strategy import NewOrder, Strategy\n\nclass Hold(Strategy):\n    def on_book_update(self, book):\n        return []\n\nclass BuyOnce(Strategy):\n    def __init__(self):\n        self._done = False\n    def on_book_update(self, book):\n        if self._done:\n            return []\n        self._done = True\n        return [NewOrder(Order('BTCUSDT', 'buy', 0.1, order_type=OrderType.MARKET))]\n",
         "starter": "eq_hold = None\neq_buy = None\n",
         "validator": "assert abs(eq_hold) < 1e-9\nassert abs(eq_buy) > 1e-9, 'BuyOnce tiene posicion: su equity se movio'\nprint(f'ok  hold={eq_hold} buy={eq_buy:.2f}')",
         "solution": "eq_hold = Backtest(Market.sample(), Hold()).run().final_equity\neq_buy = Backtest(Market.sample(), BuyOnce()).run().final_equity"},

        {"section": "Para terminar — profundización",
         "blurb": "Una estrategia con señal de verdad, lista para el juicio de L11."},
        {"title": "A6. Estrategia con señal", "practice": "decidir según el libro",
         "statement": "Define `ImbalanceBuyer`: compra 0.1 (market) solo cuando `book.imbalance(1) > 0.3`. Guarda `fills` del backtest.",
         "starter": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\nclass ImbalanceBuyer(Strategy):\n    def on_book_update(self, book):\n        pass\nfills = None\n",
         "validator": "assert fills is not None and fills >= 0\nprint('ok  fills=%d' % fills)",
         "solution": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\nclass ImbalanceBuyer(Strategy):\n    def on_book_update(self, book):\n        if book.imbalance(1) is not None and book.imbalance(1) > 0.3:\n            return [NewOrder(Order('BTCUSDT', Side.BUY, 0.1, order_type=OrderType.MARKET))]\n        return []\nfills = Backtest(Market.sample(), ImbalanceBuyer()).run().n_fills"},
    ],
})

# ---------------------------------------------------------------------------
# L9 — Primera estrategia + métricas
# ---------------------------------------------------------------------------
LESSONS.append({
    "n": 11, "slug": "11-first-strategy-metrics",
    "title": "Primera estrategia + métricas",
    "piece": "medir una estrategia contra un benchmark",
    "objective": "Cerrar el motor: una estrategia con señal real, y métricas honestas — PnL, posición y slippage contra el mid de llegada. Checkpoint integrador de todo L1-L9.",
    "frase": "Sin benchmark no hay estrategia: medir contra el mid de llegada separa la suerte del valor.",
    "concepts": [
        ("Una estrategia con criterio",
         "Compra cuando el libro empuja arriba (imbalance positivo), vende cuando empuja abajo. Simple, pero ya es una decisión basada en microestructura.",
         "if book.imbalance(3) > thr:  buy\nelif book.imbalance(3) < -thr: sell"),
        ("El benchmark: mid de llegada",
         "El precio justo de referencia es el mid cuando empezaste. Tu ejecución es buena si compraste por debajo (o vendiste por encima) de él.",
         "arrival_mid = primer book.mid\nslippage = eff_price - arrival_mid"),
        ("Leer el resultado con honestidad",
         "final_equity, posición final, número de fills. Un equity positivo con inventario enorme no es una buena estrategia: es riesgo escondido.",
         "result.final_equity, result.final_position,\nresult.n_fills"),
    ],
    "build": [
        {"title": "1. Estrategia de imbalance", "practice": "señal larga/corta",
         "statement": "Define `ImbalanceStrategy(thr)`: compra 0.05 si `imbalance(3) > thr`, vende 0.05 si `< -thr`. Market orders.",
         "given": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\n",
         "starter": "class ImbalanceStrategy(Strategy):\n    def __init__(self, thr=0.3):\n        self.thr = thr\n    def on_book_update(self, book):\n        pass\n",
         "validator": "r = Backtest(Market.sample(), ImbalanceStrategy(0.3)).run()\nassert r.n_steps == 500\nprint('ok ', r)",
         "solution": "class ImbalanceStrategy(Strategy):\n    def __init__(self, thr=0.3):\n        self.thr = thr\n    def on_book_update(self, book):\n        imb = book.imbalance(3)\n        if imb is None: return []\n        if imb > self.thr:\n            return [NewOrder(Order('BTCUSDT', Side.BUY, 0.05, order_type=OrderType.MARKET))]\n        if imb < -self.thr:\n            return [NewOrder(Order('BTCUSDT', Side.SELL, 0.05, order_type=OrderType.MARKET))]\n        return []"},
        {"title": "2. Mídela", "practice": "leer BacktestResult",
         "statement": "Corre la estrategia y guarda `equity`, `pos` y `fills` del resultado.",
         "given": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\nclass ImbalanceStrategy(Strategy):\n    def __init__(self, thr=0.3): self.thr=thr\n    def on_book_update(self, book):\n        imb = book.imbalance(3)\n        if imb is None: return []\n        if imb > self.thr: return [NewOrder(Order('BTCUSDT', Side.BUY, 0.05, order_type=OrderType.MARKET))]\n        if imb < -self.thr: return [NewOrder(Order('BTCUSDT', Side.SELL, 0.05, order_type=OrderType.MARKET))]\n        return []\n",
         "starter": "equity = None\npos = None\nfills = None\n",
         "validator": "assert isinstance(equity, float) and isinstance(fills, int)\nprint('ok  equity=%.2f pos=%.3f fills=%d' % (equity, pos, fills))",
         "solution": "r = Backtest(Market.sample(), ImbalanceStrategy(0.3)).run()\nequity = r.final_equity\npos = r.final_position\nfills = r.n_fills"},
        {"title": "3. Benchmark de llegada", "practice": "mid inicial",
         "statement": "Guarda `arrival_mid`, el mid del primer snapshot del mercado.",
         "starter": "from exchange import Market\narrival_mid = None\n",
         "validator": "assert 90000 < arrival_mid < 110000\nprint('ok  arrival_mid=%.2f' % arrival_mid)",
         "pista": "Encadena: `Market.sample()` te da el mercado, `.step()` el primer libro, `.mid` su punto medio.",
         "solution": "from exchange import Market\narrival_mid = Market.sample().step().mid"},
        {"title": "4. Riesgo escondido", "practice": "interpretar inventario",
         "statement": "Para `thr=0.1` y `thr=0.5`, guarda en `pos_small_thr` y `pos_big_thr` la posición final. Un umbral bajo opera más y arriesga más inventario.",
         "given": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\nclass ImbalanceStrategy(Strategy):\n    def __init__(self, thr=0.3): self.thr=thr\n    def on_book_update(self, book):\n        imb = book.imbalance(3)\n        if imb is None: return []\n        if imb > self.thr: return [NewOrder(Order('BTCUSDT', Side.BUY, 0.05, order_type=OrderType.MARKET))]\n        if imb < -self.thr: return [NewOrder(Order('BTCUSDT', Side.SELL, 0.05, order_type=OrderType.MARKET))]\n        return []\n",
         "starter": "pos_small_thr = None\npos_big_thr = None\n",
         "validator": "assert pos_small_thr is not None and pos_big_thr is not None\nprint('ok  thr0.1 pos=%.3f | thr0.5 pos=%.3f' % (pos_small_thr, pos_big_thr))",
         "pista": "Dos backtests idénticos salvo el umbral: `Backtest(Market.sample(), ImbalanceStrategy(0.1)).run().final_position`, y lo mismo con 0.5. `Market.sample()` nuevo en cada uno, para que ambos vean el mismo día.",
         "solution": "pos_small_thr = Backtest(Market.sample(), ImbalanceStrategy(0.1)).run().final_position\npos_big_thr = Backtest(Market.sample(), ImbalanceStrategy(0.5)).run().final_position"},
    ],
    "aux": [
        {"section": "Gimnasio · Calentamiento — repaso exprés de L10",
         "blurb": "El contrato y el resultado del runner, en dos reps."},
        {"title": "C1. Contrato exprés", "practice": "repaso: Strategy",
         "statement": "Escribe `Hold(Strategy)` (devuelve `[]`) e instánciala en `h`.",
         "given": "from exchange.strategy import Strategy\n",
         "starter": "h = None\n",
         "validator": "assert h.on_book_update(None) == []\nprint('ok')",
         "solution": "class Hold(Strategy):\n    def on_book_update(self, book):\n        return []\n\nh = Hold()"},
        {"title": "C2. Leer el resultado", "practice": "repaso: BacktestResult",
         "statement": "De un run de Hold, guarda `pasos` y `n_fills`.",
         "given": "from exchange.backtest import Backtest\nfrom exchange.market import Market\nfrom exchange.strategy import Strategy\nclass Hold(Strategy):\n    def on_book_update(self, book):\n        return []\nresult = Backtest(Market.sample(), Hold()).run()\n",
         "starter": "pasos = None\nn_fills = None\n",
         "validator": "assert pasos == 500 and n_fills == 0\nprint('ok')",
         "solution": "pasos = result.n_steps\nn_fills = result.n_fills"},

        {"section": "Gimnasio · Bloque 1 — Medir con criterio",
         "blurb": "Arrival, slippage y benchmarks: la caja de herramientas del juicio."},
        {"title": "A1. El arrival mid", "practice": "el benchmark de llegada",
         "statement": "Guarda `arrival`: el mid del PRIMER snapshot (el precio que viste al decidir empezar).",
         "given": "from exchange.market import Market\nm = Market.sample()\n",
         "starter": "arrival = None\n",
         "validator": "m2 = Market.sample()\nassert abs(arrival - m2.step().mid) < 1e-9\nprint(f'ok  arrival={arrival}')",
         "solution": "arrival = m.step().mid"},
        {"title": "A2. Slippage de un fill", "practice": "con el signo correcto",
         "statement": "Compra a 100024.5 con mid 100000; venta a 99980 con mid 100000. Calcula `slip_buy` y `slip_sell` (positivo = te costó dinero).",
         "starter": "slip_buy = None\nslip_sell = None\n",
         "validator": "assert abs(slip_buy - 24.5) < 1e-9, 'compra: precio - mid'\nassert abs(slip_sell - 20.0) < 1e-9, 'venta: mid - precio'\nprint('ok')",
         "solution": "slip_buy = 100024.5 - 100000\nslip_sell = 100000 - 99980"},
        {"title": "A3. El coste total de ejecutar", "practice": "slippage agregado",
         "statement": "Con `slips` (por unidad) y clip 0.05, calcula `coste = media × n × clip`.",
         "given": "slips = [5.2, 6.1, 4.8, 7.0, 5.9]\nclip = 0.05\n",
         "starter": "coste = None\n",
         "validator": "assert abs(coste - 1.45) < 1e-6\nprint(f'ok  coste={coste}')",
         "solution": "media = sum(slips) / len(slips)\ncoste = media * len(slips) * clip"},
        {"title": "A4. ¿Fuera de la nube?", "practice": "benchmark contra el azar",
         "statement": "Tu equity final fue `-27.3`; tres monos aleatorios hicieron `[5.4, -46.0, 8.6]`. Guarda `fuera` (True si tu resultado queda FUERA del rango de los monos).",
         "given": "mi_equity = -27.3\nmonos = [5.4, -46.0, 8.6]\n",
         "starter": "fuera = None\n",
         "validator": "assert fuera is False, 'dentro del rango del azar: nada demostrado'\nprint('ok — humildad estadistica')",
         "solution": "fuera = mi_equity < min(monos) or mi_equity > max(monos)"},
        {"title": "A5. PnL sin riesgo es media verdad", "practice": "comparar con inventario",
         "statement": "Dos estrategias: A = (PnL 30, máx inventario 2.0), B = (PnL 24, máx inventario 0.4). Guarda `mejor_por_unidad` ('A' o 'B') según PnL por unidad de inventario máximo.",
         "given": "pnl_a, inv_a = 30.0, 2.0\npnl_b, inv_b = 24.0, 0.4\n",
         "starter": "mejor_por_unidad = None\n",
         "validator": "assert mejor_por_unidad == 'B', '15 vs 60 de PnL por unidad de riesgo'\nprint('ok')",
         "solution": "ratio_a = pnl_a / inv_a\nratio_b = pnl_b / inv_b\nmejor_por_unidad = 'A' if ratio_a > ratio_b else 'B'"},

        {"section": "Para terminar — profundización",
         "blurb": "La curva de equity completa, con tus propias manos."},
        {"title": "A6. Curva de equity", "practice": "serie temporal de PnL",
         "statement": "Corre la estrategia y guarda `curve = result.equity_curve`. Verifica que tiene 500 puntos. (En clase la dibujarías con matplotlib.)",
         "given": "from exchange import Strategy, NewOrder, Order, Side, OrderType, Market, Backtest\nclass S(Strategy):\n    def on_book_update(self, book):\n        return [NewOrder(Order('BTCUSDT', Side.BUY, 0.01, order_type=OrderType.MARKET))]\n",
         "starter": "curve = None\n",
         "validator": "assert len(curve) == 500\nprint('ok  puntos=%d' % len(curve))",
         "solution": "curve = Backtest(Market.sample(), S()).run().equity_curve"},

        {"section": "Transferencia — la misma idea, otro dominio",
         "blurb": "Medir PnL por unidad de riesgo (el A5 de arriba) es un caso de una idea universal: "
                  "no mires el resultado bruto, mira el resultado POR unidad de lo que gastas. "
                  "Aquí, comparar la compra del súper por valor nutricional por euro."},
        {"title": "T1. La cesta que rinde más (ratio, fuera del trading)",
         "practice": "resultado por unidad de coste, fuera del trading",
         "statement": "Dos cestas de la compra: A aporta 1800 kcal por 6.0 €, B aporta 1500 kcal por 4.0 €. "
                       "Igual que elegiste la estrategia por PnL-por-riesgo, elige `mejor` ('A' o 'B') por "
                       "**kcal por euro**. La bruta no decide: decide el ratio.",
         "given": "kcal_a, precio_a = 1800, 6.0\nkcal_b, precio_b = 1500, 4.0\n",
         "starter": "mejor = None\n",
         "validator": "assert mejor == 'B', '300 vs 375 kcal/€: la cesta más barata rinde más por euro'\nprint('ok — el Sharpe era esto: no el PnL bruto, sino el PnL por unidad de riesgo')",
         "pista": "Calca el A5: un ratio por lado (`kcal_a / precio_a` y el de B) y un ternario que "
                  "devuelve la letra del mayor.",
         "solution": "ratio_a = kcal_a / precio_a\nratio_b = kcal_b / precio_b\nmejor = 'A' if ratio_a > ratio_b else 'B'"},
    ],
})
