# 📊 **Limit Order Book (LOB) - Dinámica Visual** 

<div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 20px; border-radius: 10px; color: white; text-align: center;">
    <h2>🚀 Entendiendo la Mecánica de los Mercados Financieros</h2>
    <p><i>"El corazón de todos los mercados electrónicos modernos"</i></p>
</div>

---

## 🎯 **¿Qué aprenderemos hoy?**

En este notebook exploraremos **visualmente** cómo funciona un **Limit Order Book**, el mecanismo fundamental que impulsa los mercados financieros modernos. 

### 📋 **Agenda del Tutorial:**
1. 🔍 **Conceptos Fundamentales** - ¿Qué es un LOB?
2. 📈 **Visualización Estática** - Componentes básicos 
3. ⚡ **Simulación Interactiva** - Órdenes en acción
4. 🎬 **Animaciones Dinámicas** - Mercado en tiempo real
5. 📊 **Métricas del Mercado** - Análisis avanzado
6. 💼 **Caso Práctico** - Simulación realista

## 🔍 **1. Conceptos Fundamentales**

### 🤔 **¿Qué es un Limit Order Book?**

Un **Limit Order Book (LOB)** es una estructura de datos que mantiene todas las órdenes de compra y venta pendientes para un activo financiero específico, organizadas por precio y tiempo.

<div style="background-color: #f8f9fa; border-left: 5px solid #28a745; padding: 15px; margin: 10px 0; color: #2c3e50;">
<h4 style="color: #2c3e50;">🎯 <b>Definición Simple:</b></h4>
<p style="color: #2c3e50;">Imagina un <b>libro de órdenes</b> como una <b>subasta continua</b> donde:</p>
<ul style="color: #2c3e50;">
    <li>📘 <b>Lado COMPRA (Bid)</b>: Lista de compradores dispuestos a pagar diferentes precios</li>
    <li>📕 <b>Lado VENTA (Ask)</b>: Lista de vendedores dispuestos a vender a diferentes precios</li>
</ul>
</div>

### 🏗️ **Componentes Principales:**

| 🔧 **Componente** | 📝 **Descripción** | 🎨 **Visualización** |
|:---|:---|:---|
| **🟢 Bid Side** | Órdenes de compra (lado izquierdo) | Precios decrecientes ⬇️ |
| **🔴 Ask Side** | Órdenes de venta (lado derecho) | Precios crecientes ⬆️ |
| **💰 Best Bid** | Precio más alto de compra | Mayor precio en bid side |
| **💸 Best Ask** | Precio más bajo de venta | Menor precio en ask side |
| **📏 Spread** | Diferencia: Best Ask - Best Bid | "Costo de liquidez" |
| **📊 Mid Price** | (Best Bid + Best Ask) / 2 | Precio "justo" teórico |

### 🎭 **Analogía del Mercado:**

<div style="background: linear-gradient(90deg, #74b9ff, #0984e3); padding: 15px; border-radius: 8px; color: white;">
<h4>🏪 <b>Piensa en un Bazar Tradicional:</b></h4>
<ul>
    <li>🛒 <b>Compradores</b> gritan: "¡Compro manzanas a $2!"</li>
    <li>🍎 <b>Vendedores</b> gritan: "¡Vendo manzanas a $3!"</li>
    <li>💱 Una <b>transacción</b> ocurre cuando alguien acepta el precio del otro</li>
    <li>📋 El <b>LOB</b> es como un megáfono que organiza todos estos gritos</li>
</ul>
</div>

### 📋 **Tipos de Órdenes:**

<div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin: 20px 0;">

<div style="background: linear-gradient(135deg, #a8e6cf, #7fcdcd); padding: 15px; border-radius: 8px; color: white;">
<h4 style="color: white;">📌 <b>LIMIT ORDER</b></h4>
<ul style="color: white;">
    <li><b>Precio específico</b> 🎯</li>
    <li><b>Se añade al book</b> 📚</li>
    <li><b>Espera matching</b> ⏳</li>
    <li><b>Ejemplo:</b> "Compro 100 AAPL a $150"</li>
</ul>
</div>

<div style="background: linear-gradient(135deg, #ffb3ba, #ff677d); padding: 15px; border-radius: 8px; color: white;">
<h4>⚡ <b>MARKET ORDER</b></h4>
<ul>
    <li><b>Ejecución inmediata</b> 🚀</li>
    <li><b>Al mejor precio disponible</b> 💰</li>
    <li><b>Consume liquidez</b> 🔥</li>
    <li><b>Ejemplo:</b> "Compro 100 AAPL YA"</li>
</ul>
</div>

</div>

### ⚙️ **¿Cómo Funciona la Mecánica?**

```
🔄 FLUJO BÁSICO DEL LOB:

1️⃣ LLEGA ORDEN → 2️⃣ ¿PUEDE EJECUTARSE? → 3️⃣ SI: MATCH ✅ / NO: AL BOOK 📚

┌─────────────┐    ┌─────────────┐    ┌─────────────┐
│   ORDEN     │    │   MATCHING  │    │  RESULTADO  │
│   NUEVA     │───▶│   ENGINE    │───▶│   TRADE O   │
│             │    │             │    │   PENDING   │
└─────────────┘    └─────────────┘    └─────────────┘
```

### 🧠 **Reglas de Prioridad:**

<div style="background-color: #2c3e50; border: 1px solid #34495e; padding: 15px; border-radius: 5px; color: white;">
<h4 style="color: white;">📏 <b>¿Qué orden se ejecuta primero?</b></h4>
<ol style="color: white;">
    <li><b>🥇 PRECIO</b>: Mejor precio tiene prioridad</li>
    <li><b>🥈 TIEMPO</b>: Si mismo precio → Primero en llegar, primero en servirse (FIFO)</li>
</ol>

<p style="color: white;"><b>Ejemplo:</b> Si hay 3 órdenes de compra a $100, se ejecuta la que llegó primero ⏰</p>
</div>

### 🎨 **Ejemplo Visual Conceptual:**

Imagina el LOB como una **escalera de precios**:

```
                    📊 LIMIT ORDER BOOK
                    
    COMPRA (BID) 💰              💰 VENTA (ASK)
    
    $149.95  │ 500 shares       300 shares │ $150.05
    $149.90  │ 200 shares       150 shares │ $150.10  
    $149.85  │ 800 shares       600 shares │ $150.15
    $149.80  │ 300 shares       400 shares │ $150.20
    
             ↑                           ↑
         Best Bid                   Best Ask
         ($149.95)                  ($150.05)
                      
                   Spread = $0.10
                Mid Price = $150.00
```

<div style="background: linear-gradient(135deg, #74b9ff, #0984e3); padding: 20px; border-radius: 10px; color: white; text-align: center; margin: 20px 0;">
<h3>🚀 ¡Ahora vamos a crear nuestro primer LOB visual!</h3>
<p>En las siguientes celdas configuraremos las herramientas y crearemos visualizaciones interactivas</p>
</div>

---

In [1]:
# 🛠️ CONFIGURACIÓN INICIAL - Importación de librerías
print("🚀 Configurando el entorno para visualización de LOB...")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import warnings
warnings.filterwarnings('ignore')

# Configuración de estilo
plt.style.use('seaborn-v0_8')
sns.set_palette("husl")

# Configuración para Jupyter
from IPython.display import display, HTML, clear_output
import ipywidgets as widgets

print("✅ ¡Librerías cargadas exitosamente!")
print("📊 Listo para crear visualizaciones del Limit Order Book")

# Configuración de plotting
plt.rcParams['figure.figsize'] = (12, 8)
plt.rcParams['font.size'] = 10

🚀 Configurando el entorno para visualización de LOB...
✅ ¡Librerías cargadas exitosamente!
📊 Listo para crear visualizaciones del Limit Order Book
✅ ¡Librerías cargadas exitosamente!
📊 Listo para crear visualizaciones del Limit Order Book


## 📈 **2. Visualización Estática - Componentes Básicos**

<div style="background: linear-gradient(135deg, #fd79a8, #e84393); padding: 20px; border-radius: 10px; color: white; text-align: center; margin: 20px 0;">
<h3>🎯 Objetivo: Crear nuestro primer LOB visual</h3>
<p>Construiremos paso a paso un Limit Order Book funcional con visualizaciones atractivas</p>
</div>

### 🏗️ **¿Qué vamos a construir?**

En esta sección crearemos:

| 🛠️ **Componente** | 📝 **Descripción** | 🎨 **Visual** |
|:---|:---|:---|
| **📚 Clase LOB** | Estructura para manejar órdenes | Sistema básico |
| **📊 LOB Estático** | Visualización con datos fijos | Gráfico bid/ask |
| **📏 Métricas** | Spread, mid-price, profundidad | Indicadores clave |
| **🎨 Styling** | Colores y formato profesional | Plotly interactivo |

---

In [2]:
# 🏗️ CONSTRUCCIÓN DE LA CLASE LIMIT ORDER BOOK
print("🔨 Construyendo la clase Limit Order Book...")

class LimitOrderBook:
    """
    🏛️ Clase para simular un Limit Order Book
    
    Esta clase mantiene las órdenes de compra (bids) y venta (asks)
    organizadas por precio y tiempo de llegada.
    """
    
    def __init__(self, symbol="AAPL"):
        self.symbol = symbol
        # 📘 Bids: diccionario {precio: [cantidad_total, timestamp]}
        self.bids = {}
        # 📕 Asks: diccionario {precio: [cantidad_total, timestamp]}  
        self.asks = {}
        self.trades = []  # Historial de transacciones
        
    def add_order(self, side, price, quantity, timestamp=None):
        """
        ➕ Añadir una orden al book
        
        Args:
            side: 'bid' o 'ask'
            price: precio de la orden
            quantity: cantidad de acciones
            timestamp: momento de llegada (opcional)
        """
        if timestamp is None:
            import time
            timestamp = time.time()
            
        if side.lower() == 'bid':
            if price in self.bids:
                # Sumar cantidad si ya existe el precio
                self.bids[price][0] += quantity
            else:
                # Nuevo nivel de precio
                self.bids[price] = [quantity, timestamp]
                
        elif side.lower() == 'ask':
            if price in self.asks:
                self.asks[price][0] += quantity
            else:
                self.asks[price] = [quantity, timestamp]
    
    def get_best_bid(self):
        """💰 Obtener el mejor precio de compra (más alto)"""
        if not self.bids:
            return None
        return max(self.bids.keys())
    
    def get_best_ask(self):
        """💸 Obtener el mejor precio de venta (más bajo)"""
        if not self.asks:
            return None
        return min(self.asks.keys())
    
    def get_spread(self):
        """📏 Calcular el spread (diferencia entre ask y bid)"""
        best_bid = self.get_best_bid()
        best_ask = self.get_best_ask()
        
        if best_bid is None or best_ask is None:
            return None
        return round(best_ask - best_bid, 2)
    
    def get_mid_price(self):
        """📊 Calcular el precio medio"""
        best_bid = self.get_best_bid()
        best_ask = self.get_best_ask()
        
        if best_bid is None or best_ask is None:
            return None
        return round((best_bid + best_ask) / 2, 2)
    
    def get_book_summary(self):
        """📋 Resumen del estado actual del book"""
        return {
            'symbol': self.symbol,
            'best_bid': self.get_best_bid(),
            'best_ask': self.get_best_ask(),
            'spread': self.get_spread(),
            'mid_price': self.get_mid_price(),
            'bid_levels': len(self.bids),
            'ask_levels': len(self.asks)
        }

print("✅ ¡Clase LimitOrderBook creada exitosamente!")
print("🎯 Lista para recibir órdenes y generar visualizaciones")

🔨 Construyendo la clase Limit Order Book...
✅ ¡Clase LimitOrderBook creada exitosamente!
🎯 Lista para recibir órdenes y generar visualizaciones


In [3]:
# 📊 CREACIÓN DE DATOS DE EJEMPLO PARA NUESTRO PRIMER LOB
print("🎲 Generando datos de ejemplo para el LOB...")

# Crear instancia del LOB
lob = LimitOrderBook("AAPL")

# 📘 Añadir órdenes BID (compra) - precios decrecientes
bid_orders = [
    (149.95, 500),   # Mejor bid
    (149.90, 200),
    (149.85, 800),
    (149.80, 300),
    (149.75, 150),
    (149.70, 600),
    (149.65, 250),
    (149.60, 400),
]

# 📕 Añadir órdenes ASK (venta) - precios crecientes  
ask_orders = [
    (150.05, 300),   # Mejor ask
    (150.10, 150),
    (150.15, 600),
    (150.20, 400),
    (150.25, 200),
    (150.30, 350),
    (150.35, 500),
    (150.40, 100),
]

# Llenar el LOB con las órdenes
print("📘 Añadiendo órdenes BID...")
for price, qty in bid_orders:
    lob.add_order('bid', price, qty)

print("📕 Añadiendo órdenes ASK...")
for price, qty in ask_orders:
    lob.add_order('ask', price, qty)

# Mostrar resumen del LOB
summary = lob.get_book_summary()
print("\n" + "="*50)
print("📋 RESUMEN DEL LIMIT ORDER BOOK")
print("="*50)
print(f"🏷️  Símbolo: {summary['symbol']}")
print(f"💰 Best Bid: ${summary['best_bid']}")
print(f"💸 Best Ask: ${summary['best_ask']}")
print(f"📏 Spread: ${summary['spread']}")
print(f"📊 Mid Price: ${summary['mid_price']}")
print(f"📘 Niveles Bid: {summary['bid_levels']}")
print(f"📕 Niveles Ask: {summary['ask_levels']}")
print("="*50)

🎲 Generando datos de ejemplo para el LOB...
📘 Añadiendo órdenes BID...
📕 Añadiendo órdenes ASK...

📋 RESUMEN DEL LIMIT ORDER BOOK
🏷️  Símbolo: AAPL
💰 Best Bid: $149.95
💸 Best Ask: $150.05
📏 Spread: $0.1
📊 Mid Price: $150.0
📘 Niveles Bid: 8
📕 Niveles Ask: 8


In [4]:
# 🎨 FUNCIÓN PARA VISUALIZAR EL LOB DE FORMA ESTÁTICA
def plot_lob_static(lob, title="📊 Limit Order Book - Vista Estática"):
    """
    🎨 Crear visualización estática del Limit Order Book usando Plotly
    
    Args:
        lob: Instancia de LimitOrderBook
        title: Título del gráfico
    """
    
    # Preparar datos para visualización
    bid_prices = sorted(lob.bids.keys(), reverse=True)  # Mayor a menor
    bid_quantities = [lob.bids[price][0] for price in bid_prices]
    
    ask_prices = sorted(lob.asks.keys())  # Menor a mayor
    ask_quantities = [lob.asks[price][0] for price in ask_prices]
    
    # Crear subplots
    fig = make_subplots(
        rows=1, cols=2,
        subplot_titles=["📘 BID SIDE (Compra)", "📕 ASK SIDE (Venta)"],
        shared_yaxes=True,
        horizontal_spacing=0.15
    )
    
    # 📘 BID SIDE (lado izquierdo)
    fig.add_trace(
        go.Bar(
            x=[-q for q in bid_quantities],  # Negativo para ir hacia la izquierda
            y=bid_prices,
            orientation='h',
            name='Bids',
            marker=dict(
                color='rgba(46, 204, 113, 0.8)',  # Verde
                line=dict(color='rgba(46, 204, 113, 1.0)', width=1)
            ),
            text=[f'${p:.2f}<br>{q:,} shares' for p, q in zip(bid_prices, bid_quantities)],
            textposition='inside',
            hovertemplate='<b>Precio:</b> $%{y:.2f}<br><b>Cantidad:</b> %{customdata:,}<br><extra></extra>',
            customdata=bid_quantities
        ),
        row=1, col=1
    )
    
    # 📕 ASK SIDE (lado derecho)  
    fig.add_trace(
        go.Bar(
            x=ask_quantities,
            y=ask_prices,
            orientation='h',
            name='Asks',
            marker=dict(
                color='rgba(231, 76, 60, 0.8)',  # Rojo
                line=dict(color='rgba(231, 76, 60, 1.0)', width=1)
            ),
            text=[f'${p:.2f}<br>{q:,} shares' for p, q in zip(ask_prices, ask_quantities)],
            textposition='inside',
            hovertemplate='<b>Precio:</b> $%{y:.2f}<br><b>Cantidad:</b> %{x:,}<br><extra></extra>'
        ),
        row=1, col=2
    )
    
    # Añadir líneas para best bid y best ask
    best_bid = lob.get_best_bid()
    best_ask = lob.get_best_ask()
    
    if best_bid:
        fig.add_hline(
            y=best_bid, 
            line_dash="dash", 
            line_color="green",
            annotation_text=f"Best Bid: ${best_bid:.2f}",
            annotation_position="bottom right"
        )
    
    if best_ask:
        fig.add_hline(
            y=best_ask, 
            line_dash="dash", 
            line_color="red",
            annotation_text=f"Best Ask: ${best_ask:.2f}",
            annotation_position="top right"
        )
    
    # Configuración del layout
    fig.update_layout(
        title=dict(
            text=title,
            x=0.5,
            font=dict(size=20, color='#2c3e50')
        ),
        height=600,
        showlegend=False,
        plot_bgcolor='rgba(248, 249, 250, 0.8)',
        paper_bgcolor='white',
        font=dict(size=12)
    )
    
    # Configurar ejes
    fig.update_xaxes(title_text="📊 Cantidad (shares)", row=1, col=1)
    fig.update_xaxes(title_text="📊 Cantidad (shares)", row=1, col=2)
    fig.update_yaxes(title_text="💰 Precio ($)", row=1, col=1)
    
    # Mostrar métricas en texto
    summary = lob.get_book_summary()
    metrics_text = f"""
    <div style='background: linear-gradient(135deg, #74b9ff, #0984e3); padding: 15px; border-radius: 8px; color: white; margin: 10px 0;'>
        <h4>📊 Métricas del Mercado:</h4>
        <p><b>💰 Best Bid:</b> ${summary['best_bid']:.2f} | <b>💸 Best Ask:</b> ${summary['best_ask']:.2f}</p>
        <p><b>📏 Spread:</b> ${summary['spread']:.2f} | <b>📊 Mid Price:</b> ${summary['mid_price']:.2f}</p>
    </div>
    """
    
    display(HTML(metrics_text))
    
    return fig

print("✅ Función de visualización creada!")
print("🎨 Lista para generar nuestro primer gráfico del LOB")

✅ Función de visualización creada!
🎨 Lista para generar nuestro primer gráfico del LOB


In [5]:
# 🚀 ¡GENEREMOS NUESTRO PRIMER LOB VISUAL!
print("🎬 Generando la primera visualización del Limit Order Book...")
print("📊 Datos cargados, función lista, ¡aquí vamos!")

# Crear y mostrar la visualización
fig = plot_lob_static(lob, "🎯 Mi Primer Limit Order Book - AAPL")
fig.show()

print("\n🎉 ¡FELICIDADES! Has creado tu primer Limit Order Book visual")
print("👆 Observa cómo:")
print("   📘 El lado BID (verde) muestra órdenes de compra")
print("   📕 El lado ASK (rojo) muestra órdenes de venta") 
print("   📏 Las líneas punteadas marcan los mejores precios")
print("   💰 El spread es la diferencia entre ambos lados")

🎬 Generando la primera visualización del Limit Order Book...
📊 Datos cargados, función lista, ¡aquí vamos!



🎉 ¡FELICIDADES! Has creado tu primer Limit Order Book visual
👆 Observa cómo:
   📘 El lado BID (verde) muestra órdenes de compra
   📕 El lado ASK (rojo) muestra órdenes de venta
   📏 Las líneas punteadas marcan los mejores precios
   💰 El spread es la diferencia entre ambos lados


## 🧠 **Quiz: ¿Entendiste el Limit Order Book?**

<div style="background: linear-gradient(135deg, #00b894, #00a085); padding: 20px; border-radius: 10px; color: white; text-align: center; margin: 20px 0;">
<h3>🎯 ¡Pon a prueba tus conocimientos!</h3>
<p>Responde estas 5 preguntas para verificar que comprendes cómo funciona un LOB</p>
</div>

---

### **📝 Pregunta 1: Conceptos Básicos**

<div style="background-color: #f8f9fa; border-left: 5px solid #e74c3c; padding: 15px; margin: 10px 0; color: #2c3e50;">
<h4 style="color: #e74c3c;">🤔 <b>¿Cuál es la diferencia principal entre una orden LIMIT y una orden MARKET?</b></h4>
<p style="color: #2c3e50;"><b>A)</b> Las órdenes LIMIT se ejecutan más rápido</p>
<p style="color: #2c3e50;"><b>B)</b> Las órdenes MARKET especifican un precio exacto, las LIMIT no</p>
<p style="color: #2c3e50;"><b>C)</b> Las órdenes LIMIT especifican un precio exacto, las MARKET se ejecutan al mejor precio disponible</p>
<p style="color: #2c3e50;"><b>D)</b> No hay diferencia entre ambas</p>
</div>

---

### **📊 Pregunta 2: Estructura del LOB**

<div style="background-color: #f8f9fa; border-left: 5px solid #f39c12; padding: 15px; margin: 10px 0; color: #2c3e50;">
<h4 style="color: #f39c12;">💰 <b>Si el Best Bid es $149.95 y el Best Ask es $150.05, ¿cuál es el Spread?</b></h4>
<p style="color: #2c3e50;"><b>A)</b> $300.00</p>
<p style="color: #2c3e50;"><b>B)</b> $0.10</p>
<p style="color: #2c3e50;"><b>C)</b> $150.00</p>
<p style="color: #2c3e50;"><b>D)</b> $149.90</p>
</div>

---

### **⚡ Pregunta 3: Prioridad de Órdenes**

<div style="background-color: #f8f9fa; border-left: 5px solid #9b59b6; padding: 15px; margin: 10px 0; color: #2c3e50;">
<h4 style="color: #9b59b6;">🏃‍♂️ <b>¿Qué orden se ejecuta primero según las reglas de prioridad?</b></h4>
<p style="color: #2c3e50;"><b>Escenario:</b> Hay 3 órdenes de compra:</p>
<ul style="color: #2c3e50;">
<li>Orden A: $100.00 (llegó a las 10:00)</li>
<li>Orden B: $101.00 (llegó a las 10:05)</li>
<li>Orden C: $100.00 (llegó a las 10:03)</li>
</ul>
<p style="color: #2c3e50;"><b>A)</b> Orden A (por tiempo)</p>
<p style="color: #2c3e50;"><b>B)</b> Orden B (por precio)</p>
<p style="color: #2c3e50;"><b>C)</b> Orden C (por tiempo)</p>
<p style="color: #2c3e50;"><b>D)</b> Se ejecutan todas al mismo tiempo</p>
</div>

---

### **🎨 Pregunta 4: Visualización**

<div style="background-color: #f8f9fa; border-left: 5px solid #00b894; padding: 15px; margin: 10px 0; color: #2c3e50;">
<h4 style="color: #00b894;">📈 <b>En nuestro gráfico del LOB, ¿qué representa el lado verde (BID)?</b></h4>
<p style="color: #2c3e50;"><b>A)</b> Órdenes de venta ordenadas de menor a mayor precio</p>
<p style="color: #2c3e50;"><b>B)</b> Órdenes de compra ordenadas de mayor a menor precio</p>
<p style="color: #2c3e50;"><b>C)</b> Transacciones completadas</p>
<p style="color: #2c3e50;"><b>D)</b> El precio del mercado actual</p>
</div>

---

### **🧮 Pregunta 5: Cálculos**

<div style="background-color: #f8f9fa; border-left: 5px solid #3498db; padding: 15px; margin: 10px 0; color: #2c3e50;">
<h4 style="color: #3498db;">🔢 <b>¿Cómo se calcula el Mid Price?</b></h4>
<p style="color: #2c3e50;"><b>A)</b> Best Ask - Best Bid</p>
<p style="color: #2c3e50;"><b>B)</b> (Best Bid + Best Ask) / 2</p>
<p style="color: #2c3e50;"><b>C)</b> Best Bid × Best Ask</p>
<p style="color: #2c3e50;"><b>D)</b> Suma de todas las órdenes / número de órdenes</p>
</div>

---

<div style="background: linear-gradient(135deg, #fdcb6e, #e17055); padding: 15px; border-radius: 8px; color: white; text-align: center; margin: 20px 0;">
<h4>🎯 <b>¡Piensa en tus respuestas!</b></h4>
<p>En la siguiente celda encontrarás las respuestas correctas con explicaciones detalladas</p>
</div>

In [6]:
# 🎯 RESPUESTAS DEL QUIZ - ¡Ejecuta para ver las soluciones!
from IPython.display import HTML, display
import time

def show_quiz_answers():
    """
    🏆 Función que muestra las respuestas correctas del quiz con explicaciones
    """
    
    print("🎉 ¡RESPUESTAS DEL QUIZ LOB!")
    print("=" * 50)
    
    # Respuesta 1
    answer_1 = """
    <div style='background: linear-gradient(135deg, #00b894, #00a085); padding: 15px; border-radius: 8px; color: white; margin: 10px 0;'>
        <h4>📝 Pregunta 1: Respuesta Correcta = <b>C</b></h4>
        <p><b>✅ Explicación:</b> Las órdenes LIMIT especifican un precio exacto y esperan en el book hasta encontrar un match. Las órdenes MARKET se ejecutan inmediatamente al mejor precio disponible en ese momento.</p>
    </div>
    """
    
    # Respuesta 2  
    answer_2 = """
    <div style='background: linear-gradient(135deg, #fdcb6e, #e17055); padding: 15px; border-radius: 8px; color: white; margin: 10px 0;'>
        <h4>📊 Pregunta 2: Respuesta Correcta = <b>B</b></h4>
        <p><b>✅ Explicación:</b> Spread = Best Ask - Best Bid = $150.05 - $149.95 = $0.10. El spread representa el "costo de liquidez" del mercado.</p>
    </div>
    """
    
    # Respuesta 3
    answer_3 = """
    <div style='background: linear-gradient(135deg, #a29bfe, #6c5ce7); padding: 15px; border-radius: 8px; color: white; margin: 10px 0;'>
        <h4>⚡ Pregunta 3: Respuesta Correcta = <b>B</b></h4>
        <p><b>✅ Explicación:</b> La Orden B se ejecuta primero porque tiene el mejor precio ($101.00). Las reglas de prioridad son: 1° PRECIO, 2° TIEMPO. Entre órdenes del mismo precio, aplica FIFO.</p>
    </div>
    """
    
    # Respuesta 4
    answer_4 = """
    <div style='background: linear-gradient(135deg, #00cec9, #00b894); padding: 15px; border-radius: 8px; color: white; margin: 10px 0;'>
        <h4>🎨 Pregunta 4: Respuesta Correcta = <b>B</b></h4>
        <p><b>✅ Explicación:</b> El lado verde (BID) representa órdenes de compra ordenadas de mayor a menor precio. El precio más alto (Best Bid) está en la parte superior.</p>
    </div>
    """
    
    # Respuesta 5
    answer_5 = """
    <div style='background: linear-gradient(135deg, #74b9ff, #0984e3); padding: 15px; border-radius: 8px; color: white; margin: 10px 0;'>
        <h4>🧮 Pregunta 5: Respuesta Correcta = <b>B</b></h4>
        <p><b>✅ Explicación:</b> Mid Price = (Best Bid + Best Ask) / 2. En nuestro ejemplo: ($149.95 + $150.05) / 2 = $150.00. Representa el precio "justo" teórico.</p>
    </div>
    """
    
    # Puntuación
    score_section = """
    <div style='background: linear-gradient(135deg, #667eea, #764ba2); padding: 20px; border-radius: 10px; color: white; text-align: center; margin: 20px 0;'>
        <h3>🏆 ¡EVALUACIÓN COMPLETADA!</h3>
        <p><b>¿Cuántas respuestas acertaste?</b></p>
        <ul style='text-align: left; margin: 20px auto; max-width: 300px;'>
            <li><b>5/5:</b> 🎉 ¡Experto en LOB!</li>
            <li><b>4/5:</b> 👍 ¡Muy bien!</li>
            <li><b>3/5:</b> 😊 Buen entendimiento</li>
            <li><b>2/5:</b> 🤔 Repasa los conceptos</li>
            <li><b>0-1/5:</b> 📚 Vuelve a leer la teoría</li>
        </ul>
    </div>
    """
    
    # Mostrar todas las respuestas
    display(HTML(answer_1))
    time.sleep(0.5)
    display(HTML(answer_2))
    time.sleep(0.5)
    display(HTML(answer_3))
    time.sleep(0.5)
    display(HTML(answer_4))
    time.sleep(0.5)
    display(HTML(answer_5))
    time.sleep(0.5)
    display(HTML(score_section))
    
    print("\n🎯 ¡Excelente trabajo completando el quiz!")
    print("🚀 ¡Ahora estás listo para el siguiente nivel: Simulación Interactiva!")

# Ejecutar función
show_quiz_answers()

🎉 ¡RESPUESTAS DEL QUIZ LOB!



🎯 ¡Excelente trabajo completando el quiz!
🚀 ¡Ahora estás listo para el siguiente nivel: Simulación Interactiva!


---

## ⚡ **3. Simulación Interactiva - Órdenes en Acción**

<div style="background: linear-gradient(135deg, #00cec9, #00b894); padding: 20px; border-radius: 10px; color: white; text-align: center; margin: 20px 0;">
<h3>🎯 Objetivo: Simular órdenes reales en el LOB</h3>
<p>Vamos a crear un sistema interactivo donde podrás enviar órdenes y ver cómo se ejecutan en tiempo real</p>
</div>

### 🏗️ **¿Qué vamos a construir?**

En esta sección crearemos:

| 🛠️ **Componente** | 📝 **Descripción** | 🎨 **Funcionalidad** |
|:---|:---|:---|
| **🔧 LOB Avanzado** | Sistema completo de matching | Limit + Market Orders |
| **⚡ Market Orders** | Órdenes SIN precio específico | Ejecución inmediata |
| **📌 Limit Orders** | Órdenes CON precio específico | Se añaden al book |
| **🎮 Interfaz Interactiva** | Controles para enviar órdenes | Widgets de Jupyter |
| **📊 Visualización en Vivo** | LOB que se actualiza en tiempo real | Gráfico dinámico |

### 🚨 **Diferencias Clave:**

<div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin: 20px 0;">

<div style="background: linear-gradient(135deg, #a8e6cf, #7fcdcd); padding: 15px; border-radius: 8px; color: white;">
<h4 style="color: white;">📌 <b>LIMIT ORDER</b></h4>
<ul style="color: white;">
    <li><b>CON precio específico</b> 🎯</li>
    <li><b>Ejemplo:</b> "Compro 100 @ $149.90"</li>
    <li><b>Se añade al book</b> 📚</li>
    <li><b>Espera matching</b> ⏳</li>
</ul>
</div>

<div style="background: linear-gradient(135deg, #fd79a8, #e84393); padding: 15px; border-radius: 8px; color: white;">
<h4>⚡ <b>MARKET ORDER</b></h4>
<ul>
    <li><b>SIN precio específico</b> 🚀</li>
    <li><b>Ejemplo:</b> "Compro 100 YA"</li>
    <li><b>Ejecución inmediata</b> ⚡</li>
    <li><b>Al mejor precio disponible</b> 💰</li>
</ul>
</div>

</div>

---

In [7]:
import ipywidgets as widgets
from IPython.display import display, clear_output
import time

class InteractiveLOB:
    def __init__(self):
        self.bids = {}  # precio -> cantidad
        self.asks = {}  # precio -> cantidad
        self.last_price = 100.0
        self.trade_history = []
        
    def add_limit_order(self, side, price, quantity):
        """Agregar orden limitada"""
        if side == 'BUY':
            if price in self.bids:
                self.bids[price] += quantity
            else:
                self.bids[price] = quantity
        else:  # SELL
            if price in self.asks:
                self.asks[price] += quantity
            else:
                self.asks[price] = quantity
    
    def execute_market_order(self, side, quantity):
        """Ejecutar orden de mercado"""
        executed_qty = 0
        executed_price = 0
        
        if side == 'BUY':
            # Comprar: ejecutar contra las mejores asks
            sorted_asks = sorted(self.asks.items())
            for price, available_qty in sorted_asks:
                if executed_qty >= quantity:
                    break
                    
                take_qty = min(quantity - executed_qty, available_qty)
                executed_qty += take_qty
                executed_price = price
                
                # Actualizar el LOB
                self.asks[price] -= take_qty
                if self.asks[price] == 0:
                    del self.asks[price]
                    
                # Registrar trade
                self.trade_history.append({
                    'price': price, 
                    'quantity': take_qty, 
                    'side': 'BUY'
                })
                
                self.last_price = price
                
        else:  # SELL
            # Vender: ejecutar contra los mejores bids
            sorted_bids = sorted(self.bids.items(), reverse=True)
            for price, available_qty in sorted_bids:
                if executed_qty >= quantity:
                    break
                    
                take_qty = min(quantity - executed_qty, available_qty)
                executed_qty += take_qty
                executed_price = price
                
                # Actualizar el LOB
                self.bids[price] -= take_qty
                if self.bids[price] == 0:
                    del self.bids[price]
                    
                # Registrar trade
                self.trade_history.append({
                    'price': price, 
                    'quantity': take_qty, 
                    'side': 'SELL'
                })
                
                self.last_price = price
        
        return executed_qty, executed_price
    
    def get_best_bid_ask(self):
        """Obtener mejor bid y ask"""
        best_bid = max(self.bids.keys()) if self.bids else None
        best_ask = min(self.asks.keys()) if self.asks else None
        return best_bid, best_ask
    
    def get_spread(self):
        """Calcular spread"""
        best_bid, best_ask = self.get_best_bid_ask()
        if best_bid and best_ask:
            return best_ask - best_bid
        return None

# Crear LOB interactivo
interactive_lob = InteractiveLOB()

# Agregar algunas órdenes iniciales
initial_orders = [
    ('SELL', 102, 50), ('SELL', 101.5, 30), ('SELL', 101, 40),
    ('BUY', 100, 35), ('BUY', 99.5, 45), ('BUY', 99, 60)
]

for side, price, qty in initial_orders:
    interactive_lob.add_limit_order(side, price, qty)

print("✅ LOB Interactivo creado con órdenes iniciales!")

✅ LOB Interactivo creado con órdenes iniciales!


In [8]:
def plot_interactive_lob(lob):
    """Visualizar LOB interactivo con estilo mejorado"""
    fig = go.Figure()
    
    # Preparar datos
    if lob.bids:
        bid_prices = sorted(lob.bids.keys(), reverse=True)
        bid_quantities = [lob.bids[p] for p in bid_prices]
        bid_colors = ['#2E8B57' if i == 0 else '#90EE90' for i in range(len(bid_prices))]  # Mejor bid más oscuro
    else:
        bid_prices, bid_quantities, bid_colors = [], [], []
        
    if lob.asks:
        ask_prices = sorted(lob.asks.keys())
        ask_quantities = [lob.asks[p] for p in ask_prices]
        ask_colors = ['#DC143C' if i == 0 else '#FFB6C1' for i in range(len(ask_prices))]  # Mejor ask más oscuro
    else:
        ask_prices, ask_quantities, ask_colors = [], [], []
    
    # Bids (verde degradado)
    if bid_prices:
        fig.add_trace(go.Bar(
            x=bid_quantities,
            y=bid_prices,
            orientation='h',
            name='💚 Bids (Compra)',
            marker_color=bid_colors,
            text=[f'${p:.2f}<br>{q} unidades' for p, q in zip(bid_prices, bid_quantities)],
            textposition='auto',
            hovertemplate='<b>BID</b><br>Precio: $%{y:.2f}<br>Cantidad: %{x}<br><extra></extra>'
        ))
    
    # Asks (rojo degradado)
    if ask_prices:
        fig.add_trace(go.Bar(
            x=ask_quantities,
            y=ask_prices,
            orientation='h',
            name='❤️ Asks (Venta)',
            marker_color=ask_colors,
            text=[f'${p:.2f}<br>{q} unidades' for p, q in zip(ask_prices, ask_quantities)],
            textposition='auto',
            hovertemplate='<b>ASK</b><br>Precio: $%{y:.2f}<br>Cantidad: %{x}<br><extra></extra>'
        ))
    
    # Información del spread y mejores precios
    best_bid, best_ask = lob.get_best_bid_ask()
    spread = lob.get_spread()
    
    # Línea del último precio
    if best_bid and best_ask:
        fig.add_hline(
            y=lob.last_price, 
            line_dash="dash", 
            line_color="orange", 
            line_width=2,
            annotation_text=f"💰 Último: ${lob.last_price:.2f}",
            annotation_position="top right"
        )
    
    # Título dinámico con emojis y colores
    if spread:
        title_text = f"🎯 <b>LOB Interactivo</b> | 💰 Último: <span style='color:orange'>${lob.last_price:.2f}</span> | 📏 Spread: <span style='color:purple'>${spread:.2f}</span>"
        if best_bid:
            title_text += f" | 💚 Best Bid: <span style='color:green'>${best_bid:.2f}</span>"
        if best_ask:
            title_text += f" | ❤️ Best Ask: <span style='color:red'>${best_ask:.2f}</span>"
    else:
        title_text = f"🎯 <b>LOB Interactivo</b> | 💰 Último: <span style='color:orange'>${lob.last_price:.2f}</span>"
    
    fig.update_layout(
        title={
            'text': title_text,
            'x': 0.5,
            'xanchor': 'center',
            'font': {'size': 16}
        },
        xaxis_title="📊 Cantidad de Acciones",
        yaxis_title="💲 Precio ($)",
        height=600,
        barmode='overlay',
        plot_bgcolor='rgba(240,248,255,0.8)',  # Fondo azul claro
        paper_bgcolor='white',
        font={'family': 'Arial, sans-serif'},
        showlegend=True,
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.02,
            xanchor="center",
            x=0.5
        )
    )
    
    # Personalizar ejes
    fig.update_xaxes(
        gridcolor='rgba(0,0,0,0.1)',
        gridwidth=1,
        zeroline=True,
        zerolinecolor='rgba(0,0,0,0.3)'
    )
    
    fig.update_yaxes(
        gridcolor='rgba(0,0,0,0.1)',
        gridwidth=1,
        tickformat='$.2f'
    )
    
    return fig

# Mostrar LOB inicial
fig = plot_interactive_lob(interactive_lob)
fig.show()

In [9]:
# 🎛️ Panel de Control - Envío de Órdenes (Versión Visual)

# Crear widgets con estilo mejorado
order_type = widgets.Dropdown(
    options=['Limit Order', 'Market Order'],
    value='Limit Order',
    description='📋 Tipo:',
    style={'description_width': '100px'},
    layout=widgets.Layout(width='300px')
)

side = widgets.Dropdown(
    options=[('🟢 COMPRAR (BUY)', 'BUY'), ('🔴 VENDER (SELL)', 'SELL')],
    value='BUY',
    description='⚡ Lado:',
    style={'description_width': '100px'},
    layout=widgets.Layout(width='300px')
)

price_input = widgets.FloatText(
    value=100.0,
    step=0.1,
    description='💲 Precio:',
    disabled=False,
    style={'description_width': '100px'},
    layout=widgets.Layout(width='300px')
)

quantity_input = widgets.IntText(
    value=10,
    description='📊 Cantidad:',
    style={'description_width': '100px'},
    layout=widgets.Layout(width='300px')
)

send_button = widgets.Button(
    description='🚀 ENVIAR ORDEN',
    button_style='success',
    layout=widgets.Layout(width='300px', height='40px'),
    style={'font_weight': 'bold'}
)

# Botones de órdenes rápidas
quick_buy_button = widgets.Button(
    description='⚡ Compra Rápida (Market)',
    button_style='info',
    layout=widgets.Layout(width='200px', height='35px')
)

quick_sell_button = widgets.Button(
    description='⚡ Venta Rápida (Market)',
    button_style='warning',
    layout=widgets.Layout(width='200px', height='35px')
)

# Widget para mostrar estadísticas en tiempo real
stats_output = widgets.HTML(
    value="<div style='background-color: #f0f8ff; padding: 10px; border-radius: 5px; font-family: Arial;'><h4>📊 Estadísticas del Mercado</h4><p>Spread: Calculando...</p></div>",
    layout=widgets.Layout(width='100%')
)

output_area = widgets.Output()

# Función para actualizar estadísticas
def update_stats():
    best_bid, best_ask = interactive_lob.get_best_bid_ask()
    spread = interactive_lob.get_spread()
    
    total_bid_vol = sum(interactive_lob.bids.values()) if interactive_lob.bids else 0
    total_ask_vol = sum(interactive_lob.asks.values()) if interactive_lob.asks else 0
    
    if best_bid and best_ask:
        stats_html = f"""
        <div style='background: linear-gradient(135deg, #f0f8ff, #e6f3ff); 
                    padding: 15px; border-radius: 10px; 
                    border-left: 4px solid #4CAF50; 
                    font-family: Arial, sans-serif;'>
            <h4 style='margin: 0 0 10px 0; color: #2c3e50;'>📊 Estadísticas del Mercado</h4>
            <div style='display: flex; justify-content: space-between; margin: 5px 0;'>
                <span><strong>💚 Mejor Bid:</strong> <span style='color: green;'>${best_bid:.2f}</span></span>
                <span><strong>❤️ Mejor Ask:</strong> <span style='color: red;'>${best_ask:.2f}</span></span>
            </div>
            <div style='display: flex; justify-content: space-between; margin: 5px 0;'>
                <span><strong>📏 Spread:</strong> <span style='color: purple;'>${spread:.2f}</span></span>
                <span><strong>💰 Último:</strong> <span style='color: orange;'>${interactive_lob.last_price:.2f}</span></span>
            </div>
            <div style='display: flex; justify-content: space-between; margin: 5px 0;'>
                <span><strong>📈 Vol. Bids:</strong> {total_bid_vol}</span>
                <span><strong>📉 Vol. Asks:</strong> {total_ask_vol}</span>
            </div>
        </div>
        """
    else:
        stats_html = """
        <div style='background-color: #fff3cd; padding: 15px; border-radius: 10px; border-left: 4px solid #ffc107;'>
            <h4 style='margin: 0; color: #856404;'>⚠️ Mercado sin liquidez</h4>
        </div>
        """
    
    stats_output.value = stats_html

# Layout mejorado con diseño en columnas
header = widgets.HTML("""
<div style='background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
            padding: 20px; border-radius: 10px; color: white; text-align: center; margin-bottom: 15px;'>
    <h2 style='margin: 0; font-family: Arial;'>🎮 Simulador Interactivo de LOB</h2>
    <p style='margin: 5px 0 0 0; opacity: 0.9;'>Experimenta con órdenes y observa el comportamiento del mercado</p>
</div>
""")

controls_section = widgets.VBox([
    widgets.HTML("<h3 style='color: #2c3e50; margin: 10px 0;'>🎛️ Controles de Orden</h3>"),
    order_type,
    side,
    price_input,
    quantity_input,
    send_button
], layout=widgets.Layout(padding='10px'))

quick_actions = widgets.VBox([
    widgets.HTML("<h3 style='color: #2c3e50; margin: 10px 0;'>⚡ Acciones Rápidas</h3>"),
    widgets.HBox([quick_buy_button, quick_sell_button])
], layout=widgets.Layout(padding='10px'))

controls = widgets.VBox([
    header,
    widgets.HBox([controls_section, quick_actions], layout=widgets.Layout(justify_content='space-around')),
    stats_output,
    output_area
])

def on_order_type_change(change):
    """Deshabilitar precio para market orders"""
    price_input.disabled = (change['new'] == 'Market Order')

order_type.observe(on_order_type_change, names='value')

def send_order(button):
    """Enviar orden al LOB con feedback visual mejorado"""
    with output_area:
        clear_output(wait=True)
        
        try:
            order_side = side.value
            quantity = quantity_input.value
            
            # Mostrar mensaje de procesamiento
            print("🔄 Procesando orden...")
            
            if order_type.value == 'Limit Order':
                price = price_input.value
                interactive_lob.add_limit_order(order_side, price, quantity)
                
                # Mensaje con estilo
                side_emoji = "🟢" if order_side == "BUY" else "🔴"
                print(f"""
                ✅ ORDEN LIMITADA ENVIADA
                {side_emoji} Lado: {order_side}
                📊 Cantidad: {quantity} acciones
                💲 Precio: ${price:.2f}
                """)
                
            else:  # Market Order
                executed_qty, avg_price = interactive_lob.execute_market_order(order_side, quantity)
                if executed_qty > 0:
                    side_emoji = "🟢" if order_side == "BUY" else "🔴"
                    print(f"""
                    ✅ ORDEN DE MERCADO EJECUTADA
                    {side_emoji} Lado: {order_side}
                    📊 Ejecutado: {executed_qty}/{quantity} acciones
                    💰 Precio promedio: ${avg_price:.2f}
                    """)
                    if executed_qty < quantity:
                        print(f"⚠️ EJECUCIÓN PARCIAL: Solo se ejecutaron {executed_qty} de {quantity} acciones")
                else:
                    print("""
                    ❌ ORDEN NO EJECUTADA
                    💔 No hay suficiente liquidez en el mercado
                    """)
            
            # Actualizar visualización y estadísticas
            fig = plot_interactive_lob(interactive_lob)
            fig.show()
            update_stats()
                
        except Exception as e:
            print(f"❌ ERROR: {e}")

def quick_buy(button):
    """Función para compra rápida de mercado"""
    with output_area:
        clear_output(wait=True)
        print("⚡ COMPRA RÁPIDA EJECUTÁNDOSE...")
        
        executed_qty, avg_price = interactive_lob.execute_market_order('BUY', 15)
        if executed_qty > 0:
            print(f"""
            🟢 COMPRA RÁPIDA COMPLETADA
            📊 Cantidad: {executed_qty} acciones
            💰 Precio: ${avg_price:.2f}
            """)
        else:
            print("❌ No hay asks disponibles para comprar")
        
        fig = plot_interactive_lob(interactive_lob)
        fig.show()
        update_stats()

def quick_sell(button):
    """Función para venta rápida de mercado"""
    with output_area:
        clear_output(wait=True)
        print("⚡ VENTA RÁPIDA EJECUTÁNDOSE...")
        
        executed_qty, avg_price = interactive_lob.execute_market_order('SELL', 15)
        if executed_qty > 0:
            print(f"""
            🔴 VENTA RÁPIDA COMPLETADA
            📊 Cantidad: {executed_qty} acciones
            💰 Precio: ${avg_price:.2f}
            """)
        else:
            print("❌ No hay bids disponibles para vender")
        
        fig = plot_interactive_lob(interactive_lob)
        fig.show()
        update_stats()

# Conectar eventos
send_button.on_click(send_order)
quick_buy_button.on_click(quick_buy)
quick_sell_button.on_click(quick_sell)

# Actualizar estadísticas iniciales
update_stats()

# Mostrar controles
display(controls)

## 🎯 ¿Cómo usar el simulador?

### 📝 **Limit Orders** (Órdenes Limitadas)
- Especifica **precio** y **cantidad**
- Se añade al LOB en el nivel de precio indicado
- **No se ejecuta inmediatamente** (a menos que cruce el spread)

### ⚡ **Market Orders** (Órdenes de Mercado)
- Solo especifica **cantidad** (el precio se deshabilita)
- **Se ejecuta inmediatamente** contra las mejores órdenes del lado opuesto
- Puede ejecutarse parcialmente si no hay suficiente liquidez

### 🧪 **Experimentos que puedes hacer:**

1. **Envía una Limit Order BUY a $99**: Verás que se añade al lado de compra
2. **Envía una Market Order SELL de 20 acciones**: Se ejecutará contra los mejores bids
3. **Observa cómo cambia el spread** después de cada orden
4. **Prueba cruzar el spread** con una limit order (ej: BUY a $101.5)

¡Experimenta y observa cómo reacciona el mercado! 🚀

---

## 🧠 **Quiz Avanzado: Microestructura de Mercados**

<div style="background: linear-gradient(135deg, #e17055, #f39c12); padding: 20px; border-radius: 10px; color: white; text-align: center; margin: 20px 0;">
<h3>🔥 Desafío para Estudiantes de Máster</h3>
<p>Preguntas complejas sobre situaciones reales que ocurren en los mercados financieros</p>
<p><i>"¿Estás preparado para pensar como un trader profesional?"</i></p>
</div>

---

### **🚨 PREGUNTA 1: Market Order Gigante**

<div style="background-color: #fff3cd; border-left: 5px solid #f39c12; padding: 15px; margin: 10px 0; color: #856404;">
<h4 style="color: #856404;">💥 <b>Situación:</b> Un hedge fund quiere comprar 500,000 acciones YA (market order)</h4>
<p style="color: #856404;">El LOB actual solo tiene 50,000 acciones disponibles en el lado ASK (venta). ¿Qué sucede?</p>

<p style="color: #856404;"><b>A)</b> La orden se rechaza automáticamente</p>
<p style="color: #856404;"><b>B)</b> Solo se ejecutan 50,000 acciones y el resto se cancela</p>
<p style="color: #856404;"><b>C)</b> Se ejecutan 50,000 y el resto se convierte en limit order al último precio</p>
<p style="color: #856404;"><b>D)</b> El precio sube dramáticamente mientras "devora" todos los asks disponibles</p>
</div>

<div style='background: linear-gradient(135deg, #f39c12, #e67e22); padding: 20px; border-radius: 10px; color: white; margin: 15px 0;'>
<h4>💥 <b>RESPUESTA: D</b> ✅</h4>
<h4>Explicación Profesional:</h4>
<p><b>🎯 Concepto Clave:</b> MARKET IMPACT & PRICE SLIPPAGE</p>

<ul>
<li><b>Fase 1:</b> Se ejecutan las primeras 50,000 acciones a precios actuales</li>
<li><b>Fase 2:</b> El algoritmo "camina por el book" buscando más liquidez</li>
<li><b>Fase 3:</b> Precios suben dramáticamente (puede ser +5-10%)</li>
<li><b>Impacto:</b> El propio trade mueve el mercado ("moving the market")</li>
</ul>

<p><b>🏛️ En la realidad:</b> Los grandes fondos usan algoritmos TWAP/VWAP para fragmentar órdenes grandes y minimizar market impact.</p>
<p><b>⚠️ Riesgo:</b> Esto puede activar stop-losses en cascada y crear volatilidad extrema.</p>
</div>

---

### **🏃‍♂️ PREGUNTA 2: Desaparición Súbita de Liquidez**

<div style="background-color: #f8d7da; border-left: 5px solid #dc3545; padding: 15px; margin: 10px 0; color: #721c24;">
<h4 style="color: #721c24;">👻 <b>Escenario:</b> De repente, TODO el lado ASK desaparece en 1 segundo</h4>
<p style="color: #721c24;">¿Cuáles podrían ser las causas de este "flash crash" en el LOB?</p>

<p style="color: #721c24;"><b>A)</b> Error técnico del exchange</p>
<p style="color: #721c24;"><b>B)</b> Algoritmos de HFT retirando liquidez simultáneamente</p>
<p style="color: #721c24;"><b>C)</b> Noticia inesperada que cambió la percepción del mercado</p>
<p style="color: #721c24;"><b>D)</b> Todas las anteriores son posibles</p>
</div>

<div style='background: linear-gradient(135deg, #e74c3c, #c0392b); padding: 20px; border-radius: 10px; color: white; margin: 15px 0;'>
<h4>👻 <b>RESPUESTA: D</b> ✅</h4>
<h4>Análisis Multi-Factor:</h4>

<div style='background: rgba(255,255,255,0.1); padding: 10px; border-radius: 5px; margin: 10px 0;'>
<p><b>🤖 Factor HFT:</b> Algoritmos de alta frecuencia retiran órdenes en milisegundos cuando detectan:</p>
<ul>
<li>Flujo de órdenes agresivo</li>
<li>Cambios en correlaciones</li>
<li>Señales de información privilegiada</li>
</ul>
</div>

<div style='background: rgba(255,255,255,0.1); padding: 10px; border-radius: 5px; margin: 10px 0;'>
<p><b>📰 Factor Fundamental:</b> Noticias inesperadas (earnings miss, crisis geopolítica, etc.)</p>
</div>

<div style='background: rgba(255,255,255,0.1); padding: 10px; border-radius: 5px; margin: 10px 0;'>
<p><b>⚙️ Factor Técnico:</b> Fallos de conectividad, errores de software</p>
</div>

<p><b>💡 Insight Profesional:</b> Los "flash crashes" son multicausales. La liquidez moderna es más frágil que antes.</p>
</div>

---

### **📊 PREGUNTA 3: Order Flow Imbalance**

<div style="background-color: #e2e3e5; border-left: 5px solid #6c757d; padding: 15px; margin: 10px 0; color: #495057;">
<h4 style="color: #495057;">⚖️ <b>Observación:</b> Durante 30 minutos, llegan 90% buy orders vs 10% sell orders</h4>
<p style="color: #495057;">¿Qué indica este <b>order flow imbalance</b> severo?</p>

<p style="color: #495057;"><b>A)</b> Probable movimiento alcista del precio</p>
<p style="color: #495057;"><b>B)</b> Posible información privilegiada en el mercado</p>
<p style="color: #495057;"><b>C)</b> Los market makers ajustarán sus precios al alza</p>
<p style="color: #495057;"><b>D)</b> Todas las anteriores</p>
</div>

<div style='background: linear-gradient(135deg, #9b59b6, #8e44ad); padding: 20px; border-radius: 10px; color: white; margin: 15px 0;'>
<h4>⚖️ <b>RESPUESTA: D</b> ✅</h4>
<h4>Análisis Predictivo:</h4>

<p><b>📊 Implicaciones Inmediatas:</b></p>
<ul>
<li><b>Presión alcista:</b> Exceso de demanda vs oferta</li>
<li><b>Market makers</b> ajustarán precios al alza para equilibrar riesgo</li>
<li><b>Spread widening:</b> Mayor incertidumbre = mayor spread</li>
</ul>

<p><b>🕵️ Señales de Información Asimétrica:</b></p>
<ul>
<li>Posible filtración de earnings positivos</li>
<li>Rumores de M&A (fusiones/adquisiciones)</li>
<li>Información privilegiada de insiders</li>
</ul>

<p><b>🎯 Estrategia Profesional:</b> Los traders institucionales monitorizan order flow imbalance como indicador predictor (especialmente útil en timeframes de 5-30 minutos).</p>
</div>

---

### **🕵️ PREGUNTA 4: Detectando Información Asimétrica**

<div style="background-color: #d1ecf1; border-left: 5px solid #0c5460; padding: 15px; margin: 10px 0; color: #0c5460;">
<h4 style="color: #0c5460;">🔍 <b>Patrón Sospechoso:</b> Órdenes grandes y precisas llegan justo antes de anuncios</h4>
<p style="color: #0c5460;">Un trader siempre coloca órdenes de 100,000 acciones exactamente 10 minutos antes de earnings calls. ¿Qué podría estar pasando?</p>

<p style="color: #0c5460;"><b>A)</b> Coincidencia estadística</p>
<p style="color: #0c5460;"><b>B)</b> Algoritmo muy sofisticado de predicción</p>
<p style="color: #0c5460;"><b>C)</b> Posible insider trading (información privilegiada)</p>
<p style="color: #0c5460;"><b>D)</b> Market making legítimo</p>
</div>

<div style='background: linear-gradient(135deg, #16a085, #1abc9c); padding: 20px; border-radius: 10px; color: white; margin: 15px 0;'>
<h4>🕵️ <b>RESPUESTA: C</b> ✅</h4>
<h4>Análisis Forense del Trading:</h4>

<p><b>🚨 Red Flags de Insider Trading:</b></p>
<ul>
<li><b>Timing preciso:</b> Siempre antes de eventos importantes</li>
<li><b>Volúmenes inusuales:</b> Órdenes mucho mayores a lo normal</li>
<li><b>Consistencia sospechosa:</b> Rentabilidad "imposible"</li>
</ul>

<div style='background: rgba(255,255,255,0.1); padding: 10px; border-radius: 5px; margin: 10px 0;'>
<p><b>⚖️ Marco Legal:</b></p>
<ul>
<li>Violación de regulaciones SEC/CNMV</li>
<li>Sanciones penales y civiles</li>
<li>Prohibición de operar en mercados</li>
</ul>
</div>

<p><b>🛡️ Detección Moderna:</b> Los exchanges usan ML y AI para detectar patrones anómalos en tiempo real.</p>
</div>

---

### **⚡ PREGUNTA 5: High-Frequency Trading Impact**

<div style="background-color: #f3e2f3; border-left: 5px solid #6f42c1; padding: 15px; margin: 10px 0; color: #493558;">
<h4 style="color: #493558;">🤖 <b>Fenómeno HFT:</b> El spread cambia 1000 veces por segundo</h4>
<p style="color: #493558;">Los algoritmos de alta frecuencia están constantemente ajustando precios. ¿Cuál es el impacto en traders retail?</p>

<p style="color: #493558;"><b>A)</b> Mejores precios para todos (menor spread)</p>
<p style="color: #493558;"><b>B)</b> Mayor dificultad para traders manuales</p>
<p style="color: #493558;"><b>C)</b> Aumento de la volatilidad intraday</p>
<p style="color: #493558;"><b>D)</b> Todas las anteriores</p>
</div>

<div style='background: linear-gradient(135deg, #6c5ce7, #a29bfe); padding: 20px; border-radius: 10px; color: white; margin: 15px 0;'>
<h4>🤖 <b>RESPUESTA: D</b> ✅</h4>
<h4>Paradoja del HFT:</h4>

<div style='display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin: 15px 0;'>
<div style='background: rgba(255,255,255,0.1); padding: 15px; border-radius: 5px;'>
<h5>✅ BENEFICIOS</h5>
<ul>
<li>Spreads más estrechos</li>
<li>Mayor liquidez promedio</li>
<li>Eficiencia de precios</li>
<li>Menores costos de transacción</li>
</ul>
</div>
<div style='background: rgba(255,255,255,0.1); padding: 15px; border-radius: 5px;'>
<h5>❌ PROBLEMAS</h5>
<ul>
<li>Volatilidad intraday</li>
<li>Flash crashes</li>
<li>Liquidez "fantasma"</li>
<li>Ventaja tecnológica injusta</li>
</ul>
</div>
</div>

<p><b>🎯 Realidad para Retail Traders:</b> Necesitan adaptarse usando órdenes inteligentes (iceberg, hidden, etc.) y timeframes más largos.</p>
</div>

---

### **💣 PREGUNTA 6: Circuit Breaker**

<div style="background-color: #f8d7da; border-left: 5px solid #721c24; padding: 15px; margin: 10px 0; color: #721c24;">
<h4 style="color: #721c24;">🛑 <b>Crisis:</b> El precio cae 20% en 5 minutos, se activa circuit breaker</h4>
<p style="color: #721c24;">El mercado se pausa por 15 minutos. ¿Qué esperarías que pase cuando reabre?</p>

<p style="color: #721c24;"><b>A)</b> Vuelta inmediata a precios normales</p>
<p style="color: #721c24;"><b>B)</b> Spread extremadamente ancho (baja liquidez)</p>
<p style="color: #721c24;"><b>C)</b> Avalancha de órdenes acumuladas</p>
<p style="color: #721c24;"><b>D)</b> B y C son correctas</p>
</div>

<div style='background: linear-gradient(135deg, #e55039, #ff3838); padding: 20px; border-radius: 10px; color: white; margin: 15px 0;'>
<h4>🛑 <b>RESPUESTA: D</b> ✅</h4>
<h4>Dinámica Post-Pausa:</h4>

<p><b>⚡ Al Reabrir el Mercado:</b></p>
<ul>
<li><b>Spread masivo:</b> Market makers aumentan spreads por incertidumbre</li>
<li><b>Órdenes acumuladas:</b> 15 minutos de presión de venta reprimida</li>
<li><b>Volatilidad extrema:</b> Primeros minutos muy turbulentos</li>
<li><b>Volume spike:</b> Picos de volumen 5-10x superiores a lo normal</li>
</ul>

<div style='background: rgba(255,255,255,0.1); padding: 10px; border-radius: 5px; margin: 10px 0;'>
<p><b>🧠 Psicología del Mercado:</b></p>
<p>La pausa amplifica el pánico. Los inversores interpretan el circuit breaker como confirmación de que "algo muy malo está pasando".</p>
</div>

<p><b>📈 Oportunidad:</b> Algunos traders contrarian ven estos momentos como oportunidades de compra (si tienen liquidez y aguante psicológico).</p>
</div>

---

<div style='background: linear-gradient(135deg, #667eea, #764ba2); padding: 25px; border-radius: 15px; color: white; text-align: center; margin: 25px 0;'>
<h2>🎓 EVALUACIÓN NIVEL MÁSTER</h2>

<div style='text-align: left; margin: 20px auto; max-width: 600px;'>
<h4>🏆 Criterios de Evaluación:</h4>
<ul>
<li><b>6/6 Correctas:</b> 🌟 Listo para trading institucional</li>
<li><b>4-5/6:</b> 📈 Excelente comprensión de microestructura</li>
<li><b>3/6:</b> 📚 Buen nivel, revisar conceptos avanzados</li>
<li><b>1-2/6:</b> 🤔 Necesita más estudio de mercados reales</li>
<li><b>0/6:</b> 📖 Volver a conceptos fundamentales</li>
</ul>
</div>

<h4>💡 COMPETENCIAS EVALUADAS:</h4>
<p>✅ Market Impact & Price Discovery<br>
✅ Liquidity Dynamics & HFT Effects<br>
✅ Information Asymmetry Detection<br>
✅ Crisis Management & Circuit Breakers<br>
✅ Order Flow Analysis<br>
✅ Regulatory & Ethical Awareness</p>

<div style='background: rgba(255,255,255,0.1); padding: 15px; border-radius: 8px; margin: 20px 0;'>
<h4>🚀 PRÓXIMO NIVEL:</h4>
<p>Si dominaste este quiz, estás preparado para temas como:</p>
<p><b>• Dark Pools • Algorithmic Trading • Market Making • Risk Management</b></p>
</div>
</div>

# 🎬 **ANIMACIONES DINÁMICAS - MERCADO EN MOVIMIENTO**

---

<div style='background: linear-gradient(135deg, #ff6b6b, #ee5a52); padding: 25px; border-radius: 15px; color: white; text-align: center; margin: 25px 0;'>
<h2>🚀 SIMULACIÓN EN TIEMPO REAL</h2>
<p><b>Vamos a ver cómo se mueve el LOB en vivo</b></p>
</div>


In [17]:
# 🔥 ULTIMATE ORDER BOOK - Versión Optimizada y Standalone

import random
import time
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from IPython.display import clear_output

class UltimateOrderBook:
    """
    Order Book standalone con visualización completa y optimizada:
    - Order Book en tiempo real (5 niveles bid/ask)
    - Mid Price Evolution (precio medio histórico)
    - Spread Evolution (dinámica de liquidez)
    """
    
    def __init__(self, base_lob):
        self.base_lob = base_lob
        
        # Datos actuales del mercado
        self.current_bids = {}
        self.current_asks = {}
        
        # Historiales para gráficos
        self.mid_price_history = []
        self.spread_history = []
        self.timestamps = []
        
        # Precio base para simulación
        self.base_price = 149.5
        
        print("✅ UltimateOrderBook optimizado creado!")
    
    def generate_realistic_market_data(self):
        """Genera datos de mercado realistas y eficientes"""
        # Generar spread aleatorio entre 0.1 y 0.5
        spread = random.uniform(0.1, 0.5)
        
        # Precio base con ligera variación
        price_change = random.uniform(-0.3, 0.3)
        self.base_price += price_change
        
        # Asegurar que el precio se mantenga en rango razonable
        self.base_price = max(148.0, min(151.0, self.base_price))
        
        # Calcular mejor bid y ask
        best_bid = self.base_price - spread/2
        best_ask = self.base_price + spread/2
        
        # Generar 5 niveles de cada lado
        self.current_bids = {}
        self.current_asks = {}
        
        # Bids (precios descendentes desde el mejor)
        for i in range(5):
            price = best_bid - (i * random.uniform(0.05, 0.15))
            volume = random.randint(10, 100)
            self.current_bids[round(price, 2)] = volume
        
        # Asks (precios ascendentes desde el mejor)
        for i in range(5):
            price = best_ask + (i * random.uniform(0.05, 0.15))
            volume = random.randint(10, 100)
            self.current_asks[round(price, 2)] = volume
        
        return best_bid, best_ask, spread
    
    def simulate_market_tick(self):
        """Simula un tick del mercado de forma eficiente"""
        best_bid, best_ask, spread = self.generate_realistic_market_data()
        
        # Calcular mid price
        mid_price = (best_bid + best_ask) / 2
            
        # Actualizar historiales
        self.mid_price_history.append(mid_price)
        self.spread_history.append(spread)
        self.timestamps.append(len(self.timestamps))
        
        # Mantener historial limitado (últimos 30 ticks para mejor rendimiento)
        if len(self.mid_price_history) > 30:
            self.mid_price_history.pop(0)
            self.spread_history.pop(0)
            self.timestamps.pop(0)
            
        return best_bid, best_ask, spread
    
    def create_orderbook_visualization(self):
        """Crea visualización optimizada con 3 subgráficos"""
        
        # Obtener datos actuales
        bid_prices = sorted(self.current_bids.keys(), reverse=True)[:5]
        ask_prices = sorted(self.current_asks.keys())[:5]
        
        # Calcular precio medio
        if bid_prices and ask_prices:
            mid_price = (bid_prices[0] + ask_prices[0]) / 2
        else:
            mid_price = self.base_price
        
        # Crear subplots optimizados
        fig = make_subplots(
            rows=3, cols=1,
            row_heights=[0.6, 0.2, 0.2],  # Simplificado
            subplot_titles=[
                f'📊 ORDER BOOK - Mid: ${mid_price:.2f}',
                '💰 Mid Price',
                '📏 Spread'
            ],
            vertical_spacing=0.15
        )
        
        # ============ ORDER BOOK ============
        
        # Preparar datos optimizados
        if ask_prices:
            ask_y_pos = list(range(9, 4, -1))
            ask_vols = [self.current_asks[price] for price in reversed(ask_prices)]
            ask_labels = [f"${price:.2f}" for price in reversed(ask_prices)]
            
            fig.add_trace(go.Bar(
                y=ask_y_pos, x=ask_vols, orientation='h',
                marker_color='rgba(255, 50, 50, 0.9)',  # Rojo más brillante para fondo negro
                text=ask_labels, textposition='inside', name='Asks',
                textfont=dict(color='white', size=12)  # Texto blanco
            ), row=1, col=1)
        
        if bid_prices:
            bid_y_pos = list(range(4, -1, -1))
            bid_vols = [self.current_bids[price] for price in bid_prices]
            bid_labels = [f"${price:.2f}" for price in bid_prices]
            
            fig.add_trace(go.Bar(
                y=bid_y_pos, x=bid_vols, orientation='h',
                marker_color='rgba(50, 255, 50, 0.9)',  # Verde más brillante para fondo negro
                text=bid_labels, textposition='inside', name='Bids',
                textfont=dict(color='white', size=12)  # Texto blanco
            ), row=1, col=1)
        
        # Línea del precio medio (más brillante para fondo negro)
        fig.add_hline(y=4.5, line_dash="dash", line_color="yellow", 
                     line_width=3, row=1, col=1,
                     annotation=dict(text=f"MID: ${mid_price:.2f}", 
                                   font=dict(color="yellow", size=14)))
        
        # ============ GRÁFICOS DE HISTORIAL ============
        
        if len(self.mid_price_history) > 1:
            fig.add_trace(go.Scatter(
                x=self.timestamps, y=self.mid_price_history,
                mode='lines+markers', name='Mid Price',
                line=dict(color='cyan', width=3),  # Cian brillante para fondo negro
                marker=dict(color='cyan', size=4)
            ), row=2, col=1)
        
        if len(self.spread_history) > 1:
            fig.add_trace(go.Scatter(
                x=self.timestamps, y=self.spread_history,
                mode='lines+markers', name='Spread',
                line=dict(color='magenta', width=3),  # Magenta brillante para fondo negro
                marker=dict(color='magenta', size=4),
                fill='tozeroy', fillcolor='rgba(255, 0, 255, 0.2)'
            ), row=3, col=1)
        
        # ============ LAYOUT OPTIMIZADO - FONDO NEGRO ============
        fig.update_layout(
            title='🔴 LIVE ORDER BOOK',
            height=700,  # Reducido para mejor rendimiento
            showlegend=False,
            template="plotly_dark",  # Fondo negro
            plot_bgcolor='black',
            paper_bgcolor='black'
        )
        
        # Configurar ejes
        fig.update_yaxes(
            tickvals=list(range(10)),
            ticktext=['B5', 'B4', 'B3', 'B2', 'B1', 'A1', 'A2', 'A3', 'A4', 'A5'],
            row=1, col=1
        )
        
        return fig
    
    def start_simulation(self, duration=15, update_interval=1.5):
        """Simulación optimizada con menor frecuencia de actualización"""
        print(f"🚀 Iniciando simulación optimizada ({duration}s, cada {update_interval}s)")
        
        start_time = time.time()
        while time.time() - start_time < duration:
            clear_output(wait=True)
            
            # Generar nuevo tick
            self.simulate_market_tick()
            
            # Mostrar visualización
            fig = self.create_orderbook_visualization()
            fig.show()
            
            # Mostrar info básica
            if self.mid_price_history:
                print(f"💰 Mid Price: ${self.mid_price_history[-1]:.2f}")
            if self.spread_history:
                print(f"📏 Spread: ${self.spread_history[-1]:.3f}")
            
            time.sleep(update_interval)
        
        print("✅ Simulación completada!")

print("✅ UltimateOrderBook optimizado listo!")
print("⚡ Mejoras aplicadas:")
print("   • Sin dependencias externas")
print("   • Generación de datos más rápida")
print("   • Historial limitado (30 vs 50)")
print("   • Visualización simplificada")
print("   • Intervalo de actualización mayor")

✅ UltimateOrderBook optimizado listo!
⚡ Mejoras aplicadas:
   • Sin dependencias externas
   • Generación de datos más rápida
   • Historial limitado (30 vs 50)
   • Visualización simplificada
   • Intervalo de actualización mayor


In [18]:
# 🚀 Crear instancia optimizada

# Crear la instancia del Ultimate Order Book optimizado
ultimate_lob = UltimateOrderBook(lob)

print("🎉 Ultimate Order Book optimizado creado!")
print("📊 Funcionalidades:")
print("   📊 Order Book (5 niveles)")
print("   💰 Mid Price tracking")
print("   📏 Spread monitoring")
print()
print("🎯 Comandos rápidos:")
print("   ultimate_lob.create_orderbook_visualization().show()  # Vista única")
print("   ultimate_lob.start_simulation(15, 2.0)               # 15s cada 2s")

✅ UltimateOrderBook optimizado creado!
🎉 Ultimate Order Book optimizado creado!
📊 Funcionalidades:
   📊 Order Book (5 niveles)
   💰 Mid Price tracking
   📏 Spread monitoring

🎯 Comandos rápidos:
   ultimate_lob.create_orderbook_visualization().show()  # Vista única
   ultimate_lob.start_simulation(15, 2.0)               # 15s cada 2s


In [19]:
# ⚡ Demo ultra-rápido - Solo datos (sin gráfico pesado)

print("⚡ DEMO ULTRA-RÁPIDO")
print("="*40)

# Generar datos de prueba rápidamente
print("🔄 Generando datos de mercado...")
ultimate_lob.simulate_market_tick()

# Mostrar estado actual
if ultimate_lob.mid_price_history:
    mid_price = ultimate_lob.mid_price_history[-1]
    spread = ultimate_lob.spread_history[-1]
    
    print(f"💰 Mid Price: ${mid_price:.2f}")
    print(f"📏 Spread: ${spread:.3f}")
    
    # Mostrar mejores precios
    bid_prices = sorted(ultimate_lob.current_bids.keys(), reverse=True)
    ask_prices = sorted(ultimate_lob.current_asks.keys())
    
    if bid_prices and ask_prices:
        print(f"🟢 Best Bid: ${bid_prices[0]:.2f}")
        print(f"🔴 Best Ask: ${ask_prices[0]:.2f}")
        
        # Mostrar book de forma simple (texto)
        print("\n📊 ORDER BOOK (top 3 niveles):")
        print("--- ASKS ---")
        for i, price in enumerate(ask_prices[:3]):
            vol = ultimate_lob.current_asks[price]
            print(f"  ${price:.2f} | {vol:3d}")
        print("--- BIDS ---") 
        for i, price in enumerate(bid_prices[:3]):
            vol = ultimate_lob.current_bids[price]
            print(f"  ${price:.2f} | {vol:3d}")

print("\n✅ Demo completado rápidamente!")
print("💡 Para ver gráfico: ultimate_lob.create_orderbook_visualization().show()")

⚡ DEMO ULTRA-RÁPIDO
🔄 Generando datos de mercado...
💰 Mid Price: $149.37
📏 Spread: $0.361
🟢 Best Bid: $149.19
🔴 Best Ask: $149.55

📊 ORDER BOOK (top 3 niveles):
--- ASKS ---
  $149.55 |  45
  $149.64 |  51
  $149.68 |  43
--- BIDS ---
  $149.19 |  43
  $149.12 |  29
  $149.07 |  49

✅ Demo completado rápidamente!
💡 Para ver gráfico: ultimate_lob.create_orderbook_visualization().show()


In [20]:
# 🎬 Simulación optimizada (más rápida)

print("🎬 SIMULACIÓN OPTIMIZADA")
print("="*40)
print("⚡ Configuración rápida:")
print("   • Duración: 12 segundos")
print("   • Actualización cada 2 segundos")
print("   • Historial limitado a 30 ticks")
print("   • Visualización simplificada")
print()
print("🚀 Iniciando...")

# Simulación más rápida
ultimate_lob.start_simulation(duration=12, update_interval=0.5)

💰 Mid Price: $149.86
📏 Spread: $0.343
✅ Simulación completada!
✅ Simulación completada!
